### ISSUE TITLE
Opening Jukebox-Options leads to crash

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#1]
If no songs are loaded the applications crashes when selecting Jukebox-Options.
See Screen shot:
![Error Screenshot](https://i.imgur.com/M6dcdWE.png)

Steps to reproduce:
1. Open USDX
2. Enter Options
3. Select Jukebox
4. Crash

Version latest.7z from 15-Dec-2015 10:30
OS Windows 10 64bit

**Comment by dracoTrier** [comment]
please confirm that this doesn't happen when at least one song file is loaded. thanks.

**Comment by tobijdc** [comment]
Confirmed with 1 song (or with 526 songs) loaded this Error does not occur.

**Comment by basisbit** [comment]
this is also fixed as of now.
