### ISSUE TITLE
[Installer] Wrong encoding of the polish language file for the installer

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#108]
The polish language file \installer\languages\Polish.nsh cotains bad characters such as "po³¹czenie" which AFAIK should be "połączenie". I've corrected some characters which I recognized being wrong and being able to check with some translation tools. But I believe there are more than the ones I corrected.

Once transifex is supported (#102), it'll be easier to check and correct these translations.

**Comment by Goostav5** [comment]
Done by 65ebaf7e720c3f63c56b7d370efc0bae3e88fadf

**Comment by RattleSN4K3** [comment]
Looks good from my side. basisbit replied in the merge request #191 regarding transifex. You can [join our project](https://www.transifex.com/usdx/usdx/) over there in order to fully translate polish (or any language you're able to translate). Polish is about 56% complete. @AlexanderS will likely merge the changes from here (this commit) over to transifex. IIRC the workflow of translation would be using transifex instead of directly translating it here. But that depends on how AlexanderS prefers it.

Closing this issue as being resolved by #191.
