### ISSUE TITLE
If Camera is not correctly configured pressing W leads to crash

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#11]
Pressing W during singing (or Jukebox) crashes USDX.

Steps to reproduce:
1) Options
2) Webcam
3) Select Webcam that not exists (maybe possible because of copied .ini file?)
4) Go to Sing
5) Select Song
6) Press W
7) Crash

![Error](https://i.imgur.com/P4v5qP1.png)

**Comment by basisbit** [comment]
fixed as of today.
