### ISSUE TITLE
[Feature Request] Switch sorting / Tabs ON/OFF at runtime (without restart)

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#114]
The title pretty much says it all. Sometimes you have that one person that would really like to see all your [language] songs, so you have to enable Tabs, then select language as sorting and THEN you have to restart the game. It would be nice to be able to change the sorting in-game, just like in the CMD version of the program.

**Comment by RattleSN4K3** [comment]
AFAIK, it is planned (judging from the source). It hasn't been done as there were other stuff to look at or the personal interest (speaking for myself here). Hopefully, it will be a _new feature_ in upcoming days/weeks/months. So thanks for the _issue_ to keep us notified :+1:

**Comment by bohning** [comment]
If it is okay with you guys, I would add a few other "issues"/feature requests along the way that I really appreciate about the CMD version that I would love to see in the new UltraStar deluxe. I have been playing and working with UltraStar ever since the original release by Corvus and have followed pretty much all the developments in all those years (wow, that must be more way more than ten years...!).

Thank you so much for your efforts, I really appreciate it! Are some of you on the IRC chat?

Best regards!

**Comment by basisbit** [comment]
sure, feel free to add feature requests. We will mark these appropriately and eventually implement them.
Yes, there are some of us idling in the IRC channel. Just don't expect immediate responses.
