### ISSUE TITLE
In 1.3 there are some videos jitter and stutter - but those were playing okay in 1.1

### ISSUE THREAD

**Issue by diver66** [UltraStar-Deluxe/USDX#118]
I noticed that some videos stutter and jitter in the preview and also when they being reproduced. In the old version 1.1 they were playing okay. Is there a way I could upload one of his jittery movies, so you guys can have a look at it ?

**Comment by basisbit** [comment]
what file ending does the video file have?
By jitter, do you mean that the video stutters (frames out of order) or that the video is like maybe 200ms late?

**Comment by diver66** [comment]
thanks for the quick reply, the videos actually shake, jitter and stutter. The file ending is always MP4.

**Comment by basisbit** [comment]
Please try if renaming the file ending to something else and then adjusting the filename in the .txt solves the issue.

**Comment by diver66** [comment]
Yes, now it works, just by renaming the filename extension to *.abc
should I go ahead and do this to all the mp4s in question, or is there an easier way or might this be working in a future version of ultrastar ?

**Comment by basisbit** [comment]
We will fix that issue within the next weeks because this is quite a critical issue.

**Comment by basisbit** [comment]
@s09bQ5 could you maybe help us and try to fix this issue?
When setting 'fCodecContext^.flags := CODEC_FLAG_LOW_DELAY;' in 'UVideo::TVIDEO_FFmpeg.Open' , then AVI encoded videos do stutter (video frames are played out of order). The 'CODEC_FLAG_LOW_DELAY' flag is currently required to have video and audio in sync. This problem appeared when we switched from ffmpeg 2.6 to ffmpeg 2.8.

**Comment by s09bQ5** [comment]
I can't seen to be able to reproduce this with my videos. Can someone upload a test video somewhere (Google Drive, Dropbox, WeTransfer, ...)? Or are there ffmpeg encoding parameters that definitely create an affected video?

According to #160 we have a video delay if we don't use CODEC_FLAG_LOW_DELAY and according to this issue frames might be returned by the decoder in the wrong order if we do use CODEC_FLAG_LOW_DELAY. Sounds to me like we should not use the flag and instead try to find the correct pts.

**Comment by basisbit** [comment]
[here](https://yaycdn.de/WiseGuysMenschwobistdu.7z) some example file with video frames out of order when CODEC_FLAG_LOW_DELAY is set (just comment out the if avi check in TVIDEO_FFmpeg.Open.

**Comment by basisbit** [comment]
verified that this fixes playback of the mentioned videos
