### ISSUE TITLE
Weird scoring for multiple players getting the same audio signal

### ISSUE THREAD

**Issue by GrueneNeun** [UltraStar-Deluxe/USDX#121]
I noticed a different scoring during singing even though all players got the exact same audio signal. I assumed that with the same input the score should also be the same. This behaviour is reproducable as seen by multiple attached screenshots.

My testing environment looks like this: A wireless microphone connected to a Behringer X18 which is then connected to the UltraStar Laptop using an USB connector. On the Laptop "O Deus ASIO Link Pro" takes the signal and splits it to 3 different virtual WDM soundcards with 2 channels each so that UltraStar can process the input. After the X18 there is no point in which the audio signal is altered. The audio output of Ultrastar is also routed via a virtual WDM soundcard and "O Deus ASIO Link Pro" to the X18.
The UltraStar version was downloaded yesterday via the 1.3.2 Beta portable link.

I attach the config of "O Deus ASIO Link Pro" and the recording settings of UltraStar and some sample Score-Tabs which describe the issue.

If you need more information or files please let me now.

![asio-config 1to6](https://cloud.githubusercontent.com/assets/12693822/17837331/1734485c-67b1-11e6-92dd-2b14d9ba03c6.JPG)
The 2 green lines are the left and right audio output from UltraStar (via a virtual WDM soundcard configured as standard device) to channels 7 and 8 of the ASIO Link (via USB cable to the X18).
The 4 red lines are the "normal" microphone inputs from the ASIO Link for further distribution.
The 6 yellow lines are the routed output from ASIO channel 3 (microphone 1) to the input of the first 3 virtual WDM soundcards which are used by UltraStar.

![screenshot0005](https://cloud.githubusercontent.com/assets/12693822/17837332/1736417a-67b1-11e6-9317-d83d15dfc554.jpg)
![screenshot0006](https://cloud.githubusercontent.com/assets/12693822/17837335/173fd4c4-67b1-11e6-8f83-c3419e413808.jpg)
![screenshot0007](https://cloud.githubusercontent.com/assets/12693822/17837334/173dce54-67b1-11e6-80fa-596cfc963e2c.jpg)
![screenshot0008](https://cloud.githubusercontent.com/assets/12693822/17837336/17418c7e-67b1-11e6-94e6-606b081c2830.jpg)
![screenshot0009](https://cloud.githubusercontent.com/assets/12693822/17837333/173bdb08-67b1-11e6-8e41-3e73e2508640.jpg)
![screenshot0010](https://cloud.githubusercontent.com/assets/12693822/17837337/174c47fe-67b1-11e6-86e3-8254f0f6deb6.jpg)

**Comment by RattleSN4K3** [comment]
There's a latency of 25ms for output configured (in your linking screenshot). May this be the origin of the differing score?

**Comment by GrueneNeun** [comment]
I dont think so, because 25ms is the default setting and is configured for all 3 virtual WDM soundcards. I can try next weekend without this latency.
While checking the scores again, i noticed that in 2 of 3 cases the players on the same virtual soundcard have the same score, thóugh this may differ from the other scores... I'll get my voice ready for further testing next weekend to get a clearer view of the situation... But atm it looks like the ASIO Link Software does something weird....

**Comment by basisbit** [comment]
does not look like a bug. feel free to reopen if still relevant.
