### ISSUE TITLE
USDX crashes when using FLV file as #MP3

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#124]
When using a flv file (with audio track) as the #MP3 tag, USDX may crash when starting the song or when the song ends (Escape or regularly).

An example test file would be [Jonathan Coulton 'Code Monkey'](https://sourceforge.net/projects/ultrastardx/files/Songs/Jonathan%20Coulton%20%28CC%20License%20-%20BY-NC%203.0%29/usdx_song-jonathan_coulton_-_code_monkey.zip/download) with the following txt header section:

```
#TITLE:Code Monkey
#ARTIST:Jonathan Coulton
#LANGUAGE:English
#MP3:Jonathan Coulton - Code Monkey [VD#4].flv
#COVER:Jonathan Coulton - Code Monkey [CO].jpg
#BACKGROUND:Jonathan Coulton - Code Monkey [BG].jpg
#VIDEO:Jonathan Coulton - Code Monkey [VD#4].flv
#VIDEOGAP:4
#BPM:320
#GAP:675
```

**Comment by basisbit** [comment]
fixed. can someone else please confirm this?
