### ISSUE TITLE
[Feature Request] Switch to a random song on keypress

### ISSUE THREAD

**Issue by WebsiteDeveloper** [UltraStar-Deluxe/USDX#125]
I would like to have button in the song overview i can use so that a random song gets selected.
I am not really familliar with the code of ultrastar but i would eventually like to try digging into it and implementing the feature myself if someone would point me in the right directions.

**Comment by RattleSN4K3** [comment]
Just in case someone stumbles upon this request, the feature is already implemented and documented in the Readme.txt, documentation or the Readme.md:
https://github.com/UltraStar-Deluxe/USDX/blob/master/README.md#4-controls

By pressing the [R] key, it will select a random song in a song selection screen.
