### ISSUE TITLE
Audio crash while Processing VoiceStream (possible fix included)

### ISSUE THREAD

**Issue by rollany** [UltraStar-Deluxe/USDX#132]
Hi,

I had repeated crashes while playing song + microphone playback.
After Debug, the program crashes with a "double free or corruption", at:
src/media/UAudioPlayback_SoftMixer.pas:1070 -> TGenericVoiceStream.WriteData

It seems that the BufferLock value is recreated and destroyed each time (call to SDL_CreateMutex() and SDL_DestroyMutex()), instead of just SDL_LockMutex/SDL_UnlockMutex.

I just took a quick look so I am not 100% sure, but since I made the changes, no more crashes.

I provide a patch for it : [SDLMutex.txt](https://github.com/UltraStar-Deluxe/USDX/files/478552/SDLMutex.txt)

Thanks for the soft, apart from this issue, it has been working great so far and have a lot of fun with it.

**Comment by basisbit** [comment]
coud you please create a pull request for your changes? Thanks a lot for providing the patch! It helps a lot 😃

**Comment by basisbit** [comment]
patch is now applied. Thanks @rollany for your help!
