### ISSUE TITLE
Problem with duet songs (UltraStar Deluxe v1.3.2 beta)

### ISSUE THREAD

**Issue by znxineohp** [UltraStar-Deluxe/USDX#133]
Hi,
I've run into a problem on the UltraStar Deluxe v1.3.2 beta version.
When the a song is a duet the bottom of the screen (P2) has the shaded strip so you can see the lyrics but the top (P1) the shading is missing and you can't see the lyrics.
How do I correct this?

Cheers

**Comment by basisbit** [comment]
Hi znxineohp,
what theme are you using?

**Comment by znxineohp** [comment]
Theme = Deluxe
Skin = Ocean
Colour = Red

Cheers

**Comment by basisbit** [comment]
this should also be fixed by recent changes. please confirm if possible.
