### ISSUE TITLE
libpng16-16 not in repo

### ISSUE THREAD

**Issue by andy5995** [UltraStar-Deluxe/USDX#142]
On Debian Jessie, libpng16-16 isn't available in my repo, but libpng12-dev is. Is 12 sufficient?

> for current debian / ubuntu: sudo apt-get update && sudo apt-get install git fpc libsdl2-dev libsdl2-image-dev libsdl2-image-2.0-0 libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-mixer-dev libsdl2-net-2.0-0 libsdl2-net-dev libsdl2-ttf-2.0-0 libsdl2-ttf-dev libsdl2-gfx-1.0-0 libsdl2-gfx-dev ffmpeg libavdevice-dev libsqlite3-0 libsqlite3-dev libpcre3 libpcre3-dev ttf-dejavu ttf-freefont portaudio19-dev lua5.1-dev libpng16-16 libopencv-highgui-dev libprojectm-dev

**Comment by basisbit** [comment]
libpng 12 should be compatible. Please just try and report your results here.

**Comment by andy5995** [comment]
ok. I added my results thus far to #131 and included my config.log

**Comment by andy5995** [comment]
I ran the program and navigated through several menus, and played part of a song. I didn't notice any graphics problems, but I don't know how the program uses libpng. But I think it's pretty safe to say there's no problem.

If you'd like, I can update the apt-get line in the README (quoted above) and make the change.

If I do that, what do you think if I changed the bass line (no pun intended) to something like

bass (not needed for POSIX/Linux builds)

**Comment by basisbit** [comment]
no need for that change. otherwise we would have to add bunch of lines for the various old debian/ubuntu/fedora/opensuse/other distributions. Instead, it currently shows what is supported and tested properly (checked the API documentation for correct type sizes,...)
