### ISSUE TITLE
[MacOS] USB Microphones only produce noise

### ISSUE THREAD

**Issue by dorphalsig** [UltraStar-Deluxe/USDX#150]
Hi, great that you guys got this working on mac. It kicks ass!  However, when I connect external (USB) mics to my mac they wont record sound but noise. Oddly enough it only happens in mac, when I run USDX on my windows vm (on the same mac) everything works fine. Any idea why this is happening?

BTW, Using MacOS Sierra

Thx!!

**Comment by basisbit** [comment]
could you please retry if the recent changes one hour ago fixed the issue for you?

**Comment by dorphalsig** [comment]
Hey, thanks for letting me know. Didn't work tho :(

**Comment by basisbit** [comment]
sorry, then I can't help. maybe @kamischi can help you.

**Comment by dorphalsig** [comment]
Can I capture any debug data that would work for you guys?

**Comment by ePirat** [comment]
Are you able to use that microphone with other applications on macOS, or do you get noise there as well?

**Comment by dorphalsig** [comment]
Hi, the microphones work with no issues, I've done test recordings with
QuickTime and they work fine. Even more, right now, as a workaround, I'm
running usdx on a Windows 7 vm and its working fine.

I am not sure how to get some logs that could help with the issue
diagnostic, but if you tell me what info you need and how to get it I'll be
glad to help.

Thx
David s

Am 26.02.2017 4:19 nachm. schrieb "ePirat" <notifications@github.com>:

**Comment by dorphalsig** [comment]
Hi! Just wanted to shamelessly bump this up. And again offer my help gathering logs / testing / providing a couple of beers :)  (@ePirat) ?

**Comment by basisbit** [comment]
had a few other people build and test almost latest master usdx codebase on Sierra and it worked fine for them.

**Comment by cloderic** [comment]
I have the exact same issue here, are there some news ? Can I help in some way to diagnose the issue ?

**Comment by raulmt** [comment]
Anyone here with the problem could please also test PR #358 to see if it helps you? It seems to fix the issue for me

**Comment by ePirat** [comment]
Now that #358 is merged, this should be fixed. Please reopen if not.
