### ISSUE TITLE
[Feature Request] Import scores from WorldParty

### ISSUE THREAD

**Issue by mrosm76** [UltraStar-Deluxe/USDX#151]
Hello, I love the beta version, thank you! Is there any way to import the scores from WorldParty to the new UltraStarDeluxe game?

**Comment by basisbit** [comment]
The scores are stored in a sqlite .db file in the game folder. You could try opening the old and the new score db file to manually copy the data.

**Comment by mrosm76** [comment]
Thank you for your answer! There is an sqlite3.dll but didn't see a .db file of the same name.

**Comment by basisbit** [comment]
should be the Ultrastar.db. In case you are bored, please feel free to write some update-batch/script/program and do a pull request 😄

**Comment by mrosm76** [comment]
Haha, yes, because I understand what that all means! :) I actually copied/pasted the Ultrastar.db file before writing on here, but that didn't do anything at all...
