### ISSUE TITLE
Raspberry Pi2 error: co-processor offset out of range

### ISSUE THREAD

**Issue by skerit** [UltraStar-Deluxe/USDX#154]
During compiling I'm running into this error:

```
Assembling umenu
../build/fpc-arm-linux/UMenu.s: Assembler messages:
../build/fpc-arm-linux/UMenu.s:5015: Error: co-processor offset out of range
../build/fpc-arm-linux/UMenu.s:5017: Error: co-processor offset out of range
../build/fpc-arm-linux/UMenu.s:5019: Error: co-processor offset out of range
...
../build/fpc-arm-linux/UMenu.s:5851: Error: co-processor offset out of range
../build/fpc-arm-linux/UMenu.s:5859: Error: co-processor offset out of range
UMenu.pas(1894) Error: Error while assembling exitcode 1
UMenu.pas(1894) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcarm returned an error exitcode
Makefile:223: recept voor doel '../game/ultrastardx' is mislukt
make[1]: *** [../game/ultrastardx] Fout 1
make[1]: Map '/home/osmc/src/USDX/src' wordt verlaten
Makefile:136: recept voor doel 'all' is mislukt
make: *** [all] Fout 2
```

Any idea what's going wrong here?

**Comment by basisbit** [comment]
looks like some bug in freepascal compiler. I heard fpc 3.0.0 being unusable on raspbian, but the current freepascal 3 with fixes from git & self-compiled is supposed to work fine.

**Comment by skerit** [comment]
Aha. I tried the raspberry pi install script from the Lazarus website, but then the `configure` command complained that fpc wasn't working.

Is the graemeg freepascal repository ok, or is there some kind of other fork with special fixes around?

**Comment by basisbit** [comment]
just the normal freepascal repository (ok, apparently not on github) should be ok. see http://www.freepascal.org/develop.var

**Comment by skerit** [comment]
That didn't help.

I ended up installing it on my Ubuntu 16.04 laptop, which has freepascal 3 in its repositories. It compiled and played without a problem there.
