### ISSUE TITLE
[Feature Request/Bug] Can't use MP4 (or other video files?) as #MP3

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#163]
It would be very convenient to be able use the video file both for #MP3 and #VIDEO if the audio track of the video is used anyway, thus it does not need to be extracted into a separate file.

In the CMD version, it is possible to use the video file as the audio source (i.e. #MP3). I tested with MP4 and it only produces noise.

**Comment by basisbit** [comment]
please provide a MP4 file which doesn't work for you as MP3 file. This usually works.

**Comment by bohning** [comment]
This one, for example: https://dl.dropboxusercontent.com/u/4021638/Grey%20-%20Vegan%20Thanksgiving.mp4

**Comment by basisbit** [comment]
works for me using current code.

**Comment by bohning** [comment]
Okay, then it must be Mac-specific. I have tested several MP4 files...
