### ISSUE TITLE
[Feature Request] Use OGG files for #MP3

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#164]
This may not be too important (OGG files can always be converted to MP3), but there exists tons of conversions from Rock Band that are originally all in OGG format. The CMD version supports OGG as input for #MP3.

**Comment by basisbit** [comment]
ogg files are supported thanks to ffmpeg already for a long time.

**Comment by bohning** [comment]
Okay, then this can be moved to the Mac-backlog. I just tested again on my Mac - I only get weird noise when using an ogg file.

**Comment by basisbit** [comment]
> weird noise 

using which ffmpeg version?

**Comment by bohning** [comment]
@basisbit 2.8.6 installed via brew

**Comment by AlexanderS** [comment]
Seems like the brew version does not support ogg/theora out of the box: http://stackoverflow.com/a/33457851/902378

(In contrast to the article: It may be sufficient to install theora and reinstall the ffmpeg via brew. At least the current brew formular checks whether theora is installed during the build and enables it with the correct configure switch.)
