### ISSUE TITLE
[Bug] Switching from video to visualization to background image back to video does not work properly on MacOS

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#165]
Pressing 'V' to switch from video to visualization results in a white background (visualization not working). I never use visualization, so this is not important to me, but I wanted to mention it anyway.

Switching further to the background image works, however, switching back to the video did not work in 2 out of three cases. I have the following screenshots:

Video background:
<img width="1680" alt="bildschirmfoto 2016-11-26 um 10 25 26" src="https://cloud.githubusercontent.com/assets/1497707/20639661/fcbd7a7e-b3c9-11e6-9db4-35e9f1b4d759.png">

Visualization background:
<img width="1680" alt="bildschirmfoto 2016-11-26 um 10 25 28" src="https://cloud.githubusercontent.com/assets/1497707/20639662/03caba84-b3ca-11e6-9713-bfc0d7519dbd.png">

Background image:
<img width="1680" alt="bildschirmfoto 2016-11-26 um 10 25 31" src="https://cloud.githubusercontent.com/assets/1497707/20639664/085154a0-b3ca-11e6-8355-794417150532.png">

Back to video background (very strange: screenshot has NOTHING to do with video!)
<img width="1680" alt="bildschirmfoto 2016-11-26 um 10 25 33" src="https://cloud.githubusercontent.com/assets/1497707/20639665/0e451658-b3ca-11e6-89d7-140ae38a2201.png">
So going back to the video, there is only this still image, video playback is not resumed.

**Comment by ePirat** [comment]
Just tried to reproduce but switching between Video, Visualization and Image is working fine for me, tried multiple times. Does it occur with all songs that have video and image or just a specific one?
And which USDX version?

**Comment by bohning** [comment]
With the latest master, I can successfully switch from video to visualization to background image and back to video, so that problem is gone. However, visualization is still broken, I only get a static white background.

@ePirat: do you get colorful background animations when switching to visualization?

Again, I never used visualizations, so it is of minor importance for me. In rare cases I want to switch from video to background and back to video, and that is working properly now.

**Comment by bohning** [comment]
Funnily, I now noticed that for songs without video, the song starts with displaying the background image as it should. Pressing 'V' switches to visualization (still white screen on Mac), again 'V' switches back to the background image.

However, when I now press 'V' again to get to visualization, nothing happens, the background stays displayed.
