### ISSUE TITLE
Translations need to be redone.

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/USDX#17]

**Comment by AlexanderS** [comment]
We could use maybe something like transifex.com.

**Comment by basisbit** [comment]
Good idea! Is there something like transifex available which supports open source or at least is free in a community edition or similar?

**Comment by AlexanderS** [comment]
transifex is free for open source projects:
> Your organization for Open Source projects will be subscribed to the Free plan.

But if you mean for self-hosting then http://zanata.org/ or https://weblate.org/de/ would be an alternative. But I think transifex has the best support for cli tools and the best UI.

**Comment by tobijdc** [comment]
https://crowdin.com was used by an OSS Project i contributed before. It is also free for OSS.
Was not involved in using it, but you could evaluate it too.

**Comment by AlexanderS** [comment]
I created a transifex project and imported the current translations: https://www.transifex.com/usdx/usdx/
