### ISSUE TITLE
[Bug] Duet delimiters "P1" and "P2"  trigger WARNings in the error.log

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#170]
The title pretty much says it all, I get two warnings for each duet, saying something like "... character expected, but found "P1" (same warning for "P2").
I guess with the perfect duet support, this should no longer trigger warnings that could confuse users looking at the error.log.

By the way, which of the two tags would be considered official for UltraStar 1.3, #P1 and #P2 or #DUETSINGERP1 and #DUETSINGERP2? I think Vocaluxe supports both, not sure about CMD.

**Comment by basisbit** [comment]
Performous only supports #DUETSINGERP1/P2, USDX 1.2/World Party only supports P1/P2 if I remember correctly. Vocaluxe and USDX 1.3 or newer support both.
To support all of the various versions, put both versions in the file like this:
`#DUETSINGERP1:Lead vocals
#DUETSINGERP2:Backing
#P1:Lead vocals
#P2:Backing`
