### ISSUE TITLE
[Feature request] Adjust aspect ratio of video in sing screen by pressing A

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#171]
In the CMD version, it is possible to cycle through different aspect ratios for the video (e.g. crop, stretch), if the video dimensions do not fit the screen resolution. This setting was saved for each video.

**Comment by gallivanter** [comment]
I've noticed that older low resolution videos also often tend to be 4:3 aspect which makes the stretch to fit look even worse. An option to scale to fit whilst retaining the aspect ratio of the original video would be awesome.

**Comment by bohning** [comment]
I've gone through my song collection and used handbrake to reencode my videos (to mp4) in order to remove black bars on the edges, especially to avoid black bars in the video preview:
<img width="672" alt="bildschirmfoto 2017-06-18 um 12 58 24" src="https://user-images.githubusercontent.com/1497707/27260187-ea634938-5425-11e7-8d25-e3a9a7fd2401.png">

What is the current behavior of USDX when dealing with video dimensions that do not match the game resolution?

**Comment by basisbit** [comment]
in current USDX, aspect ratio of the video will stay correct. Video will be zoomed until there all borders are reached.

**Comment by bohning** [comment]
I have looked at the code of CMD for this feature, but unfortunately, it seems a little bit more work to implement. Especially with the many ultra wide screen resolution of more recent videos, significant parts of the videos are cropped with the current implementation. Am I the only one who bothers? ;-)

**Comment by bohning** [comment]
I think this can be closed.

**Comment by barbeque-squared** [comment]
Yeah, I think this is sufficiently covered by #689 
It's technically not _exactly_ what OP asked for ("This setting was saved for each video.") but whatever you set it to does carry over between songs anyway.
