### ISSUE TITLE
[Feature Request] With tabs on, show total number of songs in category in song selection

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#172]
While the tab shows the total number of songs (here: German 333)

<img width="1680" alt="bildschirmfoto 2016-11-28 um 17 11 00" src="https://cloud.githubusercontent.com/assets/1497707/20675860/11e1c28c-b58e-11e6-8f46-eccb222e9ae6.png">

the total number of songs is not visible within that selection

<img width="1680" alt="bildschirmfoto 2016-11-28 um 17 11 10" src="https://cloud.githubusercontent.com/assets/1497707/20675866/19013b60-b58e-11e6-8d05-3eda8f5078f5.png">

In my opinion, it would be nice to see the total number of songs, as in the regular song selection screen (i.e. e.g. 1/333).

**Comment by basisbit** [comment]
this was actually implemented, but broke during the integration of the various USDX versions (the USDX 1.2 merge). Quick bugfix was to just hide the "/" if the total total amount of songs number was 0/nil.

**Comment by bohning** [comment]
Ah, I understand. It would be helpful to see "1/333" again =)
