### ISSUE TITLE
[feature request] japanese language support.

### ISSUE THREAD

**Issue by nntb** [UltraStar-Deluxe/USDX#174]
not sure why it doesn't have it. i saw an old post about removing language support added by the 3rd party, so please make it a 1st party addition!

**Comment by RattleSN4K3** [comment]
Hi

A well-known mod has a specific language removed. It got added back. We, the current and past USDX team, don't select specific languages nor exclude them, if there is a need or wish for a given language, and someone can provide a decent translation, it will be added.

For languages with characters other than Latin/Roman script, such as Japanse, it might be harder to support it. But IIRC it should be supported. Right-to-left is another case which should be tested.

**Take a look at our localization ressources, join the project and provide translations over here:**
https://www.transifex.com/usdx/usdx/

**Comment by basisbit** [comment]
If you know Japanese, please help us by providing the translations. Thanks.
