### ISSUE TITLE
Make the "Can't initialize OpenGL" error message more explicit

### ISSUE THREAD

**Issue by MairusuPawa** [UltraStar-Deluxe/USDX#18]
… in the way that more than often, this occurs because the user relies on drivers provided by Microsoft on Windows platforms, instead of properly installing drivers from the GPU manufacturer's own site. Windows Updates distributes gimped drivers with poor OpenGL support.

Since it's not realistic to expect Microsoft to change its ways, maybe the dialog should encourage users to update their gfx drivers from AMD/Intel/Nvidia explicitely somehow (at least on Windows).

**Comment by dracoTrier** [comment]
I planned on releasing the Mesa OpenGL library with usdx so that if the windows-opengl doesn't work, at least on fast dual-core CPUs or better it will still mostly work fine without the user having to do driver-installing stuff.

**Comment by basisbit** [comment]
I planned on releasing the Mesa OpenGL library with usdx so that if the windows-opengl doesn't work, at least on fast dual-core CPUs or better it will still mostly work fine without the user having to do driver-installing stuff. But yes, it should be shown more as a prominent warning message.
