### ISSUE TITLE
[Feature Request] Scale down font for long lines in editor as well

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#185]
While too long lines are scaled in font size in the sing screen, they reach out to the left and right of the screen in the editor. It would be nice if the font size could also be automatically adapted to the line length in the editor.

<img width="1680" alt="bildschirmfoto 2016-12-09 um 22 04 08" src="https://cloud.githubusercontent.com/assets/1497707/21064548/acd1f1b0-be5b-11e6-9a6f-382bfffd908b.png">

**Comment by basisbit** [comment]
this is as intended. Good usdx .txt files don't have too long text lines.

**Comment by bohning** [comment]
I agree with that. But sometimes you have to work with what you get (a bad text file from the net) and improve it using the editor, e.g. to split long lines...
