### ISSUE TITLE
[Webcam-Options] Preview stays active if no camera selected

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#2]
Steps to reproduce:
1. Start USDX
2. Click on 'Options'
3. Click on 'Webcam'
4. Select Webcam (0)
5. Click on 'Enable Preview'
6. Select Webcam (Off)
7. GUI Stays transparent

2 possible fixes:
1. Stop preview if Webcam off (click on 'enable preview' when webcam=off shows error).
2. Disable high GUI transparency if Webcam=off

See attached Screenshots:

GUI Normal
![Webcam-Options-Normal](https://i.imgur.com/b2Pk4dB.png)

Preview Normal
![Webcam-Options-Preview-Normal](https://i.imgur.com/0orCQVB.png)

GUI stays highly transparent
![Webcam-Options-Preview-Bug](https://i.imgur.com/EzsvvdB.png)

**Comment by basisbit** [comment]
fixed as of of now. Was not able to test it yet, but this was clearly a logical error and thus should be fixed with the last commit.
