### ISSUE TITLE
[Bug] Video artefacts on the right edge of the video

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#205]
Sometimes I see artefacts on the right edge of the video, both in the editor
<img width="1680" alt="bildschirmfoto 2016-12-29 um 02 17 17" src="https://cloud.githubusercontent.com/assets/1497707/21541603/0012a9b2-cdb8-11e6-9d04-52e0be6660d3.png">
and in the sing screen (notice the yellowish bar of few pixels width from the bottom to about half the screen height)
<img width="1680" alt="bildschirmfoto 2016-12-29 um 02 17 25" src="https://cloud.githubusercontent.com/assets/1497707/21541609/0e6ca526-cdb8-11e6-8f91-e85f4371971f.png">
First, I thought the video width was maybe not divisible by two or four (not the codec expert though), but obviously, it is a multiple of four
<img width="518" alt="bildschirmfoto 2016-12-29 um 02 17 54" src="https://cloud.githubusercontent.com/assets/1497707/21541638/3de8ca5a-cdb8-11e6-9cde-2fbe252df8f8.png">
When playing the video with e.g. VLC, there are no artefacts:
<img width="748" alt="bildschirmfoto 2016-12-29 um 11 19 08" src="https://cloud.githubusercontent.com/assets/1497707/21541693/ae2ab116-cdb8-11e6-8951-476dec673a93.png">

Any ideas of what could be the reason?

**Comment by ePirat** [comment]
Can you share the sample with us, somehow?

**Comment by bohning** [comment]
@ePirat: this is short sample: https://dl.dropboxusercontent.com/u/4021638/sample_with_artefacts.mp4

**Comment by basisbit** [comment]
place nicely here. no artifacts.
Anyways, handbreak is known to produce not fully standards compliant output, depending on what settings you use when encoding the video. To achieve the low latency playback (and be in sync with audio), many automatic error correction features are disabled in USDX.

**Comment by bohning** [comment]
Thanks for the feedback, @basisbit. I didn't know that handbrake may produce not fully standards compliant output. I pretty much use standard settings (Preset: Legacy --> Normal), and I have only noticed these artefacts in less than a handful of videos.
What could be the reason that it plays nicely for you (USDX 1.3.5b on Windows, I assume?) and not for me (1.3.5b on Mac)? Again differences in ffmpeg between Win and Mac (as with playing ogg files and audio tracks of video files for #MP3)?

**Comment by bohning** [comment]
I seem to have narrowed it down to older videos that use anamorphic resolution. While I kind of understand the idea of anamorphism for videos, I have not quite understood the details when reencoding with handbrake (and how to get rid of anamorphic encoding). It seems to be dependent of the actual screen/game resolution if the video has artefacts or not.
Removing two pixels from one edge (repeatedly if necessary) seem to solve the issue.

**Comment by bohning** [comment]
I have also noticed that this seems to be a resolution-dependent issue. A video with this issue may show these artefacts on my Mac (using a certain game resolution) while there are no artefacts with the same video on a different machine (with different game resolution).

**Comment by s09bQ5** [comment]
Please test with the current master branch.

**Comment by bohning** [comment]
@s09bQ5 Thanks for putting time and efforts into this. My workaround so far was to reencode the videos in question while cutting of 2 pixels on either side (if needed, repetetively), so now I can't test with the current master branch because I don't know which videos would still be affected. Should I come across another video with artefacts, I will report here.
