### ISSUE TITLE
Different color for sung notes and target notes

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/USDX#207]
At the moment the color for the notes that should be sung is the same as the color for the notes that are actually sung (sort of brown). IMO this makes it hard to differentiate between them. And it makes it hard to see if I hit the note perfectly or no note is recorded by the mic (e.g. because I'm not singing loud enough).

I would suggest to use colors with more contrast. Are there two image files for the note bars such that I can change the color in the files for myself locally?

**Comment by basisbit** [comment]
could you please provide a screenshot of what exactly should be changed in the default theme?
Sung notes have different colors then not sung notes in the deluxe and also the modern theme.
![2017-01-03 11_45_05-program](https://cloud.githubusercontent.com/assets/10870269/21605820/cd94f54c-d1ab-11e6-94fd-63eba3026b41.png)

**Comment by achimmihca** [comment]
It was my fault. The brow color is the color of the user ("Flame"). And what makes it hard to see the notes is the modern theme. Changing to Deluxe fixes the issue for me. I'll upload a screenshot for comparison.

![Uploading modern_theme.png…]()
![Uploading deluxe_theme.png…]()

I tried pretty much all options after install and forgot to change the theme back.
Great project by the way!
