### ISSUE TITLE
Sound choppy (crackling)

### ISSUE THREAD

**Issue by lotan** [UltraStar-Deluxe/USDX#211]
I've installed USDX on two laptops (both Arch Linux) using the following PKGBUILD https://aur.archlinux.org/packages/ultrastardx-git/.
On both laptops the sound is choppy.
I do get error messages regarding ALSA and Jack probing, but as far as I'm aware, that is normal for Portaudio.
I tested other applications using Portaudio (e.g. Audacious) on those laptops and they all run flawlessly.

Other tests:
I disabled Pulseaudio and tried running USDX directly on ALSA -> no difference, still sound is choppy.

**Comment by bohning** [comment]
I believe I have the same issue on my Mac. This also refers to the background music in the game, correct?

**Comment by basisbit** [comment]
please test diffrent versions of ultrastar deluxe and see which change introduced this problem for you.

**Comment by lotan** [comment]
@bohning: That is correct. Interesting that it also happens on the Mac. That renders all further tests into sound card configuration almost useless. 

@basisbit: I'd thought about running earlier versions. I looked at the release history and found only one other release since the major rework. I didn't think it made sense to try that one out.
A version before the rework has been running on my desktop for a long time without any sound problems.

**Comment by basisbit** [comment]
I'd guess that either things broke for you when switching from sdl 1.2 to sdl 2 because that also introduced changes in the threading,..., or the issue is caused by an api change in one of the used libraries. Thus, please test with older source code from this repository and maybe also the last trunk version from the [old repository](https://github.com/UltraStar-Deluxe/legacy-sourceforge-svn-mirror).

**Comment by dr-waterstorm** [comment]
I can confirm this issue on Arch and Ubuntu (16.04). I also first thought this is related to the switch from SDL 1.2 to 2.0 (I also tried switching the SDL to ALSA which did work in 1.2 but not in 2).
I tested a lot and "wasted" half of my Saturday trying to fix it (Sinks, PA, ALSA, SampleRates, SDL, etc.). 

Surprisingly when I compiled the last "officially declared beta" from here: https://github.com/UltraStar-Deluxe/USDX/releases (2. Dez) everything works quite well. So this seems to be a rather "new" issue.

I hope this gets sorted out. If I can be of any help, just let me know.

**Comment by bohning** [comment]
Yes, this must be a rather new issue. The Mac version (DMG) I compiled and uploaded on 2016-12-05 works just fine (stilll have that DMG/APP and currently use that, compiling the current master leads to choppy sound in the game. First I thought it was due to the update to macOS Sierra and didn't have time to look into it, so I didn't bother reporting it here.
If anybody can help me with Github Desktop and how to go back to certain commits in time, then I'd be happy to test compile older versions to see where the problem first occurs.

**Comment by lotan** [comment]
@dr-waterstorm: Thanks very much for the pointer. The last release worked for me as well.

I tried to narrow it down a bit (manual git bisect :)):
d2b3b2e0a78b0e8d93d183bf09d71e58ea58dfcc is the last one that works, the next few don't compile
7171b42d085069584809edbfa819c0b5252221dc is the first one that compiles again and has the sound coppiness issue

in particular
8f124684198e2a99e69cfc1075890902ddc67521 "audiobuffer requires size of int, not of byte." sounds like a potential candidate to influence sound, however, looking into it, the changes seem reasonable, except it fails here with:
```
/tmp/yaourt-tmp-xxx/aur-ultrastardx-git/src/USDX/src/media/UAudioPlayback_SoftMixer.pas(183,16) Error: There is no method in an ancestor class to be overridden: "ReadData(PByteArray;LongInt):LongInt;"
/tmp/yaourt-tmp-xxx/aur-ultrastardx-git/src/USDX/src/media/UAudioPlayback_SoftMixer.pas(194,1) Fatal: There were 1 errors compiling module, stopping
```
Maybe its fix is a problematic candidate?

**Comment by ePirat** [comment]
Commit 41d282e should have fixed this, so it probably can be closed.

**Comment by nathancatlow** [comment]
I can confirm this has fixed the problem on arch linux git package (https://aur.archlinux.org/packages/ultrastardx-git/), thank you!

**Comment by katosh** [comment]
It also fixed the issue for macOS 10.12.2.

**Comment by lotan** [comment]
It's fixed for me, too.

**Comment by basisbit** [comment]
this issue log shows why free/libre open source software development is so amazing!

**Comment by about-design** [comment]
I know it is closed, but i have a problem with a firewire Interface on macOS 10.12.2 and 10.11. With an usb-interface there is no problem.

**Comment by basisbit** [comment]
please create a new issue for that.

**Comment by eGit** [comment]
I cannot find an open issue for Linux and audio stuttering. Should I open one? I am running on a slowish Laptop, but Fullscreen Videos in 1080p in MPV work without a problem. Audio and Video is SMOOTH.

But in Ultrastar the background playback is just horribly choppy. Constant stuttering.

I am running the latest appimage: v2025.12.1

It's not like I tested an older version which worked. I assume it is the same with older versions. I will test it and post here if it is working with older versions.

UPDATE: it is not.

**Comment by eGit** [comment]
Tested now with older appimages. Also 2024.

I also deleted ALL downloaded songs in the Syncer App and redownloaded them with the lowest settings. H264, 360p, 128kb MP3.

CPU usage is basically Zero. STILL the annoying stuttering. It is a bug.

**Comment by s09bQ5** [comment]
Please make a new issue and provide ~/.ultrastardx/logs/Error.log.

**Comment by eGit** [comment]
> Please make a new issue and provide ~/.ultrastardx/logs/Error.log.

https://github.com/UltraStar-Deluxe/USDX/issues/1148
