### ISSUE TITLE
Record settings menu empty

### ISSUE THREAD

**Issue by ePirat** [UltraStar-Deluxe/USDX#214]
Using the Windows Version: 1.1 and same with Version: 1.3 Beta 2 the Record menu is empty. There are no options shown, only the back button.

**Comment by basisbit** [comment]
in that case, no microphone input is detected. Make sure you correctly connected some microphones and check in the windows audio settings that they are correctly set up.

**Comment by ePirat** [comment]
Thanks for the answer.
They were correctly detected by Windows, still the menu was empty. It suddenly started to work for no clear reason after restarting UltraStar a few times, without any changes to the connected hardware and such.

**Comment by basisbit** [comment]
for low latency audio recording, usdx has to get pseudo-exclusive access to the microphones. Sometimes, depending on what other software is installed and running on your computer, getting that exclusive access fails even when there are microphones connected. In such a case, try to close other applications which block that exclusive access and check your windows audio recording devices settings.
