### ISSUE TITLE
USB Mics record themselves on macOS 10.11 and 10.12

### ISSUE THREAD

**Issue by about-design** [UltraStar-Deluxe/USDX#221]
I bought 2 USB-Mics last week to play with 4 people, but on my macs i can't use them.
They have a full signal und record themselves. I tried to mute them, changed the sample rate but nothing works. Then i tried it with Logic and Garageband, they are working perfectly, no signal or self recording.
I don't have this issue on a win 10 laptop. 
On image 1 you see whats happening when nobody sings, blue ist the usb mic and red my usb interface.
![bildschirmfoto 2017-02-04 um 15 21 33](https://cloud.githubusercontent.com/assets/9933767/22619124/afe6db5e-eaed-11e6-91dd-fc9592df267e.png)
On image 2 you see the record settings.
![bildschirmfoto 2017-02-04 um 15 18 04](https://cloud.githubusercontent.com/assets/9933767/22619125/b01d75a6-eaed-11e6-8ea0-1bf2037b3401.png)

**Comment by ePirat** [comment]
Should be fixed by #358, please reopen if not.
