### ISSUE TITLE
Mac version not opening after second execution

### ISSUE THREAD

**Issue by darkgaze** [UltraStar-Deluxe/USDX#223]
USDX version is 1.1 for MacOs. Last version I found two days ago on 8th of February.

I tried several times:
New clean installation -> first time works, second fails (after creation of config folder? doesn't seem like that because If I delete it, it still fails)
New installation leaving the config folder -> Doesn't work

(I'm deleting the home/library/App support/ folder with the config.ini file.)

Everytime it runs the second time, it fails. No error log output.
I'm sending here the "force exit" log mac gives me with all my system info on top and bottom of the text.

https://drive.google.com/file/d/0B0tTPAMyuBPHM29lOUU2TVI5X1Nka01jeWEtNVpPR0wtMlIw/view?usp=sharing

**Comment by darkgaze** [comment]
I tried generating the config folder in the first execution and saving a backup. 
Then deleting everything, and installing again, and before executing the first time, I restore that backup again.  In the first execution changed config works and USDX works. Second time ...doesn't.


By the way, we found that the process is executing using 99% of the CPU, and seems like it is waiting for a thread to finish (waiting on cwait method of the thread library). So there's a thread that never finished even after finishing execution (signal sent from mac to tell the app to start) and the app is waiting for something to finish...

**Comment by basisbit** [comment]
USDX 1.1 is horribly old and known to not work any more on current OS X versions because of changed functions.
Please try current USDX trunk here from this github repository.
Also, please take a look at #167

**Comment by darkgaze** [comment]
Thanks. I wish I could compile it myself, but I can't. I'm not a mac developer, I'm a windows developer with very little time. I had a party right now, in fact, and I've been all day trying to fix this the easy way. Until I found this weird way to make it work... but after a while searching on the song list it gets closed. 

Is there any compiled versions anywhere?

**Comment by bohning** [comment]
@darkgaze: try this one - https://transfer.sh/BDhm6/ultrastardeluxe.dmg

**Comment by darkgaze** [comment]
@bohning Erm... the file is gone!  I can do it myself now, but if you have that file it would be awesome to try it. Thanks!

**Comment by ePirat** [comment]
You can find a very recent build here: https://transfer.sh/II14X/ultrastardeluxe.dmg

Do not link to that file elsewhere, it will be gone at some point.

**Comment by basisbit** [comment]
please someone test this on a os x device where usdx wasn't installed before. once it is reported as good, I'll put it on my cdn

**Comment by ePirat** [comment]
I can confirm that this is fixed, tested on multiple machines, so it can be closed.

**Comment by liamarmitage** [comment]
Hi it appears this issue is still ongoing. I too was able to run once however app hang after that. Error log available - https://drive.google.com/file/d/0B3u-U5TEnwgRZzJWY1gxSEljWFE/view?usp=sharing

I tried 1.3 Beta which loaded however with it being Beta the graphics were off etc

**Comment by ePirat** [comment]
If it does not happen with the beta, it is fixed.

**Comment by UltrastarError** [comment]
I have the same issue with USDX 1.1 and macOS 10.13.2 (High Sierra). 1.3 Beta works, but with a graphic issue instead. Is there any solution for this?
