### ISSUE TITLE
Sometimes keypresses count twice during search

### ISSUE THREAD

**Issue by GrueneNeun** [UltraStar-Deluxe/USDX#225]
I have a song database of a little more than 5600 songs and during the usage of the search feature it is a bit laggy while filtering the list and showing only the songs matching the search phrase.
But in 1.3.5 while the lagging occurs it happens that if one types fast enough the keypresses during the lag count twice and also are shown twice in the search field.
I could not reproduce this behaviour with the same song database in 1.3.2 or in 1.1.0 so it seems to be a new bug since this version.

**Comment by basisbit** [comment]
already fixed in current master. thanks for the bugreport anyways!
