### ISSUE TITLE
[Feature Request] Adding an option for some kind of GAP-fix in ms.

### ISSUE THREAD

**Issue by Jamilian** [UltraStar-Deluxe/USDX#226]
Hi all,

in the last days i have played some rounds of UltraStar DX with many different songs. After some days we get more and more the idea, that for nearly all songs (regardless of the source) the GAP is not completely correct, but more or less like 200ms too small (or so).

So today i started an investigation about this, and it looks like that the song is tagged and "gapped" correctly in the editor, but while singing there is this timegap.

Since I am an technician myself i had an idea where this could come from, the whole hardware configuration:

For example in our configuration USDX is running on my desktop which is connected to my TV by HDMI (video and audio). Additionally our microphones are attached by USB.
I think both HDMI and USB result in some kind of latency, so that the "real" GAP does not fit completely.

But to fix this (for this and any other configuration) there could be some option for fixing the GAP. So just an option where you could give some value for some kind of global GAPfix (because of latency) in ms, which would be added when the song is loaded to be sung.

Can you imagine what i mean?

Technically this should be quite easy, first adding a new option and second include a line while parsing the song-sheet for singing to add the fixGAP value to the songs GAP.

Feel free to comment on this suggesstion, i'll have an eye on this thread :)

TY!
Jamilian

PS: 
in general: really good job which you are doing here!

**Comment by despian** [comment]
I am also experiencing latency issues with my mics and would find this option very useful.

**Comment by s09bQ5** [comment]
I really thought we already had something like this.
Please don't call it "GAP-fix". That sounds like the GAP is incorrect.

What we need is a setting for changing the audio output synchronization relative to the video output and a per-microphone setting for the input delay. The former has to be added to the PTSes of the audio track. It can be positive or negative depending on where (audio or video) the biggest delay is.

The latter should affect the MidBeatD value (and all values derived from it) for grading the recorded voice. Looking at the formula for MidBeatD, there already appears to be some constant offset. The difficulty is to allow this to be tuned for each microphone. ...Maybe we should start with a global value. It is rare that people use more than one microphone and record from them in ways that have significantly different delays.
