### ISSUE TITLE
Static noise for some audio files on macOS

### ISSUE THREAD

**Issue by ePirat** [UltraStar-Deluxe/USDX#228]
Some audio files do not play properly on macOS, instead you only hear static noise. This does not happen for mp3, but for example for FLAC files.

**Comment by bohning** [comment]
I can confirm this also for OGG files and also if you try to use the video file as #MP3 source, which does work for the Windows version.

**Comment by basisbit** [comment]
so, this is ffmpeg related. Can anyone of you check if this also happens with ffmpeg 2.7 or older?

**Comment by s09bQ5** [comment]
Should be fixed since #239 has been merged.

**Comment by ePirat** [comment]
Yep, can confirm that this is fixed now.
