### ISSUE TITLE
[Feature Request] Keyboard shortcut to show/hide oscilloscope (microphone feedback) at player name/score

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#230]
Currently, the microphone feedback can be displayed at the player name/score by enabling 'Oscilloscope' in the settings. This is great to verify that indeed all microphones are working. Once it has been verified that the microphones are working, it would be great if this feature could be enabled/disabled (in the sing screen) by a keyboard shortcut, e.g. STRG+O instead of having to disable it in the settings (of course, this should change the Oscilloscope settings and not only change the display for the current song).

**Comment by basisbit** [comment]
I personally vote against this because it would result in one more key shortcut which most people won't know and might accidentally press. But if anyone wants this feature, feel free to code it and do a pull request.

**Comment by bohning** [comment]
I see your point in too many (unknown) keyboard shortcuts. However, accidentally pressing the combination of STRG+O is rather unlikely, I would say ;-)
In any case, an in-game help system (e.g. toggled via TAB as in CMD) would indeed be helpful for all available keyboard shortcuts, especially for the editor.
