### ISSUE TITLE
Ultra Star won't find my microphone V 1.3.5

### ISSUE THREAD

**Issue by ghost** [UltraStar-Deluxe/USDX#236]
Good day,

The game is having problems finding my microphone. I am currently using a Samson usb Mic on my computer, yet it says it can't find any.

- USDX version: 1.3.5
- Operating System + version: Windows 7 Pro

**Comment by basisbit** [comment]
please check your audio configuration in windows audio recording settings. Also, make sure any other application which might take microphone access is closed. For low latency, UltraStar Deluxe requires a special access to the microphone which is sometimes blocked when other recording software is running.

**Comment by barbeque-squared** [comment]
I'm going to close this issue because it's been 6 years without a reply and the reporter has deleted their account in the meantime.
