### ISSUE TITLE
Invisible lyrics visible.

### ISSUE THREAD

**Issue by carcinojen** [UltraStar-Deluxe/USDX#25]
I have both plugins that are supposed to make lyrics invisible, but the lyrics still show up. Thoughts?

**Comment by basisbit** [comment]
the plugins are for the party mode only. which plugins do not work on which songs for you?

**Comment by carcinojen** [comment]
I am in party mode. I am using blindLyrics.usdx and blindLyricsAndNotes.usdx.
The blind notes work just fine... the lyrics show up on every song I try.

**Comment by basisbit** [comment]
I just double checked and the plugins (from https://github.com/UltraStar-Deluxe/USDX/tree/master/game/plugins ) work just fine here. What version of UltraStar Deluxe are you using? Also please provide the Error.log from the installation folder.

**Comment by carcinojen** [comment]
Thanks for responding so quickly.
I'm using Ultrastar Deluxe World Party v 12.07 and Ultrastar Deluxe v 1.1.0.

> UltraStar Deluxe WorldParty 12.07 Error Log
Date: 4/7/2016 Time: 7:48:18 PM
-------------------
ERROR:  Can't find video file in song: C:\Program Files (x86)\UltraStar Deluxe\songs\Pixies - Mr. Grieves\Pixies - Mr. > Grieves.txt

and
> UltraStar Deluxe V 1.1.0 Build Error Log
Date: 4/7/2016 Time: 7:50:34 PM
-------------------
ERROR:  Can't find video file in song: C:\Program Files (x86)\UltraStar Deluxe\songs\Pixies - Mr. Grieves\Pixies - Mr.> Grieves.txt

Are the only things the error logs show.

**Comment by basisbit** [comment]
we are not the developers of the USDX world party edition. can't help you with that, sorry.
