### ISSUE TITLE
Cannot build on Fedora 25: failed to link libpcre

### ISSUE THREAD

**Issue by mhuin** [UltraStar-Deluxe/USDX#262]
Hello,

### Actual behaviour

./configure fails on Fedora when trying to link the libpcre library.

### Steps to reproduce

installing dependencies:
sudo yum install git fpc SDL2-devel SDL2_image-devel SDL2_image SDL2 SDL2_mixer SDL2_mixer-devel SDL2_net SDL2_net-devel SDL2_ttf SDL2_ttf-devel SDL2_gfx SDL2_gfx-devel ffmpeg-devel ffmpeg libavdevice libsqlite3x libsqlite3x-devel sqlite-devel pcre pcre-devel dejavu-fonts-common gnu-free-serif-fonts portaudio-devel lua-devel libpng-devel opencv-devel libprojectM-devel freetype freetype-devel pcre2 pcre2-devel

./configure ouput:
[...]
checking for libpcre... yes
checking version of libpcre... [8.40]
configure: error: failed to link

### Details

- USDX version: master as of March 17, 2017
- Operating System: Fedora 25

**Comment by s09bQ5** [comment]
Can you quote the relevant snippet from config.log?

**Comment by mhuin** [comment]
Sorry for the delay, here is the full config.log: https://pastebin.com/iMGeebGL

The error seems to appear on line 506.

**Comment by s09bQ5** [comment]
Please try again with the current master branch. 5b8e8bc should fix your problem, but if you decide you want projectM, you need to install g++.

**Comment by s09bQ5** [comment]
Assuming everybody is happy now

**Comment by mhuin** [comment]
yes, sorry it slipped from my mind! I successfully built and ran USDX on Fedora 25 after this change. Thanks a lot!
