### ISSUE TITLE
Cannot start USDX v1.3.5

### ISSUE THREAD

**Issue by fgtm** [UltraStar-Deluxe/USDX#267]
Hi
please help, The USDX could not start and shown this message:
***********************************************************
Error
An unhandled exception occurred at $0040FBF9:
EOutOfMemory: Out of memory
$0040FBF9
$0040FF27
$$0054BF7F
************************************************************
I tried to install to another PC and same problem happened

Thank you

- USDX version: 1.3.5
- Operating System: windows 10 pro, windows 8 pro

**Comment by dhhartree** [comment]
I am having exactly the same issue.

USDX version 1.3.5
OS windows 10

**Comment by basisbit** [comment]
finally found someone with exactly this issue and was able to reproduce it with the the last released 1.3.x beta. This was fixed already in the mean time by changing the freepascal project setting from gui-application to console application. Tried to get some help/support by freepascal developers but gave up on that after a couple of weeks. I guess Windows users will have to live with the console window showing up for a few seconds when starting the game.

**Comment by JOHAAANNS** [comment]
Hi, sorry for my poor english, the solution is to launch application with right click on executable, and "solve the compatibility problem". And work ;)

**Comment by basisbit** [comment]
@JOHAAANNS the solution is so simply use some current version of UltraStar Deluxe, not something 3 years old or so.
