### ISSUE TITLE
[OSX] Editor crashes on load

### ISSUE THREAD

**Issue by rhaamo** [UltraStar-Deluxe/USDX#27]
It seems that the line:
`SoundLib.Click.Volume := SelectsS[VolumeClickSlideId].SelectedOption / 100;` on file `src/screens/UScreenEditSub.pas` around line 3530 makes the editor crashes on load.
Commenting it allows it to runs, I haven't  investigated further

**Comment by basisbit** [comment]
This happens because of some library having changed its api. Does not happen with the fink build from michi.

**Comment by RattleSN4K3** [comment]
Likely fixed with c83c379. Does this crash still happen?

The missing files were causing the Click object/stream not being created and thus accessing a member of that object will result into a crash.

**Comment by bohning** [comment]
I cannot confirm this bug. Editor loads without crashing for me on El Capitan and Sierra.

**Comment by basisbit** [comment]
it works. Just doen't have midi playback support - not sure how much work it would be to get midi playback to work. These code parts are inside compiler time target checks.
