### ISSUE TITLE
Problems compiling and running on Windows 10 64-bit

### ISSUE THREAD

**Issue by ricardosdl** [UltraStar-Deluxe/USDX#273]
Just installed Lazarus 1.6.4, fpc 3.0.2 win64. Cloned the repo and tried to compile, but no success. After some digging I finally got it to compile. But when tried to run the game I got the error 0xc000007b. After some searching I found out that it could be a 64-bit application trying to run with 32-bit libraries. I downloaded and installed the add-on [lazarus-1.6.4-fpc-3.0.2-cross-i386-win32-win64.exe](http://wiki.lazarus.freepascal.org/Cross_compiling#From_win64_to_win32) (which allow to cross compile windows 32-bit applications on Windows 64-bit), changed the Target OS to Win32 and I finally got the game to compile and run without any errors.

Maybe you should mention it on the documentation to help future users. Thank you! Great job with the game!

**Comment by basisbit** [comment]
the included libraries are 32-bit only, thus a win64 build will not be able to launch correctly. Please feel free to modify the documentation and add this as a note, then do a pull request on this git repository so we can merge the changes. Thanks!
