### ISSUE TITLE
Double Characters when entering playername

### ISSUE THREAD

**Issue by paul70078** [UltraStar-Deluxe/USDX#275]
I'm using Ultrastar DX 1.3.5 beta on Windows 10

When I try to enter/change a player name and enter the letters the letter gets Input double first as the capitalised one and after that as the pressed one (capitalised depending on pressing SHIFT)

See Screenshot: (I tried to enter "Paul")
![screenshot0002](https://cloud.githubusercontent.com/assets/2229858/26278981/2c9de432-3da8-11e7-9411-37d29b1da25e.jpg)

Delting chars works normal -> I have do press Backspace twice for every pressed letter

I will provide additional informations or clarifications if needed.
Thank you for the awesome game tough altough

**Comment by MariusHofmann** [comment]
Having the same issue, also occurs when using the search function.

UDX 1.3.5
Lenovo Y520 Notebook
Win 10 1703

**Comment by basisbit** [comment]
duplicte, already fixed.
