### ISSUE TITLE
Crashes on Windows during normal use

### ISSUE THREAD

**Issue by s09bQ5** [UltraStar-Deluxe/USDX#276]
It has been noted on IRC that the current development version is quite unstable on Windows. Lacking a computer with Windows, I need more information to analyze the problem (ideally some kind of backtrace across all threads with symbol names, line numbers, function parameters, current register values and disassembly of the current function, but I take everything I can get). Also mention the commit ID you used to build the binary and if you are able to reproduce the problem easily, please take the time and try to git bisect the error.

SInce there is already #267 for errors on startup, let's restrict this issue to cases where you can at least sometimes successfully start a song.

**Comment by basisbit** [comment]
part of the problem seem to be this:

> INFO:   Using decoder BASS_Decoder for "C:\Users\boop\UltraStar Songs\test\Michael Jackson - Beat it\Michael Jackson - Beat It.mp3" [TAudioPlaybackBase.OpenDecodeStream]
> WARN:   Reading decoded audio data from the BASS library failed. Faulty audio file?
> Stacktrace:
> Exception class: ERangeError
> Message: Range check error
>   $004C2AE7  TBASSDECODESTREAM__READDATA,  line 204 of media/UAudioDecoder_Bass.pas (referring to "Result := BASS_ChannelGetData(Handle, Buffer, BufSize);")
>   $004C3313  TBASSPLAYBACKSTREAM__READDATA,  line 232 of media/UAudioPlayback_Bass.pas
>   $004C317A  PLAYBACKSTREAMHANDLER,  line 179 of media/UAudioPlayback_Bass.pas
>   $6EC0D99E
>   $6EC0DC6B
>   $6EC0F8FA
>   $6EC0FA07
>   $004C3801  TBASSPLAYBACKSTREAM__PLAY,  line 354 of media/UAudioPlayback_Bass.pas
>   $004C3841  TBASSPLAYBACKSTREAM__FADEIN,  line 360 of media/UAudioPlayback_Bass.pas
>   $004BC786  TAUDIOPLAYBACKBASE__FADEIN,  line 327 of media/UAudioPlaybackBase.pas
>   $004DCCC4  TSCREENSONG__STARTMUSICPREVIEW,  line 3741 of screens/UScreenSong.pas
>   $004D3870  TSCREENSONG__ONSONGSELECT,  line 2072 of screens/UScreenSong.pas
>   $004DA86F  TSCREENSONG__DRAW,  line 3247 of screens/UScreenSong.pas
>   $00436DC8  TDISPLAY__DRAW,  line 295 of menu/UDisplay.pas
>   $0044F781  MAINLOOP,  line 325 of base/UMain.pas
>   $0044F5AD  MAIN,  line 264 of base/UMain.pas
>   $00402B67  main,  line 397 of ultrastardx.dpr [UAudioDecoder_Bass.ReadData]

**Comment by basisbit** [comment]
seems like range check issues for this place also happen at the end of songs with certain audio + video in one file. Adding try... except around this line is the work-around for me currently. Will search for other related thrown errors.

**Comment by basisbit** [comment]
hacky "fixed" more of these cases by adding some error handling so at least people can continue playing the game.
