### ISSUE TITLE
Can't build on Xubuntu 17.04 / ffmpeg > 3.2

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [UltraStar-Deluxe/USDX#277]
### Actual behaviour

`./configure` won't finish it's job. The actual output is:

`Unsupported ffmpeg version, most recent version supported is 3.2.`

### Expected behaviour

`./configure` should work on Xubuntu 17.04 with the current ffmpeg.  Indeed, even DOWNGRADING ffmpeg doesn't fix the same issue.

### Steps to reproduce

Try to build USDX on Xuubuntu 17.04

**Comment by QbeRoot** [comment]
Same issue on Debian 9.0 Stretch with ffmpeg 3.2.5-1, although I couldn’t downgrade it because I have a lot of packages depending on it.

**Comment by cRaZy-bisCuiT** [comment]
Any news regarding this problem? Is there any active usdx developement being done atm?

**Comment by basisbit** [comment]
there is no development done to improve support for linux / more recent ffmpeg versions.
Anyone with ffmpeg knowledge, please feel free to add support for whatever version is current. If you know libvlc, please help me at the task of adding support in usdx for playback using libvlc.

**Comment by cRaZy-bisCuiT** [comment]
I'm not even sure if newer ffmpeg versions will cause trouble. How could I force ./configure to skip the ffmpeg-check and build it with a newer version anyway?

**Comment by basisbit** [comment]
headers of newer versions need to be translated accordingly.
