### ISSUE TITLE
[OSX] Microphone input sometimes not detected

### ISSUE THREAD

**Issue by rhaamo** [UltraStar-Deluxe/USDX#28]
```ERROR:  Device "Built-in Microph" does not work [TAudioInput_Portaudio.EnumDevices]```

I've got this problem sometimes and I found a workaround.
There is probably a better way to do that.

In file ```src/media/UAudioCore_Portaudio.pas``` line 318, if I put ```1 to 20``` to ```1 to 30``` I don't have the detection problem anymore.

I'm not sure what the problem is exactly but a longer detection/wait seems to do the job.

**Comment by basisbit** [comment]
implemented the suggested bugfix with up to 400ms scanning time on os x

**Comment by Firestarter2809** [comment]
Hi, I am new here and NOT a programmer. Could anybody please help me how I access that file and if  not mac similar file to change the detection? 
 
src/media/UAudioCore_Portaudio.pas

**Comment by Firestarter2809** [comment]
Hi, I am new here and NOT a programmer. Could anybody please help me how I access that file to change the detection? We use Ultrastar every Year for my wife's B'day, but I have been struggling this year to get it started. Only 7 days left to fix it. I have the same problems on several mac's, Mac OS X's and config.ini's. My neighbor has same problem, PLEASE HELP :-)

src/media/UAudioCore_Portaudio.pas

**Comment by basisbit** [comment]
@Firestarter2809 this issue was already closed and is fixed in current code. For instructions on how to compile and run the game on OS X, see https://github.com/UltraStar-Deluxe/USDX#compiling-on-os-x

**Comment by basisbit** [comment]
there currently is no ready to use package of the game available, because none of the active developers know how to adapt the make script for these packages.

**Comment by Firestarter2809** [comment]
Thank you for the very quick feedback. So that means there is no current version with these changes to download?
Might have to install it on a PC :-)

**Comment by bohning** [comment]
I could upload an app or dmg file, if you want.

**Comment by Firestarter2809** [comment]
Hi Markus,

a DMG would be awesome. Dropbox?

**Comment by bohning** [comment]
Try this: https://dl.dropboxusercontent.com/u/4021638/UltraStarDeluxe.dmg

**Comment by basisbit** [comment]
@bohning what git commit is that dmg based off? I might want to copy it and put the file on the ultrastardx website for download, if others report that is works for them.

**Comment by bohning** [comment]
Checked out a few minutes ago (am on my mobile now and can't look it up).

**Comment by basisbit** [comment]
perfect

**Comment by bohning** [comment]
@basisbit: https://github.com/UltraStar-Deluxe/USDX/commit/64293f7abbe823607100c2f47d35bd21b12b4f35

(now I am back home and was able to look it up)

**Comment by Firestarter2809** [comment]
Hi Markus,

you are great - THANKS A LOT!!! 
I have it working with following great improvements vs. the old version:

(Singstar) Microphones working now and visible under „record“
Programm can be (re)-started without any workarounds
switch between programs and desktop with „standard“ CMD+TAB

For further development in the future one more critical thing I noticed while singing:

displayed notes seem to be buggy and no result shown

Following minor bugs:
black menu text can not be clicked => which shortcut works for them to be used? E. g. to find a song? 
at selection video preview is not always displayed


![pastedgraphic-1](https://cloud.githubusercontent.com/assets/23745805/20647124/29638290-b48c-11e6-89f0-b28f9344ad77.png)
