### ISSUE TITLE
[MacOS] [MacOS SIerra] Garbled Mic Audio

### ISSUE THREAD

**Issue by dorphalsig** [UltraStar-Deluxe/USDX#281]
Hi!

When using a USB Microphone in MacOS Sierra, I get only garbled sound from the microphones (See attached).

I've tried using the 1.3 Version that's available for download on the website, as well as the latest github source code compiled by yours truly (btw, tried to do the Lazarus way and it kept saying there was no make rule, so I reverted to 'good old make'). 

My configuration: 

![image](https://user-images.githubusercontent.com/5605517/27383792-c8e4d100-568c-11e7-83df-ed8e70b88d0c.png)

![image](https://user-images.githubusercontent.com/5605517/27383815-deda8374-568c-11e7-9d20-fcf07f92a099.png)

![image](https://user-images.githubusercontent.com/5605517/27383821-e5d49b10-568c-11e7-9481-a4d7b0280092.png)

![image](https://user-images.githubusercontent.com/5605517/27383827-eb9e3d3a-568c-11e7-97cb-a5a001336802.png)

The problem:
Mic sound is garbled, the mic works fine outside USDX and also works in USDX win

https://youtu.be/Xs93truWsyQ

**Comment by s09bQ5** [comment]
This sounds a lot like your other issue #150.
Feel free to raise attention there if it still does not work.
