### ISSUE TITLE
Feature suggestion - Reverb effect on microphone(s)

### ISSUE THREAD

**Issue by maxlefou** [UltraStar-Deluxe/USDX#288]
Recently I played Rock Band with some friends and I noticed the singing part adds a reverb effect on the microphone output, and it renders pretty good during gameplay. So I was thinking it would sound neat in USDX as well. Of course the effect can be enabled or disabled in hte options.

Tho, I have no idea if it's possible or how hard it is to implement it :/

**Comment by basisbit** [comment]
no idea what this reverb effect might be. I don't own rockband.
I doubt anyone would like to spend time implementing new features in a game written in objective pascal. 
Anyways, I'll close this issue for now. Please provide a video of that effect, so other developers might be able to take a look into it. Also, we might be able to implement it in the usdx rewrite that I started working on a bit.

**Comment by basisbit** [comment]
Also, on a side note, why that weird mane color?

**Comment by maxlefou** [comment]
1. it's not a mane, it's a hat.

2. geez. reverb is that thing that "reverbs" the sounds like in a cave. here's a sample of how it can sound https://youtu.be/k5MqjS1rZrk?t=2m36s
