### ISSUE TITLE
MacOS 

### ISSUE THREAD

**Issue by neurolabusc** [UltraStar-Deluxe/USDX#293]
USDX does [not work on MacOS](https://github.com/SaschaWillems/dglOpenGL/issues/4). The core problem is that USDX uses many legacy OpenGL commands glMatrixMode, GL_QUADS, glBegin, but on MacOS it launches with the Core specification that removes these deprecated functions. This is not an issue for Linux or Windows, which provide compatibility modes that allow you to mix and match legacy and modern features. The [solution](http://lists.freepascal.org/fpc-pascal/2017-May/051384.html) is to specify a legacy context: 

```
{$IFDEF Darwin}
SDL_Init(SDL_INIT_VIDEO);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
{$ENDIF}
```

**Comment by basisbit** [comment]
This would break support of hardware which does not support OpenGL 2.1 and thus is not an option.

**Comment by basisbit** [comment]
@bohning can you check if USDX works as expected on current macOS?

**Comment by bohning** [comment]
Latest release runs on my Mac without issues. Can check with a non-development Mac tonight or tomorrow.

**Comment by neurolabusc** [comment]
@basisbit [SDL](https://wiki.libsdl.org/Installation) requires MacOS 10.5 or later, MacOS 10.5 supports [OpenGL 2.1](https://en.wikipedia.org/wiki/Mac_OS_X_Leopard). More recent releases either support up 2.1 for legacy and later Core versions that drop deprecated features. While different OSes and hardware support different [features](https://developer.apple.com/opengl/OpenGL-Capabilities-Tables.pdf), for your project requesting 2.1 ensures that you do not get a core context. Different machines and OSes may work differently, but since you are not using any modern features, requesting legacy mode ensures that your project works well. If you want to try out a Pascal project that can be compiled for either Core or Legacy, download [Surf Ice](https://github.com/neurolabusc/surf-ice/releases) - note that when you choose "About" with SurficeOld the OpenGL context is 2.1, whereas the regular version requires Core specification and will report a higher OpenGL version. For that project, the Core version leverages new features (e.g. geometry engine). However, for your project you do not use modern features, so clamping to an older context ensures compatibility. By the way, you could always request a version earlier than 2.1 - though in my experience MacOS provides 2.1 if you request 2.1 or earlier and the latest supported CORE context if you request a value greater than 2.1. Take a look at the Lazarus glcocoanscontext.pas - what your project needs to ensure broad support is a NSOpenGLProfileLegacy. So you lose nothing by requesting legacy support and ensure it works on modern Macs.

**Comment by neurolabusc** [comment]
@basisbit, I find the negative emojis from you very unprofessional. I am earnestly trying to help with this project. I have done research on this topic, I am familiar with this topic. I strongly believe the issues you reported are due to the fact that your installation has elected to give you a core context. I have provided constructive, helpful advice that allows you to troubleshoot a problem you found. My advice is professional and constructive. Open source relies on us working together. I apologize if you inferred any negative tone in my messages. I am providing sound advice to improve this project. Open source software relies on us working cooperatively. If you treat people who try to help you poorly, they are unlikely to help you resolve your issues.

**Comment by neurolabusc** [comment]
@basisbit, I can not replicate your issue on my hardware. I suspect this is due to your combination of OS and hardware selecting the core profile. My best guess is you can fix this by providing a hint to engage the compatibility profile. If you could test this out, it would help other users who have a similar setup to you. As noted, this should have no negative consequences: all supported versions of MacOS have at least OpenGL 2.1 and the SDL uses calls that are not supported by the later CORE specification.

```
{$IFDEF Darwin}
SDL_Init(SDL_INIT_VIDEO);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY );
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
{$ENDIF}
```

**Comment by basisbit** [comment]
how come you even think this problem affected me? The other issue report which you are hugging was closed by me (after I found the actual problem months ago and fixed it), so there is no need for you to spam here. (and create a duplicate issue report)
Please check stuff before you open issues in other projects where you never contributed before. Also, the downvote was because you simply ignored our issue submission form.
