### ISSUE TITLE
[Bug] 2017.08.0-Stable crashes on (non development) Mac

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#294]
The Mac version of the latest 2017.08 release seems to be missing libx264, referenced from libavcodec:

![bildschirmfoto 2017-08-08 um 22 40 14](https://user-images.githubusercontent.com/1497707/29093889-b4066044-7c8b-11e7-9084-bc3cbb7f480c.png)

**Comment by basisbit** [comment]
this is also what I heard half a year ago from some other people. they said that some library that xcode installs with it is missing. No idea about any details

**Comment by bohning** [comment]
Strange this is... the file is there:
<img width="1228" alt="bildschirmfoto 2017-08-10 um 23 31 46" src="https://user-images.githubusercontent.com/1497707/29193090-2dec1644-7e24-11e7-96bd-6f2afec1ad0b.png">

@ePirat, @AlexanderS, @kamischi any ideas what could be the cause?

**Comment by s09bQ5** [comment]
Is this really the v2017.8.0 release?
The release DMG contains libavcodec.57.dylib, not libavcodec.56.dylib.

**Comment by bohning** [comment]
@s09bQ5 Okay, my bad. The two screenshots were refer to two different builds (first refers to DMG from Travis, tested on a non-development Mac, downloaded from transfer.sh via Travis), the second  screenshot was from my own DMG I created on my (development) Mac (with latest ffmpeg 3.3.3 installed). Sorry for the confusion.

However, neither version worked on the development Mac. I will further investigate and report back. Thanks in advance! =)

**Comment by bohning** [comment]
Okay, I just checked. The DMG from Travis contains libavcodec.**56**.dylib, but is missing libx264.148.dylib. When trying to run this version (on the non-development Mac), I get the above error that libx264.148.dylib is missing.

My own DMG built based on the 2017.08 master (and ffmpeg 3.3.3) contains both libavcodec.**57**.dylib and libx264.148.dylib. When trying to run this version (on the non-development Mac), I get
`An unhandled exception occurred at $00000001000AEC1B: EAccessViolation: Access violation
  $00000001000AEC1B
  $0000000100065A0D`

**Comment by s09bQ5** [comment]
Now I get it, you built the DMG that is linked for 2017.8.0, not Travis.
Do you have any way to resolve these addresses to symbols and disassembly snippets (or line numbers)?

**Comment by bohning** [comment]
@s09bQ5 I am afraid not or I don't understand your question. It does NOT run on a non-development Mac, therefore I don't have any more info than what I provided from that machine (unless you tell me how...). Wish I could be of more help to resolve the issue...

**Comment by ePirat** [comment]
Looks like something is not ok with how stuff is referenced, therefore the dynamic library loader does not find things. Unfortunately I do not have time to look into this right now, maybe in a few weeks.

**Comment by ePirat** [comment]
@basisbit 
> some library that xcode installs with it is missing. No idea about any details. Most likely only since Sierra or the version before that.

Unlikely, at least the reported error looks completely unrelated to Xcode libraries or specific macOS versions.

**Comment by bohning** [comment]
@ePirat @s09bQ5 Let me know if I can be of any help. I have two Macs at my hands, one set up with development environment (fpc 3.0.2, ffmpeg 3.3.3), the other one a non-development Mac, both Sierra 10.12.6.

**Comment by ePirat** [comment]
@bohning Could you try with this build please? https://nightlies.1750studios.com/usdx/UltraStarDeluxe_20170531.zip

**Comment by bohning** [comment]
@ePirat This nightly runs on the non-development Mac (obviously on the development Mac as well), only the graphics are missing:
![bildschirmfoto 2017-09-02 um 17 31 40](https://user-images.githubusercontent.com/1497707/29996827-2988dfee-9006-11e7-8f59-809290f7fdfd.png)
![bildschirmfoto 2017-09-02 um 17 31 56](https://user-images.githubusercontent.com/1497707/29996830-3042bd28-9006-11e7-84d0-d623c007825a.png)

**Comment by ePirat** [comment]
Thanks. Missing graphics is a known bug: #255

**Comment by ePirat** [comment]
Given that beta works fine (except the other know bugs), I will close this.
