### ISSUE TITLE
[Webcam-Preview] Screenshot message, UI not redrawn

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#3]
Steps to reproduce:
1. Start USDX
2. Click on Options
3. Click on Webcam
4. Select Webcam (0)
5. Click "Enable Preview"
6. Make Screenshot
7. Press "OK" to dispose message
8. Parts of the UI are not redrawn

![Screenshot-saved-stays](https://i.imgur.com/Z7wq2pI.png)

OS: Windows 10 64bit
latest.7z from 15-Dec-2015 10:30

**Comment by basisbit** [comment]
fixed with last commit.
