### ISSUE TITLE
Editor deletes tags

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#30]
Editor deletes tags such as #MEDLEYSTARTBEAT, #MEDLEYENDBEAT, #PREVIEWSTART, and possibly others. Presumably also on other operating systems.

**Comment by RattleSN4K3** [comment]
Confirmed. [I'm really glad I wasn't using the USDX 1.3 for editing files]

**Comment by bohning** [comment]
Since switching to Mac, it was pretty much my only (hassle-free) to edit files in the Ultrastar editor. Thanks for looking into it!

**Comment by RattleSN4K3** [comment]
It's happending on Windows as well, therefore I think it's like that accross platforms.

**Comment by bohning** [comment]
True, now that you mention it I remember that this also happened on Windows...

**Comment by RattleSN4K3** [comment]
Fixed with 5aa1153a6c1ac8efca6e393d7e810a71d389d176, ef7aabd2e703fc33b815e1c9437850d094409fb2.

As of bd9426d28e91f920901cde78b5fd7c9beed27515, you should be able to properly preview the medley and previewstart from the editor. Check the [readme](../blob/master/README.md)
