### ISSUE TITLE
Error Check on Ultrastar Deluxe Start

### ISSUE THREAD

**Issue by diver66** [UltraStar-Deluxe/USDX#301]
Ultrastar needs about 10 minutes to start up (i have about 5000 songs in the directory). Isn't it  possible to turn off the error checking ? And only have the check run on demand ?

**Comment by basisbit** [comment]
what version of the game are you using and what hardware? Please also provide an Error.log from the installation folder.
We tested the game with way more songs already and it didn't need 10 minutes to load.

**Comment by diver66** [comment]
Hi,

I am running Lubuntu and theUltrastar 2017.8.0 dev build, thanks for responding so fast

[Error.zip](https://github.com/UltraStar-Deluxe/USDX/files/1278899/Error.zip)

**Comment by basisbit** [comment]
"257ers - Holz" << that made be laugh... Didn't know it exists for karaoke!
As far as I remember, most of the time for analyzing the song files was used up for loading the song cover images, so it knows how big the SDL_Texture for the image will have to be. As you are running on a rather old and slow onboard intel gpu, that explains the 10 minutes waiting time (especially also if your song folder is stored on a hdd.

I guess you would have to sacrifice or at least rewrite the displaying of the cover images in the song selection screen if you want to get the game to start up quickly on that hardware with so many songs.

**Comment by diver66** [comment]
Okay, thanks, just one more little thing - the covers folders does not seem to work on linux, its supposed to show - if the option TABS ist set to ON, the images of artist,decade,edition,language,title. Artist and title should work out of the box, since there are images in the directory.

I have changed the path to example C=./home/diver66/USDX/game/covers/Artist/ArtistC.jpg - but no joy - any ideas ?

What does the [Folder] in covers.ini do ? Its also available to choose as sorting option in the game options menu.

**Comment by basisbit** [comment]
set tabs to on and restart the game. then you'll see the result if the song tags are written correctly

**Comment by basisbit** [comment]
with Folder you can specify folder preview "cover"/image files fort your folders

**Comment by basisbit** [comment]
when using "language" as sorting and tabs on: 
![image](https://user-images.githubusercontent.com/10870269/30084495-f6123022-9292-11e7-9cd6-2f64f245b63c.png)

**Comment by diver66** [comment]
thanks, i know this works great on my windows machine, but on my lubuntu , it does only show the default ultrastar image. That's why i think the paths in the linux version have to be adjusted  : 

English=.\Language\English.jpg
French=.\Language\French.jpg
German=.\Language\German.jpg

Does not work for me.

**Comment by basisbit** [comment]
no idea. please create a new issue for that problem and please fill in the issue template.
