### ISSUE TITLE
[Feature Request] Use multithreading for performance

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [UltraStar-Deluxe/USDX#303]
### Actual behaviour

At least under Linux / ARMv7 Raspian USDX only creates a single thread. The scheduler is not able to split tasks to different cores for performance reasons.

### Expected behaviour

It could be a good idea to split tasks to several threads. E.g. decoding video could be a seperate task, decoding audio, the engine, UI, IO etc. - so the problem has the chance to scale a bit better with multiple cores on slow systems lile Raspberry Pi 3, AMD NEO, Intel Atom etc.

### Steps to reproduce

Start the game and watch the processes created as well as their load with e.g. top / HTOP.

### Details

Provide some additional information:

- USDX version: latest git as of 2017-09-005
- ffmpeg 3.2.7 with the following settings:
```./configure  --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-libmp3lame --enable-static --enable-omx --enable-omx-rpi --enable-mmal  --prefix=/usr```
- Operating System + version: Raspian (Debian 9) Stretch

**Comment by basisbit** [comment]
this would require major code changes and I doubt any sane developer would do that work with freepascal. A rewrite of the game based on some other language and tooling is much more likely to happen. Will close this issue for now. If anyone wants to actually start work on this, please feel free to reopen this issue.

**Comment by cRaZy-bisCuiT** [comment]
One last question: Wouldn't it be quite easy to call an instance of external ffmpeg instead of using some functions of it compiled in the usdx code? Like that we have at least two threads which produce load and like this the scheduler could do its job. Maybe ffmpeg itself will create several threads by itself then as well.
