### ISSUE TITLE
Songs are listening with bad quality

### ISSUE THREAD

**Issue by danicasati** [UltraStar-Deluxe/USDX#305]
Hi.
I've installed 2017.08.0 version.
When I start to sing a song, it is reproducing correctly but audio quality i very low.

### Details
Provide some additional information:

- USDX version: 2017.08.0
- Operating System + version: Windows 10

**Comment by basisbit** [comment]
please try again to describe your actual problem or feel free to join our irc channel at https://webchat.freenode.net/?nick=usdx305.&channels=%23usdx&prompt=1
