### ISSUE TITLE
Build for Ubuntu 16.10

### ISSUE THREAD

**Issue by frankiejol** [UltraStar-Deluxe/USDX#306]
I'm trying to follow the guide for build USDX for Ubuntu. I may have missed something, but maybe docs can be improved from where I got stuck.

### Bass

I downloaded bass but I don't know where to put it. I unzipped but there is no make install nor I couldn't find any tip at the Bass website. I tried putting it inside an USDX dir.

### Build from Lazarus

This may come from my unability to install Bass, but when I try to compile it returns in the terminal:

    TCodeToolManager.HandleException: "include file not found "config-linux.inc"" at Line=71 Col=9 in
    "src/USDX-2017.8.0/src/switches.inc"

I couldn't find config-linux-inc file in Bass nor in the USDX sources, nor anywhere in my system nor with apt-file search. I see there is a config-win.inc. May be this file is missing.

### Steps to reproduce

1. Download USDX-2017.8.0.tar.gz
2. tar xzf USDX-2017.8.0.tar.gz
3. Start lazarus-ide
4. Open project src/ultrastardx-unix
5. Run -> Compile

### Details

- USDX version: 2017.8.0
- Linux Ubunty Yakkety 16.10

**Comment by diver66** [comment]
Hi,

try it like this 👍 

UltraStar Install

sudo apt-get install fp-compiler
sudo apt-get update && sudo apt-get install git fpc libsdl2-dev libsdl2-image-dev libsdl2-image-2.0-0 libsdl2-2.0-0 ffmpeg libavdevice-dev libsqlite3-0 libsqlite3-dev libpcre3 libpcre3-dev ttf-dejavu ttf-freefont portaudio19-dev lua5.1-dev libopencv-highgui-dev libprojectm-dev

git clone https://github.com/UltraStar-Deluxe/USDX
cd USDX
./autogen.sh
./configure
make
sudo make install
ultrastardx

works without a flaw

**Comment by s09bQ5** [comment]
The Linux build doesn't need BASS.
config-linux.inc is created by configure.
