### ISSUE TITLE
No mic usable

### ISSUE THREAD

**Issue by razette** [UltraStar-Deluxe/USDX#307]
Hi all,
I've had an issue with Ultrastar, my mics are not usable. I can choose them in the setup, but they doesn't work in the game  (I have one USB and another one plug in the jack of my mother board)
I have a message: No mic selected for player 1

os : Win 10 
ultrastar : 1.3.5

thx

**Comment by basisbit** [comment]
can not reproduce the problem. More details will be required to help you. Do the microphones show up in the record settings of windows? do they show up in the record settings of usdx? did you map the channels to the players microphones?

**Comment by razette** [comment]
All my apologies,
I haven't understood how assign mic to player. It's not very intuitive, but now it works.
 thx
![image](https://user-images.githubusercontent.com/31970829/30510551-a10b217e-9ac6-11e7-8e81-40a8d2d9e27d.png)
But what about auto-assign to player 1 mic device ? Or add label like "assign chanel to player N°" ?

**Comment by cRaZy-bisCuiT** [comment]
Could someone with appropriate rights please close the issue?
