### ISSUE TITLE
USDX hang when starting

### ISSUE THREAD

**Issue by douardda** [UltraStar-Deluxe/USDX#309]
From a fresh build (git rev c17ed6e41f213af0032a09a22c97fc2b7e985318) on a Debian stretch, I'm using a SongDir on a NFS mounted disk.

During start of the app, it stays locked on the "Loading..." splashscreen.

Digging a bit, I found that the FindFilesByExtension() (in base/USongs.pas) is recursively called indefinitely because at some point, the  FileSystem.FileFind iterator generates an empty string which make   FindFilesByExtension() start over again from the root directory it was called with.

**Comment by basisbit** [comment]
Thanks for using our issue template... Please provide steps on how to reproduce this.
Does the game launch without issues once you remove the NFS mounted song-dir from the config.ini?
Could you maybe check in the Error.log, if usdx is able to read any files at all from the NFS?
