### ISSUE TITLE
Editor does not display freestyle notes correctly

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#31]
The OSX editor displays freestyle notes with zero length, all squeezed together at the very beginning of the line.

**Comment by basisbit** [comment]
this also affects Windows / Linux versions -> all targets.

**Comment by RattleSN4K3** [comment]
The problems relies in b5391a310e17a59364815b255fdfcace5c49485f

From the code:
```pas
var
  TempR: real;
  lTmpA, lTmpB : real;
begin
  lTmpA := (Right-Left);
  lTmpB := (Lines[NrLines].Line[Lines[NrLines].Current].End_ - Lines[NrLines].Line[Lines[NrLines].Current].Note[0].Start);

  if ( lTmpA > 0 ) and ( lTmpB > 0 ) then
    TempR := lTmpA / lTmpB
  else
    TempR := 0;
```

It got changed to:

```pas
var
  TempR: real;
begin
  if (Lines[NrLines].Line[Lines[NrLines].Current].TotalNotes > 0) and ( Right-Left > 0 ) and ( (Lines[NrLines].Line[Lines[NrLines].Current].End_ - Lines[NrLines].Line[Lines[NrLines].Current].Note[0].Start) > 0 ) then
      TempR := (Right-Left) / (Lines[NrLines].Line[Lines[NrLines].Current].End_ - Lines[NrLines].Line[Lines[NrLines].Current].Note[0].Start)
```

The problem with this is a **rounding error**. The variables `lTmpA` and `lTmpB` were used for converting/casting _integer_ to _real_. Without such conversion/casting, the operator `/` is used as integral division with `1 / 2 = 0`. Depending on the compiler, with any expression being a _double_, _single_, _double_ (etc.), the operator is likely a floating point operator resulting into `1.0 / 2 = 0.5` (or `1 / 2.0 =0.5, to be safe both operator should be converted `1.0 / 2.0 = 0.0` ). Same applies if variables are used.

Pascal/FPC doesn't _like_ the casting of an integer to a real (like `real(MyIntegerValue)`). Therefore the workaround using another variable is used. However, using a 1.0-multiplication works.

```pas
var
  A, B: integer;
begin
  A:=1; B:=2;
  writeLn(Format('%n',[A/B])); // prints 0.5 IF it would crash, %n expects an floating value but gets a integer back
  writeLn(Format('%d',[A/B])); // prints 0
  writeLn(Format('%d', [(1.0*A)/(1.0*B)]); // prints 0.5
```

A possible fix for most of the line looks similar to this:
```pas
var
  TempLine: PLine;
begin
    TempLine := @Lines[NrLines].Line[Lines[NrLines].Current];
    TempR := ifthen(TempLine.End_ - TempLine.Note[0].Start = 0, 0.0, (Right-Left) / (1.0*(TempLine.End_ - TempLine.Note[0].Start)));
```

Where `TempLine` is used to replace all the other long expression accessing several arrays.

**Comment by RattleSN4K3** [comment]
Should work as expected.
![screenshot0021](https://cloud.githubusercontent.com/assets/6833006/16905880/71b20388-4cad-11e6-94fb-60c542ac248a.jpg)

Please test known problematic files (including files with empty lines which @basisbit mentioned in commit log in b5391a3).

**Comment by bohning** [comment]
Awesome, RattleSN4K3.
