### ISSUE TITLE
[ffmpeg] Make USDX ffmpeg 3.4 compatible

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [UltraStar-Deluxe/USDX#312]
### Actual behaviour

USDX is not able to be build against ffmpeg 3.4.

### Expected behaviour

USDX should be able to be build against ffmpeg 3.4 and running with it as well.

### Steps to reproduce

Clone USDX repository and try to build it. /autogen will not finish.

### Details

Note: ffmpeg shouldn't break it's API within a major version. 

- USDX version: latest git as of 2017_10_19
- Operating System + version: Arch Linux 4.13 + Mesa 17.2.2

**Comment by basisbit** [comment]
`Note: ffmpeg shouldn't break it's API within a major version.`

but it does break it within major version all the time, and even rather often within minor versions.

**Comment by UgnilJoZ** [comment]
Is anyone working on this?
Or can someone point me to what is missing in order to support ffmpeg 3.4?

**Comment by s09bQ5** [comment]
Nobody is working on this AFAIK.

You have to copy the src/lib/ffmpeg-3.2 folder for 3.4 and then check each file in there line by line against the C header files for FFmpeg. All types must have the same size and all constants the same values. The layout of structures/records must of course also be the same. It might be easier to diff the headers for ffmpeg-3.2 and ffmpeg-3.4 first to know where changes have to be made.

@basisbit, is there a semi-automated way to do this?
