### ISSUE TITLE
Missing configure for macOS

### ISSUE THREAD

**Issue by fuxx** [UltraStar-Deluxe/USDX#313]
Hi,

i've tried to setup a development environment for OS X today, unfortunately the configure is missing on the master branch.

### Actual behaviour

./configure does not work on master branch for macOS 

### Expected behaviour

./configure should exist

### Steps to reproduce

Check out project on macOS from master.
enter ./configure

### Details

Provide some additional information:

- USDX version: master branch
- Operating System + version: macOS 10.12

**Comment by basisbit** [comment]
this is as designed. please use the autogen / autoconf tools to generate the configure file as needed for your setup. These scripts check which versions of the various libraries are installed on your system and accordingly sets up the configure file.

**Comment by fuxx** [comment]
Alright, the Readme says something different for macOS :)
