### ISSUE TITLE
cvWaitKey(0) in UWebcam.pas blocks forever

### ISSUE THREAD

**Issue by s09bQ5** [UltraStar-Deluxe/USDX#318]
When enabling the webcam preview for a V4L2 camera in Linux with OpenCV 2.4, the first frame is displayed and then USDX locks up inside cvWaitKey. The camera preview works as expected when removing the cvWaitKey line.

The OpenCV people said on IRC that cvWaitKey is not necessary for capturing video. As far as I can see, only the Video for Windows backend needs an event loop like cvWaitKey to process the window messages, but we already have one inside SDL. In OpenCV 3.x the capture functionality has been moved from the highgui module, which provides cvWaitKey, into a separate videoio module, further hinting at its independence.

Do we need that cvWaitKey call on other platforms?
Please try without that line if you know how to recompile USDX.

**Comment by bohning** [comment]
@s09bQ5: does this also concern MacOS? If yes, let me know.

**Comment by hoehermann** [comment]
I do not know the USDX code very well, but I do work with OpenCV on a daily basis. The parameter in `cvWaitKey(int)` determines the time in milliseconds to wait for a keystroke. The functions main usage is to wait for keystrokes when having a GUI managed by OpenCV. `cvWaitKey(int)` should not be used in USDX except for debugging purposes.

**Comment by ePirat** [comment]
This does not affect macOS, as Webcam is broken anyway there.

**Comment by hoehermann** [comment]
I did some research. [This question](https://stackoverflow.com/questions/33710515/opencv-3-0-camera-not-accessible-by-cvcreatecameracapture) pointed me to [this known issue within OpenCV](https://web.archive.org/web/20170725231204/http://code.opencv.org/issues/4395) and finally to [this pull request](https://github.com/opencv/opencv/pull/2947).  
Bottom line seems to be that the ancient C function `cvCreateCameraCapture`, which USDX is using, is now broken in non-Windows environments. [Some answers](https://stackoverflow.com/questions/7708129/cvcreatecameracapture-not-working) recommend using the newer (eight year old) `cvCaptureFromCAM` or the newer C++ bindings, but neither are available in the headers USDX employs.

**Comment by s09bQ5** [comment]
No, the bottom line is that `cvCreateCameraCapture` will in current OpenCV versions not use the Windows DirectShow, Intel Perceptual Computing, Intel Media SDK, Windows RT, and GPhoto2 backends. Only the former two were in 2.4 supported by `cvCreateCameraCapture` and our users most likely only care about the first one. So far it is not a problem for us as we ship the Windows releases with ancient OpenCV DLLs.

**Comment by hoehermann** [comment]
Thank you for your insights.

It looks like `cvCaptureFromCAM` has indeed been deprecated in favour of `cvCreateCameraCapture`. I never expected a stackoverflow answer to be that wrong. In future, I want to check the sources more thorough.

**Comment by s09bQ5** [comment]
fixed by PR #382
