### ISSUE TITLE
Medley end screen

### ISSUE THREAD

**Issue by segabl** [UltraStar-Deluxe/USDX#321]
### Actual behaviour

When finishing a medley and it switches to the score screen, the first score shown is the score for the first song in the medly. You can then scroll through the songs to display individual scores. The total score is displayed at the end which makes it kind of confusing to tell which player won at the first glance.

### Expected behaviour

It would be more intuitive if the total score would be shown first and scrolling would reveal the individual scores so it is clear who won by the first look.

**Comment by bohning** [comment]
I agree.

**Comment by bohning** [comment]
Which song should be played while showing the total score? The last one? The first one? Neither, i.e. background music?

**Comment by segabl** [comment]
That's a good question actually. I would go for either the last one or none not really too sure, none might be weird if the user doesn't have background music enabled.

**Comment by basisbit** [comment]
do same behavior as with others (keep consistency). Just play the last song while in scores screen (or at least that would be my suggestion)
