### ISSUE TITLE
Free Pascal on x86-32 Linux uses wrong stack alignment

### ISSUE THREAD

**Issue by s09bQ5** [UltraStar-Deluxe/USDX#325]
We can't do anything about that. We have to wait until it is fixed in the compiler.
See https://bugs.freepascal.org/view.php?id=32710
This ticket should be kept for documentation purposes until then.

For me the bug manifests itself in a memory leak in the webcam code when using a non-default saturation or hue value or the "negative" filter because the image processing crashes before freeing the frames but USDX keeps running as it catches the exception.

**Comment by ePirat** [comment]
https://bugs.freepascal.org/view.php?id=15582

**Comment by s09bQ5** [comment]
Appears to be fixed in Free Pascal 3.2.0
