### ISSUE TITLE
"Slow motion" and crash when playing "2 Unlimited - Faces\2 Unlimited - Faces.flv"

### ISSUE THREAD

**Issue by amayii0** [UltraStar-Deluxe/USDX#329]
### Actual behaviour

I'm a new user and got a few crashes within the first 10-15 minutes of use. I've however been able to try out a few songs (full play, until score screen).
When browsing songs in regular mode, USD happens to crash when switching songs.
For this particular bug report, I was playing:
2 Unlimited - Faces
  26/11/2017  21:40        24.136.560 2 Unlimited - Faces.flv
  26/11/2017  21:40            58.347 2 Unlimited - Faces.jpg
  26/11/2017  21:39             2.406 2 Unlimited - Faces.txt

I was able to properly play the FLV using VLC 2.2.6
![2017-11-27_21-17-43](https://user-images.githubusercontent.com/9150547/33287259-71392722-d3b8-11e7-8e61-410a5bfcc285.jpg)

### Expected behaviour

Song should play at regular speed and not crash USD.

### Steps to reproduce

1. Open the ultrastardx.exe
2. Go to Sing mode
3. Select player (I've set only one)
4. Browse to 2 Unlimited - Faces (This is the first in my playlist, so just wait for preview)
(At this step, the video preview plays "slow motion", sound too)
5. On first try, USD crashed here. On second try it raised a new error when exiting video by hitting ESC key
![2017-11-27_21-23-57](https://user-images.githubusercontent.com/9150547/33287574-6376ced6-d3b9-11e7-8d9f-ad4c75b3ba87.jpg)

### Details
Intel i7 4770k, 16GB RAM
1070 GTX, 23.21.13.8831 (2017-11-14)
Sound Blaster Z (6.00.0102.0050)
Headset on jack in of SBZ

USD 1.3.5 beta
Windows 7 x64

Note: I'm using 3 screens (Left-Center-Right): 1600*1200 + 4K + 1600*1200. USD was running on central one.

### Attached files from USD
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/1507465/Error.log)
![2017-11-27_21-14-22](https://user-images.githubusercontent.com/9150547/33287147-08b3e264-d3b8-11e7-8e92-94d658748cf4.jpg)

[config.ini.txt](https://github.com/UltraStar-Deluxe/USDX/files/1507495/config.ini.txt)

**Comment by basisbit** [comment]
please use the current version of usdx (2017.8). If I remember correctly, those issues were fixed roughly a year ago.
Please report here if the current version solves these issues for you.

**Comment by amayii0** [comment]
Hmmm indeed I have missed the small "We moved to a new website." sentence close to the big title "Version: 1.3 Beta 2" at http://ultrastardx.sourceforge.net/usdx-downloads/usdx/

I've now installed 2017.08.

Reproducing same steps till preview (start USD, go to sing, select P1, wait for preview), I wasn't having any sound/preview, moving quickly to second and back to first song raised this error:
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/1507614/Error.log)
![2017-11-27_22-05-02](https://user-images.githubusercontent.com/9150547/33289284-52df4c14-d3bf-11e7-95a0-6fca20bd6f4c.jpg)

I can reproduce this each time with same song. Other songs around are fine (tried 2-3 back and forth).

**Comment by basisbit** [comment]
could you provide a download link for this song or send that to contact@usdx.eu so we can reproduce this issue? Also, updated error.log file would be nice.

**Comment by amayii0** [comment]
Info sent by mail

**Comment by basisbit** [comment]
sorry, won't register on another website / use torrent because of possibly legal issues in my country
