### ISSUE TITLE
[OSX] Editor displays the first line of text wrong on first open

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#33]
When you open the editor on a song ("E"), the first line of text is displayed incorrectly (inter-word and inter-letter spaces are messed up). If you change to another lyric and line and go back (arrow down/up), it is displayed correctly.

This is most likely the case for the other operating systems as well.

**Comment by RattleSN4K3** [comment]
Any example file? Does this still happen?

A related problem as been recently fixed #31.

**Comment by RattleSN4K3** [comment]
It this the same problem like this one, #83?

I cannot reproduce the case with changing the lyric line and got the line fixed (on Windows, current dev version, c3bb8cb.

**Comment by basisbit** [comment]
yes, same issue as #83

**Comment by RattleSN4K3** [comment]
#83 got resolved. Pending confirm. Is that fixing this problem on your side as well, @bohning?

**Comment by bohning** [comment]
Will test tonight and report back. Thanks!

**Comment by bohning** [comment]
Perfect, you can close this issue!

**Comment by RattleSN4K3** [comment]
Thanks for testing.
