### ISSUE TITLE
[MacOS] USB Mics record themselves only in usdx

### ISSUE THREAD

**Issue by about-design** [UltraStar-Deluxe/USDX#333]
**Please, do not create duplicate issues**

### Actual behaviour

If I use my USB Microphones with a Logitech Chip on macOS it is like the Mics record themselves.
I did not sing, but the Game fills the lines and gives points for singing.
In other Apps like Logic oder Garageband the Mics work fine.

### Expected behaviour

No self recording. 

### Steps to reproduce

Take a Mac, plug the Mics in and start a song.

### Details

Provide some additional information:

- latest build with fresh home-brew upgrade and ffmpeg 3.3.3
- macOS High Sierra 10.13.2

**Comment by about-design** [comment]
Maybe it is a problem with the sampling rate. They use max 48 kHz. If I use my Focusrite Scarlett 2i2 Interface there is something similar until 48 kHz. If I set the Interface to 96+ kHz the issue is solved. This problem is only in usdx, all other recording software works fine.

**Comment by ePirat** [comment]
Should be fixed by #358, please reopen if this still happens.
