### ISSUE TITLE
Search is not case-insensitive with Umlauts/special characters

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#334]
When searching for songs with Umlauts (here: die ärzte), the search yields no results even though there are several songs available of 'Die Ärzte' in the song collection, see screenshot:

<img width="1680" alt="bildschirmfoto 2017-12-17 um 12 49 51" src="https://user-images.githubusercontent.com/1497707/34079226-989f1710-e329-11e7-8ac9-82ab936bf631.png">

Have not tested if this is Mac-specific or not.

- USDX version: latest checkout (2017-12-16)
- Operating System + version: MacOS 10.13.2

**Comment by bohning** [comment]
Ah, maybe this can be closed. Indeed when I search for "Ärzte" (correct capitalization), all corresponding songs are found. So the search seems to be case-sensitive for special characters (while it is case-insensitive with regular characters - 'grönemeyer' finds all songs with artist 'Grönemeyer').

**Comment by s09bQ5** [comment]
Case-insensitive search with Unicode is difficult. Just think about the Turkish dotted and dotless i.

**Comment by bohning** [comment]
Ah, I see. So the current situation is that a search containing simple (ASCII) chars is case insensitive, but any search query containing chars beyond ASCII is case-sensitive?

**Comment by basisbit** [comment]
most libraries offer a normalization function for comparing or searching such strings. Search should be fully case insensitive and use such normalization function so the other finds what "looks" the same.

**Comment by bohning** [comment]
Yes, ideally even typos could be ignored, e.g. how Youtube does it:
<img width="495" alt="bildschirmfoto 2017-12-18 um 00 40 36" src="https://user-images.githubusercontent.com/1497707/34085149-35a48b8c-e38c-11e7-9bcb-638501742fb7.png">

**Comment by barbeque-squared** [comment]
This was probably fixed by #795

**Comment by bohning** [comment]
Yes, it's fixed.
