### ISSUE TITLE
Compiling with latest FFMPEG@2.8 release doesn't work

### ISSUE THREAD

**Issue by Kaes3kuch3n** [UltraStar-Deluxe/USDX#336]
(OS: macOS 10.13.2)

### Actual behaviour

The configure script doesn't find the latest version of ffmpeg@2.8 installed via homebrew, because it is using libavutil version 54.031.100. Changing the version in the configure script doesn't fix the issue, because this version of libavutil is not supported.

### Expected behaviour

It should compile using ffmpeg@2.8.

### Steps to reproduce

1. Install brew
2. `brew install fpc`
3. `xcode-select --install`
4. `brew install sdl2 sdl2_image automake portaudio binutils sqlite freetype lua libtiff pkg-config ffmpeg@2.8`
5. `git clone https://github.com/UltraStar-Deluxe/USDX`
6. `./autogen.sh`
7. `./configure`

### Details

Error:
`checking version of ffmpeg... configure: error: 
Unsupported ffmpeg version, most recent version supported is 3.3.`

**Comment by s09bQ5** [comment]
What is the output of `find /usr/local/opt/ffmpeg*/lib /usr/local/lib -name libavcodec.pc` on your system?
Do you also have ffmpeg 3.4.x installed?

**Comment by Kaes3kuch3n** [comment]
`/usr/local/opt/ffmpeg/lib/pkgconfig/libavcodec.pc
/usr/local/opt/ffmpeg@2.8/lib/pkgconfig/libavcodec.pc
/usr/local/opt/ffmpeg@3/lib/pkgconfig/libavcodec.pc
/usr/local/lib/pkgconfig/libavcodec.pc`

Yes, ffmpeg 3.4.1 is installed, too.

**Comment by Kaes3kuch3n** [comment]
Okay, I removed version 3.4.1 now and it is working! Thank you for the hint :)

**Comment by s09bQ5** [comment]
But you should also be able to use 3.4.1 with the latest development version of USDX.
