### ISSUE TITLE
[Request] Read *.txd files as duets

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#34]
Currently, *.txd files are simply ignored by USDX 1.3. These files have a different file extension to differentiate the regular non-duet version from the duet version of a song, while they share the same resources (mp3, video, cover, background) and are thus in the same folder.
I seem to have about 200 of those files.

**Comment by basisbit** [comment]
the file format is still txt and the same for duetts and non-duetts. Thus I don't really see why there is any reason to use a different fileextension for duetts. Please rename them to .txt and put something in the filename to mark them as duet.

**Comment by bohning** [comment]
I guess I can live with it, but it seems to be an easy feature to add, especially considering compatibility for existing (duet) files. While the file format is still a plain text file, it is obvious to the user that the contents require "P1" and "P2" in it, otherwise the file won't work. This is particularly important in the face of usdb, where these tags (unfortunately still) get deleted during upload.

**Comment by basisbit** [comment]
sorry, but whoever came up with that idea didn't do a good job and doesn't know the idea of file extensions in Microsoft Windows based systems.
usdx 1.1 and usdx wp never "supported" .txd files.
the P1 and P2 tags are what the usdx software uses to detect if a song file is duett or not.
Usually for every song you have something like a "[language]Artistname - Songname" folder which contains 
- cover.png (600x600 px)
- background.png (1920x1080px)
- instrumental.txt
- notes.txt
- duet.txt (containing the "#P1:" (and/or "#DUETSINGERP1:" tags) and the "P1", "P2" lines)
- instrumental.mp3 (320 Kb/s)
- song.mp3 (320 Kb/s)
- video.mp4 (h264 mpeg4 720p with no audio stream)

there, each txt file is sort of an "edition" of the same song. Such a setup will work with performous, vocaluxe, usdx wp and usdx 1.3.
The quality and file format information are just my suggestions based on what I see in the wild in the various usdx song creation communities.

If there is any good reason for using an extra file extension for duet files except for some rare legacy stuff, please tell me and I'll be glad to implement it.
