### ISSUE TITLE
API for Ultrastar

### ISSUE THREAD

**Issue by psx01de** [UltraStar-Deluxe/USDX#340]
Hi there,

just a question: is there something like an API which could be used to

1.) request the available songs
2.) start a song
3.) get information about which song is currently playing including the BPM and other infos (maybe with MIDI or OSC)

With that it would be possible to 
a) create a own interface (e.g. on a tablet)
b) control external devices e.g. lights, screens, speakers. You would be able to start a light show if a song is playing or execute llight scenes for bonus points, color of the winner....

Thanks,
Patrick

**Comment by basisbit** [comment]
nope, does not currently exist.
