### ISSUE TITLE
[Retropie] Access Violation | ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by ricardRuiz** [UltraStar-Deluxe/USDX#341]
### Actual behaviour
After installing UltraStar Deluxe on a raspberry pi3 b under the retropie system, the game will not start.

### Expected behaviour
What should happen is that the game runs correctly.

### Steps to reproduce
1. Compiling on Linux/BSD using make (README.me)
1.1 `./configure` works perfectly.
![sdfg](https://user-images.githubusercontent.com/31921480/34521796-f2650b42-f08f-11e7-84af-d16f2696bcf1.png)
1.2 `make `give me some warnings.
![imagen](https://user-images.githubusercontent.com/31921480/34521846-3c7920e2-f090-11e7-9e1b-24a1677883d2.png)
1.3 `sudo make install` looks like it works perfectly.
![imagen](https://user-images.githubusercontent.com/31921480/34525816-7d1f0408-f0a0-11e7-888c-d2d851dcbf3a.png)

2. Start the game.
2.1. See errors.
![ultrastardx](https://user-images.githubusercontent.com/31921480/34521733-9ac08452-f08f-11e7-9f1b-7d57b1b38f3c.png)

3. Fix the ALSA Warnings.
![asdfl](https://user-images.githubusercontent.com/31921480/34522920-60c3498c-f095-11e7-8147-bf3cb0b7e8d8.png)
3.1 Same errors.
![imagen](https://user-images.githubusercontent.com/31921480/34526109-a8d07b4e-f0a1-11e7-9419-413487ed8b95.png)

### Details
- USDX version: 2017.8.0+
- Operating System + version: Retropie v4.3
- Machine: Raspberry pi3 B
- Audio output: Jack 3.5mm

**Comment by s09bQ5** [comment]
My gut instinct tells me that this crash might not be related to ALSA at all.
Can you upload ./game/Error.log and the log file create by `strace -fFo strace.log ./game/ultrastardx`?
Do you get a more descriptive error message if you configure with --enable-debug and run ultrastardx in gdb?
Does OpenGL work with other applications on the device?

**Comment by ricardRuiz** [comment]
Log Files:
1. [Error.log](https://github.com/UltraStar-Deluxe/USDX/files/1601300/Error.log) 
2. [strace.log](https://github.com/UltraStar-Deluxe/USDX/files/1601301/strace.log)

The first one failed because it had emulationstation open
![retropie](https://user-images.githubusercontent.com/31921480/34534023-ecb1cb2c-f0bc-11e7-97e7-e8b13c5335c8.PNG)
About OpenGL the Retropie system has an experimental desktop OpenGL driver.
By default is on G3 Option, "Legacy non-GL desktop driver".
![imagen](https://user-images.githubusercontent.com/31921480/34534077-235cadd6-f0bd-11e7-97ae-7367a2ff735f.png)

by the way, if i enable the G1 (Full KMS) and start the game, the execution get stuck 
![imagen](https://user-images.githubusercontent.com/31921480/34534183-801fbfcc-f0bd-11e7-80ea-27ba7d50d67d.png)
and my raspberry don't boot EmulationStation, showing me 3 errors.
"lvl0: Error initializing SDL!"
"lvl0: Render failed to initialize"
"lvl0: Window failed to initialize"

I suspect it does not work, ultrastardx on retropie D:

**Comment by s09bQ5** [comment]
The Raspberry Pi OpenGL driver apparently needs X11.
Error.log shows that you only have OpenGL ES with the G3 option, which does not work with ultrastardx.
