### ISSUE TITLE
Random frozen or crash - Access violation

### ISSUE THREAD

**Issue by blackPantherOS** [UltraStar-Deluxe/USDX#344]
The binary made from actual Git version
System: Linux x86
Fpc: 3.0.0
Gcc: 5.4.0
Note: The application working without any songs

### Actual behaviour
1.) Frozen "Loading screen" when reading song list, by random song. Output:

WARN:   "Aqua - Barbie Girl.txt" in line 649: character expected but found "-1511" [TSong.ParseLyricCharParam]
ERROR:  Reading headers from file failed. File incomplete or not Ultrastar txt?: /USER/.ultrastardx/songs/Aqua - Barbie Girl/Aqua - Barbie Girl.txt
ERROR:  Can't find video file in song: /USER/.ultrastardx/songs/Carl Douglas - Kung Fu Fighting/Carl Douglas - Kung Fu Fighting.txt
ERROR:  Reading headers from file failed. File incomplete or not Ultrastar txt?: /USER/.ultrastardx/songs/Carl Douglas - Kung Fu Fighting/Carl Douglas - Kung Fu Fighting.txt
ERROR:  AnalyseFile failed for "/USER/.ultrastardx/songs/Carl Douglas - Kung Fu Fighting/Carl Douglas - Kung Fu Fighting.txt".
Sorry, an error ocurred! Please report this error to the game-developers. Also check the Error.log file in the game folder.
Stacktrace:
Exception class: EAccessViolation
Message: Access violation
  $08062F84
  $081A2EE4
  $081A3024
  $080FC237
  $080B8476
  $080BA55B
  $080BA1FA
  $080BA0EF
  $080B9ED0
  $080A2C4C
  $080A69D2
  $0804D221

### Steps to reproduce
Not changed songlist, just started again and crash now with different song, output

ERROR:  Can't find video file in song: /USER/.ultrastardx/songs/Black Eyed Peas - Don t Lie/Black Eyed Peas - Don t Lie.txt
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 10: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 12: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 19: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 20: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 23: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 28: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 32: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 34: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
WARN:   "/USER/.ultrastardx/songs/Edda - Kör/Edda - Kör Közepén állok.txt" in line 35: found note with length zero -> converted to FreeStyle [TSong.LoadSong]
An unhandled exception occurred at $08062F84:
EAccessViolation: Access violation
  $08062F84
  $080A174A

An unhandled exception occurred at $0806D745:
EInOutError: Invalid file handle
  $0806D745
  $08063A86
  $080A18F5
  $0804D3EB

### Details

EDIT: links removed

**Comment by s09bQ5** [comment]
Please remove links to copyrighted works and please retry with a binary that has been built with debug symbols (configure with --enable-debug).

**Comment by blackPantherOS** [comment]
Hi, sorry for links... I see you removed links already, thanks. So debug mode still enabled . We rebuild the package without strip and compress on one core (j1) and we can't reprocedure this problem, because the USDX working fine now.

**Comment by s09bQ5** [comment]
Maybe fixed by d7fdd4bb51c0644e139544637562b7bc4572ae48?

**Comment by basisbit** [comment]
looks like the issue was resolved already. If the problem still happens, please reopen this issue.
