### ISSUE TITLE
Q: Is the UltraStar .txt song format friendly with complex tempo map ?

### ISSUE THREAD

**Issue by X-Raym** [UltraStar-Deluxe/USDX#349]
Hi,

### Actual behaviour

According to doc I find online, event positions in the .txt song format are expressed in **integer beats**. In the CSV, it is the second column.

`: 18 1 -8 Word`

The actual timecode is then calculated in milliseconds from a simple calculation with the `#BPM` header field.

This seems great if the song is pure 4/4 with fixed tempo and notes aligned on the grid.
But what if the song as multiple time signature and tempo changes ? Progressive tempo changes like accelerandi or rallentandi ? Or complex swing movements ?

### Expected behaviour

I think it would be way more flexible to have **timecode expressed in milliseconds**, as absolute position.
**No more BPM or GAP fields** required. It would be way more flexible for building song generator third party script from other file format.
I currently map a song with MIDI, doing all the beat matching, and when I imported into YASS, it was completely messed up because of these time changes. Notes were not aligned on the grid (cause grid is fixed), and moving them was kind of extra difficult.

Another solution would be to allow entering this complex tempo changes by having new line markers. But IMHO, the absolute milliseconds timecode position would be more flexible.

Did I miss something ?

Thanks for listening 😸

**Comment by basisbit** [comment]
just adjust the bpm to fit into something like 250 and 400. Anything else would result in either not exact notes positioning or too much work when creating / editing the file.

**Comment by X-Raym** [comment]
@basisbit Ok, I see you point the idea is to have 1 / ( 400 / 60 ) = 15ms steps between each notes.
Too bad that the BPM isn't semantic though, cause having one BPM only make third party softwares like YASS less friendly to use (as the grid doesn't match the song logic).

Thanks for your support.

**Comment by X-Raym** [comment]
150ms seems quite high actually. Is 400 bpm the limit ?

**Comment by basisbit** [comment]
it is not the limit, but the amount of work that is required for creating/editing the songs rises exponentially with higher bpm. There is no gain in the exactness of notes above 400bpm because of the average differences in audio / video delay even with the more expensive hardware. The problem you mentioned regarding the grid not matching the song logic usually doesn't apply for vocals because singers tend to never hit the written notes perfectly in time - it usually is better to align the notes to what was sung, instead of aligning the notes to what was written when the song was originally composed.

There is no hard bpm limit coded in the software (except for some incredibly high number). The advantages of such a simplified "bpm" based numbering outweight the disadvantages in most USDX developers opinions so far, but was discussed a couple of times.

**Comment by X-Raym** [comment]
@basisbit Thanks for the explanation. I understand that you have discussed and experience this before, and why you chose not having high precision after all. I'm still think though that for using third party app for sync song, if the files could translate what the music is really is (semantic BPM, multiple grid size...), it would be more handy. But if we consider that ultra start is just a destination format, it should be ok (considering the amount of songs done by the community, it surely is).

Well, I made few experiment, but I'm not sure it's good,

Considering an intial bpm, and a note pos in second what would be the formulas to convert to utlrastar timecode ?

I have something like this:

```lua
bpm = 400
beat_duration = 1 / (bpm / 60 )
function SecondToBeats( seconds )
  local beat_pos =  second / beat_duration
  return math.floor( ( beat_pos + (beat_duration / 2) ) ) -- (round second to closest beat position)
end
```

Did I miss something ?

**Comment by X-Raym** [comment]
Also, has BPM to be an integer or can it be decimal ?

**Comment by bohning** [comment]
It can be decimal, yes.

Not sure if I am completely right, but BPM actually refers to QUARTER beats, so if a song has a BPM of 120, USDX-BPM should ideally be 480. There is or used to be a #RESOLUTION tag that defines the subdivision of a beat and is implicitly 4, therefore QUARTER beats, but it could be set to 8 to have 8 subdivisions of a beat. But I guess RESOLUTION is somewhat deprecated.

**Comment by X-Raym** [comment]
Oh, thanks to your advice, I manage to do what I needed (scripts for interoperability with REAPER).

[ReaScripts: Creating Karaoke Songs for UltraStar and Vocaluxe with REAPER](https://www.extremraym.com/en/reaper-ultrastar-reascripts/)

Hope it can be useful!

Cheers 😃
