### ISSUE TITLE
Instant Crash at Program start

### ISSUE THREAD

**Issue by Kazzt** [UltraStar-Deluxe/USDX#351]
Toshiba Satelitte Pro Dual Core
Fresh Win 7 Installation

Gives me the Error I attached.
Ultrastar Deluxe 1.3.5 Beta build
Installed via Installer.exe

Problem every startup

For more system Info gimme a reply on what u need

Error.log
`UltraStar Deluxe V 1.3.5 beta Build Error Log
Date: 26.01.2018 Time: 18:02:55
-------------------
STATUS: Load Language [Initialization]
STATUS: Loading Skin List [Initialization]
STATUS: Loading Theme List [Initialization]
STATUS: Searching for Theme : C:\Program Files\UltraStar Deluxe\themes\*.ini [Theme.LoadList]
STATUS: Found Theme: Deluxe.ini [Theme.LoadList]
STATUS: Found Theme: Modern.ini [Theme.LoadList]
STATUS: Website-Manager [Initialization]
STATUS: DataBase System [Initialization]
STATUS: Initializing database: "C:\Program Files\UltraStar Deluxe\Ultrastar.db" [TDataBaseSystem.Init]
STATUS: Load Ini [Initialization]
STATUS: GamePath : C:\Program Files\UltraStar Deluxe\ []
STATUS: Using config : C:\Program Files\UltraStar Deluxe\config.ini [Ini]
ERROR:  Could not load website "mlkhs.dll": Basic Procedures not found
STATUS: Found Video Mode: 1440x900 [Video]
STATUS: Found Video Mode: 1280x768 [Video]
STATUS: Found Video Mode: 1280x720 [Video]
STATUS: Found Video Mode: 1152x864 [Video]
STATUS: Found Video Mode: 1024x768 [Video]
STATUS: Found Video Mode: 800x600 [Video]
STATUS: Found Video Mode: 640x480 [Video]
STATUS: Found Video Mode: 640x400 [Video]
STATUS: Found Video Mode: 512x384 [Video]
STATUS: Found Video Mode: 400x300 [Video]
STATUS: Found Video Mode: 320x240 [Video]
STATUS: Found Video Mode: 320x200 [Video]
STATUS: Found resolutions: 12 [Video]
STATUS: Write Ini [Initialization]
STATUS: Loading: C:\Program Files\UltraStar Deluxe\themes\Modern.ini [TTheme.LoadTheme]
ERROR:  no texture type for LoadingStaticAnimation found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SongRouletteStaticCat found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxStaticActualSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongMenuTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressSong found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressWeb found. [TTheme.ThemeLoadStatic]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\Common start.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\Common back.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\menu swoosh.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\select music change music 50.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\option change col.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\rimshot022b.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\Applause.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files\UltraStar Deluxe\sounds\background track.mp3" [TAudioPlaybackBase.OpenDecodeStream]
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config fullscreen resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Fullscreen [SDL_SetVideoMode]
INFO:   OpenGL vendor Microsoft Corporation [UGraphic.InitializeScreen]
INFO:   OpenGL renderer GDI Generic [UGraphic.InitializeScreen]
INFO:   OpenGL version 1.1.0 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor Microsoft Corporation [TTextureUnit.Create]
INFO:   OpenGL renderer GDI Generic [TTextureUnit.Create]
INFO:   OpenGL version 1.1.0 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: 0 [TTextureUnit.Create]
STATUS: TDisplay.Create [UGraphic.Initialize3D]
STATUS: Loading Font Textures [UGraphic.Initialize3D]
STATUS: Building Fonts [LoadTextures]
STATUS: Loading Loading Screen [UGraphic.Initialize3D]
STATUS: Loading and checking songs [UGraphic.Initialize3D]
STATUS: Creating Category Covers Array [Initialization]
STATUS: Creating Avatars Cache [Initialization]
STATUS: Creating Song Array [Initialization]
STATUS: Searching For Songs [SongList]
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Bodo Wartke - Liebeslied\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Bodo Wartke - Liebeslied\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Dead Smiling Pirates - I 18\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Dead Smiling Pirates - I 18\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - A Talk with George\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - A Talk with George\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Better\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Better\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Big Bad World One\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Big Bad World One\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Chiron Beta Prime\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Chiron Beta Prime\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Code Monkey\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Code Monkey\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Creepy Doll\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Creepy Doll\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Dance, Soterios Johnson, Dance\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Dance, Soterios Johnson, Dance\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - First of May\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - First of May\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Flickr [VIDEO]\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Flickr [VIDEO]\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Furry Old Lobster\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Furry Old Lobster\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I Crush Everything\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I Crush Everything\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I Feel Fantastic\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I Feel Fantastic\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I'm Your Moon\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - I'm Your Moon\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Ikea\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Ikea\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Monkey Shines\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Monkey Shines\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Mr. Fancy Pants\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Mr. Fancy Pants\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - My Beige Bear\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - My Beige Bear\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Not About You\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Not About You\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Re- Your Brains\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Re- Your Brains\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Shop Vac\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Shop Vac\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Skullcrusher Mountain\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - Skullcrusher Mountain\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - That Spells DNA\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - That Spells DNA\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - The Future Soon\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - The Future Soon\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - When You Go\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Jonathan Coulton - When You Go\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Joshua Morin - On The Run\License.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Joshua Morin - On The Run\License.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Pornophonique - Space Invaders\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Pornophonique - Space Invaders\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Pornophonique - Space Invaders (Kar)\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Pornophonique - Space Invaders (Kar)\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - 69\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - 69\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - 69 (Kar)\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - 69 (Kar)\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - Can't stop it\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - Can't stop it\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - Can't stop it (Kar)\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - Can't stop it (Kar)\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - Consequence of Dawn\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - Consequence of Dawn\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - In My Hand\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - In My Hand\license.txt".
ERROR:  File contains empty lines or BPM tag missing: C:\Program Files\UltraStar Deluxe\songs\Shearer - Man Song\license.txt
ERROR:  AnalyseFile failed for "C:\Program Files\UltraStar Deluxe\songs\Shearer - Man Song\license.txt".
STATUS: Search Complete [SongList]
STATUS: Creating 2nd Song Array [Initialization]
STATUS:  Loading Textures [UGraphic.Initialize3D]
STATUS: Loading Textures [LoadTextures]
STATUS: Loading Textures - A [LoadTextures]
STATUS: Loading Textures - B [LoadTextures]
STATUS: Loading Textures - C [LoadTextures]
STATUS: Loading Textures - Done [LoadTextures]
STATUS:  Loading Screens [UGraphic.Initialize3D]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
STATUS: Finish [Initialize3D]
STATUS: Playlist Manager [Initialization]
STATUS: Effect Manager [Initialization]
STATUS:   # Name                           Version  Status     Paused  #Errors [LuaCore Plugins]
STATUS:   0 party mode: 1000blind          1.00     running    False   0      [LuaCore Plugins]
STATUS:   1 party mode: 2000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   2 party mode: 2000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   3 party mode: 5000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   4 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   5 party mode: 500blind           1.00     running    False   0      [LuaCore Plugins]
STATUS:   6 party mode: 7000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   7 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   8 party mode: blindLyrics        1.00     running    False   0      [LuaCore Plugins]
STATUS:   9 party mode: blindTotal         1.00     running    False   0      [LuaCore Plugins]
STATUS:  10 party mode: blind              1.00     running    False   0      [LuaCore Plugins]
STATUS:  11 party mode: deaf               1.00     running    False   0      [LuaCore Plugins]
STATUS:  12 party mode: duel               1.00     running    False   0      [LuaCore Plugins]
STATUS:  13 party mode: hardcore           1.00     running    False   0      [LuaCore Plugins]
STATUS:  14 party mode: holdtheline        0.6      running    False   0      [LuaCore Plugins]
STATUS:  15 party mode: holdthelineblind   0.6      running    False   0      [LuaCore Plugins]
STATUS:  16 party mode: shortsong          1.00     running    False   0      [LuaCore Plugins]
STATUS:  17 party mode: teamduel           1.00     running    False   0      [LuaCore Plugins]
STATUS: Main Loop [Initialization]
ERROR:  Fading disabled: ungültiger Wert [TDisplay.Draw]
![crash](https://user-images.githubusercontent.com/35846603/35452105-c9c500b4-02c5-11e8-93b5-eb80d1495f76.png)
`

**Comment by basisbit** [comment]
please use a current version of this game. You can download it here at github or on our official website https://usdx.eu
