### ISSUE TITLE
USDX won´t start anymore

### ISSUE THREAD

**Issue by TendouPein** [UltraStar-Deluxe/USDX#353]
Hey guys, I really love USDX but since I downloaded a few songs it wont start anymore.
I simply click on USDX (V 1.3.5 beta build) but it shows me an error message.

UltraStar Deluxe V 1.3.5 beta Build Error Log
Date: 09.02.2018 Time: 23:20:15
-------------------
STATUS: Load Language [Initialization]
STATUS: Loading Skin List [Initialization]
STATUS: Loading Theme List [Initialization]
STATUS: Searching for Theme : C:\Program Files (x86)\UltraStar Deluxe\themes\*.ini [Theme.LoadList]
STATUS: Found Theme: Deluxe.ini [Theme.LoadList]
STATUS: Found Theme: Modern.ini [Theme.LoadList]
STATUS: Website-Manager [Initialization]
STATUS: DataBase System [Initialization]
STATUS: Initializing database: "C:\Program Files (x86)\UltraStar Deluxe\Ultrastar.db" [TDataBaseSystem.Init]
STATUS: Load Ini [Initialization]
STATUS: GamePath : C:\Program Files (x86)\UltraStar Deluxe\ []
STATUS: Using config : C:\Program Files (x86)\UltraStar Deluxe\config.ini [Ini]
ERROR:  Could not load website "mlkhs.dll": Basic Procedures not found
STATUS: Found Video Mode: 1920x1080 [Video]
STATUS: Found Video Mode: 1680x1050 [Video]
STATUS: Found Video Mode: 1600x900 [Video]
STATUS: Found Video Mode: 1440x900 [Video]
STATUS: Found Video Mode: 1400x1050 [Video]
STATUS: Found Video Mode: 1366x768 [Video]
STATUS: Found Video Mode: 1360x768 [Video]
STATUS: Found Video Mode: 1280x1024 [Video]
STATUS: Found Video Mode: 1280x960 [Video]
STATUS: Found Video Mode: 1280x800 [Video]
STATUS: Found Video Mode: 1280x768 [Video]
STATUS: Found Video Mode: 1280x720 [Video]
STATUS: Found Video Mode: 1280x600 [Video]
STATUS: Found Video Mode: 1152x864 [Video]
STATUS: Found Video Mode: 1024x768 [Video]
STATUS: Found Video Mode: 800x600 [Video]
STATUS: Found Video Mode: 640x480 [Video]
STATUS: Found Video Mode: 640x400 [Video]
STATUS: Found Video Mode: 512x384 [Video]
STATUS: Found Video Mode: 400x300 [Video]
STATUS: Found Video Mode: 320x240 [Video]
STATUS: Found Video Mode: 320x200 [Video]
STATUS: Found resolutions: 22 [Video]
STATUS: Write Ini [Initialization]
STATUS: Loading: C:\Program Files (x86)\UltraStar Deluxe\themes\Modern.ini [TTheme.LoadTheme]
ERROR:  no texture type for LoadingStaticAnimation found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SongRouletteStaticCat found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxStaticActualSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongMenuTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressSong found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressWeb found. [TTheme.ThemeLoadStatic]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common start.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common back.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\menu swoosh.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\select music change music 50.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\option change col.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\rimshot022b.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Applause.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\background track.mp3" [TAudioPlaybackBase.OpenDecodeStream]
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Borderless fullscreen [SDL_SetVideoMode]
INFO:   OpenGL vendor Intel [UGraphic.InitializeScreen]
INFO:   OpenGL renderer Intel(R) HD Graphics 505 [UGraphic.InitializeScreen]
INFO:   OpenGL version 4.5.0 - Build 22.20.16.4749 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor Intel [TTextureUnit.Create]
INFO:   OpenGL renderer Intel(R) HD Graphics 505 [TTextureUnit.Create]
INFO:   OpenGL version 4.5.0 - Build 22.20.16.4749 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]
STATUS: TDisplay.Create [UGraphic.Initialize3D]
STATUS: Loading Font Textures [UGraphic.Initialize3D]
STATUS: Building Fonts [LoadTextures]
STATUS: Loading Loading Screen [UGraphic.Initialize3D]
STATUS: Loading and checking songs [UGraphic.Initialize3D]
STATUS: Creating Category Covers Array [Initialization]
STATUS: Creating Avatars Cache [Initialization]
STATUS: Creating Song Array [Initialization]
STATUS: Searching For Songs [SongList]
INFO:   Empty field "MEDLEYSTARTBEAT" in file C:\Program Files (x86)\UltraStar Deluxe\songs\Depeche Mode - Just Can´t Get Enough\Depeche Mode - Just Can´t Get Enough.txt [TSong.ReadTXTHeader]
INFO:   Empty field "MEDLEYENDBEAT" in file C:\Program Files (x86)\UltraStar Deluxe\songs\Depeche Mode - Just Can´t Get Enough\Depeche Mode - Just Can´t Get Enough.txt [TSong.ReadTXTHeader]
STATUS: Search Complete [SongList]
STATUS: Closing DB file [Finalization]
INFO:   TDataBaseSystem.Free [TDataBaseSystem.Destroy]
STATUS: Finalize Media [Finalization]
STATUS: Uninitialize 3D [Finalization]
STATUS: Kill Fonts [UnloadFontTextures]
STATUS: Finalize SDL [Finalization]
STATUS: Finalize Log [Finalization]

I run Windows 10
Thank you very much for this game!

**Comment by basisbit** [comment]
please use the current version of this game which you can find at https://github.com/UltraStar-Deluxe/USDX/releases
