### ISSUE TITLE
Error while compiling on macOS 10.13.3

### ISSUE THREAD

**Issue by about-design** [UltraStar-Deluxe/USDX#354]
**Please, do not create duplicate issues**

### Actual behaviour

There is an error while compiling the newest code.

Compiling base/UHelp.pas
Assembling (pipe) ../build/fpc-i386-darwin/UHelp.s
Compiling base/UGraphic.pas
UGraphic.pas(581,3) Note: Local variable "I" not used
UGraphic.pas(584,3) Note: Local variable "Depth" not used
UGraphic.pas(791,5) Note: Local variable "w" not used
UGraphic.pas(791,7) Note: Local variable "h" not used
Assembling (pipe) ../build/fpc-i386-darwin/UGraphic.s
Compiling base/UParty.pas
Assembling (pipe) ../build/fpc-i386-darwin/UParty.s
UScreenPopup.pas(875,3) Note: Local variable "Value" is assigned but never used
UScreenPopup.pas(975,26) Warning: Implicit string type conversion from "AnsiString" to "WideString"
UScreenPopup.pas(975,38) Warning: Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
UScreenPopup.pas(955,3) Note: Local variable "I" not used
UScreenPopup.pas(1089,29) Warning: Implicit string type conversion from "AnsiString" to "WideString"
UScreenPopup.pas(1096,48) Warning: Implicit string type conversion from "AnsiString" to "UnicodeString"
UScreenPopup.pas(1110,39) Warning: Implicit string type conversion from "AnsiString" to "WideString"
UScreenPopup.pas(1594,27) Warning: Function result does not seem to be set
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPopup.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenCredits.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenStatDetail.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenStatMain.s
UScreenPartyTournamentOptions.pas(105,3) Note: Local variable "I" not used
UScreenPartyTournamentOptions.pas(105,6) Note: Local variable "J" not used
UScreenPartyTournamentOptions.pas(160,5) Note: Local variable "I" not used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyTournamentOptions.s
UScreenPartyTournamentPlayer.pas(173,3) Note: Local variable "I" not used
UScreenPartyTournamentPlayer.pas(440,3) Note: Local variable "I" not used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyTournamentPlayer.s
UScreenPartyTournamentRounds.pas(143,3) Note: Local variable "p" not used
UScreenPartyTournamentRounds.pas(143,6) Note: Local variable "I" not used
UScreenPartyTournamentRounds.pas(649,3) Note: Local variable "I" not used
UScreenPartyTournamentRounds.pas(953,3) Note: Local variable "I" not used
UScreenPartyTournamentRounds.pas(953,6) Note: Local variable "J" not used
UScreenPartyTournamentRounds.pas(953,9) Note: Local variable "Count" not used
UScreenPartyTournamentRounds.pas(963,3) Note: Local variable "CurrentTick" not used
UScreenPartyTournamentRounds.pas(1004,23) Note: Local variable "YQ5" is assigned but never used
UScreenPartyTournamentRounds.pas(1004,28) Note: Local variable "YQ6" is assigned but never used
UScreenPartyTournamentRounds.pas(1004,33) Note: Local variable "YQ7" is assigned but never used
UScreenPartyTournamentRounds.pas(1004,38) Note: Local variable "YQ8" is assigned but never used
UScreenPartyTournamentRounds.pas(1005,13) Note: Local variable "YS3" is assigned but never used
UScreenPartyTournamentRounds.pas(1005,18) Note: Local variable "YS4" is assigned but never used
UScreenPartyTournamentRounds.pas(1005,28) Note: Local variable "YF2" is assigned but never used
UScreenPartyTournamentRounds.pas(1358,23) Note: Local variable "YQ5" is assigned but never used
UScreenPartyTournamentRounds.pas(1358,28) Note: Local variable "YQ6" is assigned but never used
UScreenPartyTournamentRounds.pas(1358,33) Note: Local variable "YQ7" is assigned but never used
UScreenPartyTournamentRounds.pas(1358,38) Note: Local variable "YQ8" is assigned but never used
UScreenPartyTournamentRounds.pas(1359,13) Note: Local variable "YS3" is assigned but never used
UScreenPartyTournamentRounds.pas(1359,18) Note: Local variable "YS4" is assigned but never used
UScreenPartyTournamentRounds.pas(1359,28) Note: Local variable "YF2" is assigned but never used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyTournamentRounds.s
UScreenPartyTournamentWin.pas(198,3) Note: Local variable "p" not used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyTournamentWin.s
Assembling (pipe) ../build/fpc-i386-darwin/UPartyTournament.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyRounds.s
UScreenPartyPlayer.pas(645,3) Note: Local variable "I" not used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyPlayer.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyWin.s
UScreenPartyOptions.pas(265,3) Note: Local variable "I" not used
UScreenPartyOptions.pas(53,7) Note: Private field "TScreenPartyOptions.SelectRounds" is never used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyOptions.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyScore.s
UScreenPartyNewRound.pas(167,6) Note: Local variable "R" is assigned but never used
UScreenPartyNewRound.pas(270,3) Note: Local variable "I" not used
Assembling (pipe) ../build/fpc-i386-darwin/UScreenPartyNewRound.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenSongJumpto.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenSongMenu.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenAbout.s
Assembling (pipe) ../build/fpc-i386-darwin/UScreenOpen.s
UScreenEditConvert.pas(240,5) Error: Identifier not found "SDL_ModState"
UScreenEditConvert.pas(413,15) Error: Identifier not found "SDL_ModState"
UScreenEditConvert.pas(1049,32) Warning: Local variable "tm" does not seem to be initialized
UScreenEditConvert.pas(1049,35) Warning: Local variable "ts" does not seem to be initialized
UScreenEditConvert.pas(1144,35) Warning: Local variable "TrackPos" does not seem to be initialized
UScreenEditConvert.pas(1281) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/local/bin/ppcx64 returned an error exitcode
make[1]: *** [../game/ultrastardx] Error 1
make: *** [all] Error 2

### Expected behaviour

Tell us what should actually happen

### Steps to reproduce

autogen.sh works
configure works
make macosx-standalone-app produces the error above

### Details

Provide some additional information:

latest clone of USDX
iMac Mid 2011
latest OS (10.13.3) all updates installed
latest Xcode 
latest upgrade of home-brew

**Comment by basisbit** [comment]
worked fine on travis-ci: https://travis-ci.org/UltraStar-Deluxe/USDX/jobs/332958816
Thus I guess there are some local changes which break your build. Try `git reset --hard` and `git clean -d -x -f`

**Comment by s09bQ5** [comment]
Please try again with the current master branch

**Comment by about-design** [comment]
I've tried the new master, but now I have a new error.

make[1]: *** No rule to make target `/usr/local/opt/jack/lib/libjack.0.dylib', needed by `UltraStarDeluxe.app/Contents/MacOS/libjack.0.dylib'.  Stop.
make: *** [macosx-standalone-app] Error 2

**Comment by basisbit** [comment]
this most likely is caused by a dependency of portaudio missing in the portaudio package. Please try again after installing libjack-jackd2-dev (or similar)

**Comment by s09bQ5** [comment]
Homebrew has a new bottle for ffmpeg 2.8 that no longer depends on jack.
