### ISSUE TITLE
[README] modification request

### ISSUE THREAD

**Issue by groms** [UltraStar-Deluxe/USDX#356]
### Actual behaviour

There is an issue when compiling on Mac OSX with ffmpeg and brew.
This issue prevents USDX to compile.

### Expected behaviour

USDX compilation on Mac OSX

### Steps to reproduce

I found a workaround that would allow compiling on Mac OSX.

> install Homebrew : /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> install freepascal : brew install fpc
> install needed libraries : brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf libav portaudio binutils sqlite freetype libpng pcre lua libtiff autoconf autogen automake ffmpeg@2.8
> to enable faac in ffmpeg : brew reinstall ffmpeg@2.8 --with-faac
> check for ffmpeg@2.8 version (i.e. : 2.8.13_2)
> cd /usr/local/Cellar/
> rm -Rf ffmpeg
> cp -R ffmpeg@2.8 ffmpeg
> brew switch ffmpeg 2.8.13_2
> cd /usr/local/opt/
> rm ffmpeg@2.8
> ln -s ../Cellar/ffmpeg/2.8.13_2 ffmpeg@2.8
> clone repo (checkout latest version) : git clone https://github.com/UltraStar-Deluxe/USDX
	-> the directory ./USDX is created
> ./autogen.sh
> ./configure
> make macosx-standalone-app

### Details

Provide some additional information:

- USDX version: latest (1.3)
- Operating System + version: Mac OSX Sierra 10.12.6

**Comment by s09bQ5** [comment]
Can you be a bit less vague about the problem you are trying to fix?

**Comment by groms** [comment]
The problem is the "./configure.sh" script uses, by default, ffmpeg@3.4 and the only way to force using ffmeg@2.8 was to do as described in my first post.

**Comment by s09bQ5** [comment]
And what problems do you have when it uses ffmpeg@3.4?

**Comment by groms** [comment]
The lib files are not compatible with MacOSX. I don't have the error logs anymore but I now that I succeeded only with ffmpeg v2.8

**Comment by bohning** [comment]
I don't have these problems on MacOS 10.13.3 (or any other previous version I have worked with).

**Comment by ePirat** [comment]
> The lib files are not compatible with MacOSX

Thats not the case, as far as I know. There is no issue with ffmpeg 3 on macOS, I tried it and it works fine. If you are encountering problems installing ffmpeg 3 from brew, please report to homebrew and not here :)
