### ISSUE TITLE
Most of song covers do not show up

### ISSUE THREAD

**Issue by redflash13** [UltraStar-Deluxe/USDX#357]
**Please, do not create duplicate issues**

### Actual behaviour

Most covers do not show up in the roulette view, Instead, the default USDX cover placeholder is visible.

### Steps to reproduce

I figured out that the issue seems to be introduced by commit 7f24cb9c198f1ae072fec460e513c42c7f713f4f. 
On 5409908e33d2a008e021ba9b06c31c834d625222 it works.

Here is the log file (test with one track in the song folder that has the issue)

UltraStar Deluxe - www.usdx.eu V 2017.8.0 dev Build Error Log
Date: 17-2-18 Time: 22:54:47
-------------------
STATUS: Load Language [Initialization]
STATUS: Load Default Language English [Initialization]
STATUS: Loading Skin List [Initialization]
STATUS: Loading Theme List [Initialization]
STATUS: Searching for Theme : /usr/local/share/ultrastardx/themes/*.ini [Theme.LoadList]
STATUS: Found Theme: Deluxe.ini [Theme.LoadList]
STATUS: Found Theme: Modern.ini [Theme.LoadList]
STATUS: Website-Manager [Initialization]
STATUS: DataBase System [Initialization]
STATUS: Initializing database: "/home/ultrastardx/.ultrastardx/Ultrastar.db" [TDataBaseSystem.Init]
STATUS: Load Ini [Initialization]
STATUS: GamePath : /home/ultrastardx/.ultrastardx/ []
STATUS: Using config : /home/ultrastardx/.ultrastardx/config.ini [Ini]
STATUS: Found Video Mode: 1920x1080 [Video]
STATUS: Found resolutions: 1 [Video]
STATUS: Load Help [Initialization]
STATUS: Write Ini [Initialization]
STATUS: Loading: /usr/local/share/ultrastardx/themes/Deluxe.ini [TTheme.LoadTheme]
ERROR:  no texture type for LoadingStaticAnimation found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SongRouletteStaticCat found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxStaticActualSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongMenuTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressSong found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressWeb found. [TTheme.ThemeLoadStatic]
STATUS: Opened audio device [TAudioPlayback_SDL.InitializeAudioPlaybackEngine]
STATUS: InputDevice "Wireless Mic #121077315: USB Audio (hw:0,0)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "USBMIC Serial# 031355342: Audio (hw:1,0)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "HDA Intel PCH: ALC887-VD Analog (hw:2,0)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "HDA Intel PCH: ALC887-VD Alt Analog (hw:2,2)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "ESI Juli@: ICE1724 (hw:4,0)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "ESI Juli@: ICE1724 IEC958 (hw:4,1)"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "sysdefault"@2x48000Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "spdif"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "pulse"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: InputDevice "default"@2x44100Hz (0.1sec) [Portaudio.EnumDevices]
STATUS: #Input-Devices: 10 [Portaudio]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/Common start.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/Common back.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/menu swoosh.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/select music change music 50.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/option change col.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/rimshot022b.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/Applause.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/usr/local/share/ultrastardx/sounds/background track.mp3" [TAudioPlaybackBase.OpenDecodeStream]
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config fullscreen resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Fullscreen [SDL_SetVideoMode]
INFO:   OpenGL vendor nouveau [UGraphic.InitializeScreen]
INFO:   OpenGL renderer NV117 [UGraphic.InitializeScreen]
INFO:   OpenGL version 3.0 Mesa 17.2.8 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor nouveau [TTextureUnit.Create]
INFO:   OpenGL renderer NV117 [TTextureUnit.Create]
INFO:   OpenGL version 3.0 Mesa 17.2.8 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]
STATUS: TDisplay.Create [UGraphic.Initialize3D]
STATUS: Loading Font Textures [UGraphic.Initialize3D]
STATUS: Building Fonts [LoadTextures]
STATUS: Loading Loading Screen [UGraphic.Initialize3D]
STATUS: Loading and checking songs [UGraphic.Initialize3D]
STATUS: Creating Category Covers Array [Initialization]
STATUS: Creating Avatars Cache [Initialization]
STATUS: Creating Song Array [Initialization]
STATUS: Searching For Songs [SongList]
STATUS: Search Complete [SongList]
STATUS: Creating 2nd Song Array [Initialization]
STATUS:  Loading Textures [UGraphic.Initialize3D]
STATUS: Loading Textures [LoadTextures]
STATUS: Loading Textures - A [LoadTextures]
STATUS: Loading Textures - B [LoadTextures]
STATUS: Loading Textures - C [LoadTextures]
STATUS: Loading Textures - Done [LoadTextures]
STATUS:  Loading Screens [UGraphic.Initialize3D]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
STATUS: Finish [Initialize3D]
STATUS: Playlist Manager [Initialization]
STATUS: Effect Manager [Initialization]
STATUS:   # Name                           Version  Status     Paused  #Errors [LuaCore Plugins]
STATUS:   0 party mode: blind              1.00     running    False   0      [LuaCore Plugins]
STATUS:   1 party mode: 5000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:   2 party mode: 2000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   3 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS:   4 party mode: holdthelineblind   0.6      running    False   0      [LuaCore Plugins]
STATUS:   5 party mode: blindLyrics        1.00     running    False   0      [LuaCore Plugins]
STATUS:   6 party mode: deaf               1.00     running    False   0      [LuaCore Plugins]
STATUS:   7 party mode: holdtheline        0.6      running    False   0      [LuaCore Plugins]
STATUS:   8 party mode: shortsong          1.00     running    False   0      [LuaCore Plugins]
STATUS:   9 party mode: teamduel           1.00     running    False   0      [LuaCore Plugins]
STATUS:  10 party mode: hardcore           1.00     running    False   0      [LuaCore Plugins]
STATUS:  11 party mode: blindTotal         1.00     running    False   0      [LuaCore Plugins]
STATUS:  12 party mode: 500blind           1.00     running    False   0      [LuaCore Plugins]
STATUS:  13 party mode: 1000blind          1.00     running    False   0      [LuaCore Plugins]
STATUS:  14 party mode: duel               1.00     running    False   0      [LuaCore Plugins]
STATUS:  15 party mode: 2000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:  16 party mode: 7000points         1.00     running    False   0      [LuaCore Plugins]
STATUS:  17 party mode: 5000pointsblind    1.00     running    False   0      [LuaCore Plugins]
STATUS: Main Loop [Initialization]
STATUS: Open Wireless Mic #121077315: USB Audio (hw:0,0) [Portaudio]
STATUS: Latency of Wireless Mic #121077315: USB Audio (hw:0,0): 0.0348299319727891 [Portaudio]
ERROR:  no texture type for ScorePlayer1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture1 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScorePlayer2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScorePlayer3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture3 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScorePlayer4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture4 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScorePlayer5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture5 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScorePlayer6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreStaticRatingPicture6 found. [TTheme.ThemeLoadStatic]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" [LoadImage]
ERROR:  Could not load texture: "/usr/local/share/ultrastardx/themes/Deluxe/[rap]notesRight.png" with type "Colorized" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
INFO:   VideoStreamIndex : -1 [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 30fps [TVideoPlayback_ffmpeg.Open]
STATUS: Closing DB file [Finalization]
INFO:   TDataBaseSystem.Free [TDataBaseSystem.Destroy]
STATUS: Finalize Media [Finalization]
STATUS: Uninitialize 3D [Finalization]
STATUS: Kill Fonts [UnloadFontTextures]
STATUS: Finalize SDL [Finalization]
STATUS: Finalize Log [Finalization]

### Details

Provide some additional information:

- USDX version: 7f24cb9c198f1ae072fec460e513c42c7f713f4f up to latest
- Operating System + version: Ubuntu 17.10

**Comment by bohning** [comment]
@redflash13 Should be fixed by 9d190774c3bfe8da9615212fc514b241c22728f1. Please try again with current master and report back if it is not fixed.

**Comment by redflash13** [comment]
great! works again. Thank you very much!

**Comment by bohning** [comment]
Am I correct in the assumption that your cover files contain '[CO]' in their name, but are not explicitly referenced in the text file?

**Comment by redflash13** [comment]
I estimate that about 90% of the songs didn't have a cover displayed. Some of my songs still worked, but I didn't really saw a rule why one is working and the other not. One not working example was:
Wincent Weiss - Frische Luft[CO].jpg
while the txt file referencing it by "#COVER:Wincent Weiss - Frische Luft[CO].jpg"
..so, the assignment looks ok to me.

An example that works in any case is:
Three Doors Down - Here Without You [CO].jpg and Three Doors Down - Here Without You [BG].jpg
while the txt file is referencing by:
"#COVER:Three Doors Down - Here Without You [CO].jpg" and "#BACKGROUND:Three Doors Down - Here Without You [BG].jpg"

Following your solution, I would guess, the issue was, that in a not working case, there is no background image in the song folder and because of the C&P mistake, the cover got overwritten by a not existing [BG].jpg ... somehow like that.
