### ISSUE TITLE
Sounds missing

### ISSUE THREAD

**Issue by pkerling** [UltraStar-Deluxe/USDX#36]
I just compiled the latest USDX version from git to check out the new features, but it does not seem to have any sounds in the UI.
Sound is generally working (I can hear the songs), so it's not an output problem.
I noticed that it will play some sounds if they are copied back into the game/sounds folder from an older ultrastar version.

**Comment by basisbit** [comment]
could this maybe be caused by already existing configuration / themes from previous installs?
Maybe cleaning up the ultrastardx folder in the users folder and then compiling  + running it again would be a good check. audio files are not missing for windows target. thus it should also not be missing for other targets.

**Comment by pkerling** [comment]
I have tried to reset everything to a clean state beforehand (remove ~/.ultrastardx etc.).
But the point is: the sounds are just not there in $PREFIX/share/ultrastardx/sounds.
Where are they in the source tree? I assumed that they should be here: https://github.com/UltraStar-Deluxe/USDX/tree/master/game/sounds but the directory is empty.

**Comment by basisbit** [comment]
indeed... .gitgnore had an entry for *.mp3. I'll fix that now and push the missing mp3 files.
Also, could you please create a pull request against this repository regarding your linux-lua-detection bugfix?

**Comment by pkerling** [comment]
Done. Seems I trusted the big shiny "Create pull request" button a bit too much and didn't check the repository... Nice that you saw the PR anyway, thanks :cat:

**Comment by basisbit** [comment]
thanks for the bugfix! Also, the sound files have been readded in commit c83c379
