### ISSUE TITLE
[Bug] Some scripts are only supported in the editor, not in the sing screen

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#363]
Some scripts (sample screenshots: Hindi) are correctly shown in the editor (main lyrics, but not in the on-note lyrics):
<img width="1680" alt="bildschirmfoto 2018-03-03 um 23 29 40" src="https://user-images.githubusercontent.com/1497707/36940001-6abd4aa8-1f3b-11e8-8e99-ce2335f27dec.png">
However, they are not correctly displayed in the singscreen:
<img width="1680" alt="bildschirmfoto 2018-03-03 um 23 35 32" src="https://user-images.githubusercontent.com/1497707/36940035-af666126-1f3b-11e8-82cd-d4c809e8ddef.png">

So in principle, these scripts are supported by the fonts shipping with USDX, but somehow they are not correctly displayed everywhere.

- USDX version: latest HEAD
- Operating System + version: MacOS X 10.13.3

**Comment by bohning** [comment]
Not directly related, but maybe it is worthwhile investigating if USDX could switch to Google Noto as "one font to rule the them all" - all languages, all scripts.

**Comment by basisbit** [comment]
@bohning sounds like a good idea and the noto license also looks good. As usual, try and go ahead if you want to ;-)

**Comment by bohning** [comment]
@basisbit: I already did, check [this](https://github.com/UltraStar-Deluxe/USDX/compare/master...bohning:fontsRevisited) out. Still has some minor issues, but seems to work quite well so far.

**Comment by bohning** [comment]
I just created a pull request and am looking forward to your remarks. It currently includes basically all fonts that are available in the previously used fonts, so some of most of them can maybe removed or be provided as a separate language pack (especially CJK because of the size).

And yes, I do like tofu as well (as a vegan), but not in UltraStar ;-)

**Comment by bohning** [comment]
See PR #386.

**Comment by s09bQ5** [comment]
Is this still an issue?

**Comment by bohning** [comment]
I believe it can be closed after my PR #386 was successfully merged a while back.
