### ISSUE TITLE
Ultrastar doesn't receive microphone signal since april2018 windows 10 update

### ISSUE THREAD

**Issue by alexchvt** [UltraStar-Deluxe/USDX#367]
### Actual behaviour
Record devices display in settings but impossible to get any signal
since the april update.

### Expected behaviour
Signal should come from microphone and meter should show input level

### Details
USDX version: 2018.04.15 + 1.3.2 beta  
Windows 10 1803
Tested with various mic (singstar usb, jack port, soundcard mic)

**Comment by basisbit** [comment]
can not reproduce this issue on various systems. Please use the current stable from https://usdx.eu/downloads/ and try again. Also, check your windows recording device settings.

**Comment by alexchvt** [comment]
Issue resolved:
privacy settings were set after the update and one of them concern access authorisation for recording devices in applications, it was indeed disabled.
