### ISSUE TITLE
ERangeError exception on song list screen

### ISSUE THREAD

**Issue by Stefan1200-de** [UltraStar-Deluxe/USDX#371]
### Actual behaviour

In the song list pressing ALT key followed by letters I get an ERangeError exception.
![image](https://user-images.githubusercontent.com/15168351/41501535-860a5414-71a6-11e8-81fb-8ce2ebf887e6.png)
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/2108447/Error.log)

### Expected behaviour

Jumping to the pressed letter in the list.

### Steps to reproduce

In the song list pressing ALT key followed by letters, in my case the letter W is enough.

### Details

Provide some additional information:

- USDX version: V 2017.8.0
- Operating System + version: Windows 10 1803 64 bit

**Comment by ChaosMarc** [comment]
This only happens with "List" as a display style as far as I can say
