### ISSUE TITLE
Raspberry Pi 3 - overheating as well as worse performance then to be expected/in the past

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [UltraStar-Deluxe/USDX#374]
### Actual behaviour

When running UltraStar Deluxe with an Raspberry Pi 3 on Raspian, the performance is pretty bad. In the menue I got like 1 FPS. In additon the Raspberry heats up too much to quickly.

Changing the GPU memory size does not make any difference. The CPU load checked via SSH from another PC seems to be prettty low so it has to be the GPU.

### Expected behaviour

Rpi3 should be able to handle USDX with a decent performance. In the past I was able to play songs without video with constant 60 FPS and with 720p video with 40-60 FPS. Now even the menue is not working.

### Steps to reproduce

Compile USDX on raspian like descriped in the Wiki. The only additional dependency needed seems to be "automake".

### Details

Provide some additional information:

- USDX version: Latest git version as of 2018-07-05
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/2167321/Error.log)

commit 114ff0c11e8f2c415404e75db213f97a744f487b
Merge: 5869467 47cbee8

- Operating System + version: Raspian Debian Stretch 9

Error.log is attached.

**Comment by s09bQ5** [comment]
You are using the llvmpipe OpenGL software renderer. Are you sure you got 40 FPS with that driver?

**Comment by basisbit** [comment]
> STATUS: Set Video Mode...   Fullscreen [SDL_SetVideoMode]
> INFO:   OpenGL vendor VMware, Inc. [UGraphic.InitializeScreen]
> INFO:   OpenGL renderer Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits) [UGraphic.InitializeScreen]
> INFO:   OpenGL version 3.0 Mesa 13.0.6 [UGraphic.InitializeScreen]
> INFO:   OpenGL vendor VMware, Inc. [TTextureUnit.Create]
> INFO:   OpenGL renderer Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits) [TTextureUnit.Create]
> INFO:   OpenGL version 3.0 Mesa 13.0.6 [TTextureUnit.Create]
> INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]

yes, definitely not running with OpenGL hardware acceleration. Check your systems settings. Not USDX related, sorry.
