### ISSUE TITLE
Raspbian Ultrastar No Game Audio

### ISSUE THREAD

**Issue by gltich** [UltraStar-Deluxe/USDX#377]
Have not found a solution

### There is no audio (background music, mp3 playback)  

in Raspi-Config GL Legacy is real choppy and too slow
                         GL (Fake KMS) works fast. Video stutters and renders in spots. Audio works perfect. 
                                                 Microphones are on but have bad static and unable to play 
                         GL (Full KMS) Runs great. Video is good. Microphones work and can play but...
                                                There Is No Audio

### I don't have much experience with Raspbian so go easy
I think it's a quick conf.ini file or something I can easily edit with wordpad

### Steps to reproduce were from this site. it's in spanish

https://www.fororaspberry.es/viewtopic.php?t=1043

### Details

Provide some additional information:

- USDX version: UltraStar Deluxe 2017.80 version 1.3.5
- Operating System + version: Raspbian

**Comment by basisbit** [comment]
Hi,
based on your description, this is not a bug in USDX but instead only an issue of that linux system setup. Please try to get help from some raspbian forum or the mentioned spanish forum. My first guess is that you have to tell your audio system (alsa?) where to send the audio.
