### ISSUE TITLE
[Feature Request] Record and apply note pitches in editor

### ISSUE THREAD

**Issue by natowi** [UltraStar-Deluxe/USDX#378]
The pitch recognition of USDX is quite good, so why not use it to simplify the content creation with it?
It would be nice to have a sing-mode to record the pitch and length of the notes to Midi/ABC or add pitch to existing tap/lyrics from Ultrastar Creator.
They could then be optimized in Yass.
It would reduce the time to create the correct pitch and length of the notes and the overall creation time of songs.

**Comment by basisbit** [comment]
please provide some more details of the workflow and the features you suggest. Also, how should the syllable lengths be detected?

**Comment by natowi** [comment]
Depending on the accuracy of the pitch and length detection engine I see two variants.

Variant A:
1) Syllabification and "tap" synchronisation (length) in UltrastarCreator -> time synced lyrics without pitch
2) Start USDX -> Tools -> Editor -> "PitchSync" -> load song-folder with "timing-only" lyrics
3) Sync timed lyrics to pitch using the USDX pitch-detection used in Sing-Mode
4) Pitch can be sung or maybe better hummed or whistled. The "flat" notes are adjusted according to the input pitch. 

Variant B:
In addition to Variant A the lengths of the hummed/whistled/sung tones are recorded as well.
The resulting timed and pitched lyric file could then be synced with the syllabification text.

I think Variant A would be a good start and quite helpful.

I already experimented with AmazingMIDI, which delivers good results for recordings with low noise,
but it is wav input only, does not work in real time and USDX seems to have better noise filters and works well with humming/whistling.

**Comment by basisbit** [comment]
Thanks for clarification! This looks like two different feature requests (variant A and B). In this issue we should focus only on variant A, so we can discuss and track this properly. Regarding variant B, please create another issue for that feature request.

**Comment by natowi** [comment]
Thank you for the quick reply. I created #379 for variant B.
I also prefer starting with variant A, since the time sync in Yass is easy to use and fast enough.

**Comment by Tauvic** [comment]
Great idea, I'm working on creating Thai karaoke songs. I'm try out Reaper, and some tool to extract singing notes. In Reaper there is ReaTune. I'm also looking at musical science tools. Tony is good https://code.soundsoftware.ac.uk/projects/tony. Also Sonic Visualizer. But tryingto automate the workflow

**Comment by natowi** [comment]
@Tauvic I can recommend you https://github.com/deezer/spleeter , it does an amazing job separating vocals and accompaniment (you can test it in [Colab](https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb)). The clean vocal file can then be used for midi conversion / tone extraction.

**Comment by basisbit** [comment]
fyi, the [song editor in UltraStar Play](https://github.com/UltraStar-Deluxe/Play/wiki/Song-Editor) already supports recording pitches for songs. Also, there is this project for a tensorflow / AI based pitch detection which has better usable results than just using spleeter:  https://github.com/paradigmn/ultrastar_pitch

**Comment by natowi** [comment]
@basisbit Thank you for the references. I close this issue, as now - two years later, there are good tools available for this task.
