### ISSUE TITLE
FPC version not checked

### ISSUE THREAD

**Issue by pkerling** [UltraStar-Deluxe/USDX#38]
I first tried to build this with FPC 2.6.2, which gave me some weird errors. Everything worked with FPC 3.0 then, so I guess that 2.6.2 was just too old.
It would be great if the configure script could check the FPC version against the actual minimum requirement so you get an error message and know what's wrong instead of a failing compilation.

**Comment by basisbit** [comment]
you don't know by any chance how to do that and could implement the checking for fpc 3.0.0 or newer?

**Comment by pkerling** [comment]
I'll take a look, shouldn't be too complicated.
