### ISSUE TITLE
No Songs loaded

### ISSUE THREAD

**Issue by derzu** [UltraStar-Deluxe/USDX#393]
### Actual behavior

When I run the ultrastardx and try to Sing on the main menu. The message "No Songs loaded" is shown.

I put some mp4 songs files at the folder /usr/local/share/ultrastardx/songs/ , but they are not being loaded. I also tried using the "-Songpath" command line parameter but still no songs loaded.

My songs (videos) file name are just a number of 5 digits folwed by .mp4. Ex.:  01130.mp4

How can I set the songs path? Is mp4 an accepted format?

### Expected behavior

I expected to be able to select my songs.

### Steps to reproduce

1. Open the ultrastardx
2. Select Sing on the main menu

### Details

- USDX version: 2017.8.0 dev build
- Operating System + version: Ubuntu 16.04

**Comment by s09bQ5** [comment]
Are you aware that you need text files listing the syllables of the songs with their pitch, time, and duration?

**Comment by derzu** [comment]
Hi @s09bQ5, 

My mp4 files already have the lyrics and timing, I downloaded from youtube. Does UltraStar works with this kind of file?

**Comment by basisbit** [comment]
UltraStar Deluxe is a sing-along karaoke game. So you will also need a microphone, and for each song you need a .txt file containing the lyrics data including syllable timings, lyrics and tone pitches.

See http://www.ultraguide.net/addingsongs.php for how to get started.

**Comment by naXa777** [comment]
@basisbit's link is a spam. it redirects to random locations.

**Comment by basisbit** [comment]
Its not spam, it is dead. That message was from 2018 and it worked back then. Feel free to use waybackmachine / archive.org to find the page from back then.

**Comment by basisbit** [comment]
Anyways, closing this issue because it is not a valid bug report or change/feature request.
