### ISSUE TITLE
Failed build configuration on Ubuntu 18.04, FPC

### ISSUE THREAD

**Issue by john-kloss** [UltraStar-Deluxe/USDX#394]
Configuration fails:

`
checking whether make sets $(MAKE)... yes  
checking whether ln -s works... yes  
checking for a thread-safe mkdir -p... /bin/mkdir -p  
checking for a BSD-compatible install... /usr/bin/install -c  
checking for a sed that does not truncate output... /bin/sed  
checking for grep that handles long lines and -e... /bin/grep  
checking build system type... x86_64-unknown-linux-gnu  
checking host system type... x86_64-unknown-linux-gnu  
checking for fpc... fpc  
checking for fpcmake... fpcmake  
checking version of fpc... [3.0.4]  
checking whether the Free Pascal Compiler works... yes  
checking whether the Free Pascal Compiler can link... no  
configure: error: installation or configuration problem: Cannot link with some standard libraries.  
`

### Steps to reproduce  
I downloaded the master branch and followed the build instructions

### Details

- USDX version: 2017.08.0 Stable
- Operating System + version: Ubuntu 18.04

### Things I've tried

- uninstalled and reinstalled fpc
- downloaded fpc source and built it manually
- ran one of the fpc examples without any problems

**Comment by s09bQ5** [comment]
Is there any useful output in config.log?

**Comment by john-kloss** [comment]
Yes there is:

configure:3270: checking whether the Free Pascal Compiler can link
Free Pascal Compiler version 3.0.4 [2017/10/03] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling conftest.pp
conftest.pp(1,19) Fatal: Can't find unit crt used by foo
Fatal: Compilation aborted
Error: /usr/local/bin/ppcx64 returned an error exitcode
configure:3297: result: no


But I don't quite get the problem.

**Comment by s09bQ5** [comment]
If ppcx64 is in /usr/local/bin, the configure script does not pick up the Free Pascal compiler installed with `apt-get install fpc`. You appear to have installed another Free Pascal compiler manually at some point that is broken.

**Comment by john-kloss** [comment]
Yes you're correct. I removed it now but the problem stays the same.

Error: /usr/bin/ppcx64 returned an error exitcode

That's the correct one isn't it?

**Comment by s09bQ5** [comment]
If you have a ~/.fpc.cfg, delete it.
If it still does not work, you need to fix the global /etc/fpc.cfg.
This configuration file points Free Pascal to the directory where GCC keeps its crt*.o files.

**Comment by john-kloss** [comment]
The deletion did it!
I'm stuck with #188 now though.
But thanks for helping :)
