### ISSUE TITLE
ffmpeg 4.1 support

### ISSUE THREAD

**Issue by kyrios123** [UltraStar-Deluxe/USDX#397]
### Actual behaviour

When building USDX against FFMPEG 4.1, I get the following messgae
```
src/lib/ffmpeg-4.0/avutil.pas(81,4) Error: User defined: Linked version of libavutil is not yet supported!
```

### Expected behaviour

Successful build

### Steps to reproduce

Simply build USDX against the latest version of ffmpeg

### Details

Provide some additional information:

- USDX version: 2017.8.0 + commit a955a9e8e041d324173b3cc683f4d118801d551f
- Operating System + version: Solus 3.9999 - x86_64 GNU/Linux 4.18.16

**I don't think any change is required for supporting ffmpeg 4.1, just adding it as a supported version should be enough**

CC: @brianch who's the great person who fixed #369 :smiley:

**Comment by brianch** [comment]
Thanks for reporting!

Yes, it should be enough to just bump the max versions there (which is what I did), from what I saw nothing was removed/changed in their API.
