### ISSUE TITLE
cover.db 4x size increase between 1.1 and 1.2 pre-alpha

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#4]
For the same Songs the "cover.db" file produced is much bigger for 1.2 pre-alpha compared to 1.1
Is this intended?

1.1 Release | 1.2 pre-alpha
--- | ---
24,9 MB (26.120.192 Bytes) | 104 MB (109.131.776 Bytes)

Songs >500

**Comment by basisbit** [comment]
with 1.3 pre-alpha this is now at eg. 313KB for 1052 Songs. I consider this issue fixed now.
