### ISSUE TITLE
Quick jump to a letter in the song selection screen

### ISSUE THREAD

**Issue by MairusuPawa** [UltraStar-Deluxe/USDX#42]
Hi there!

In order to be able to browse large libraries quicker without relying on search, it could be a good idea to allow the user to jump to a given letter instead of going through every single entry available.

For instance, on pressing PageDown, the user would move from Axxxx to Bxxxx then to Cxxxx etc (according to the current sorting, by artist name or song name). PadeUp would work the same but cycle backwards. On joypads, the left and right triggers would be used for such a function.

**Comment by basisbit** [comment]
please feel free to take a look at https://github.com/UltraStar-Deluxe/USDX/blob/master/README.md .
this is already implemented (not for joypads, but for keyboard):

|Keys | Action|
| :--- | :--- |
| [Alt] + [Letter] | jump to a artist with the first letter [Letter] |
| [Alt] + [Shift] + [Letter] | jump to a title with the first letter [Letter] |

does this answer your request?

**Comment by basisbit** [comment]
page down / up might be better for scrolling 5 songs right / left at a time

**Comment by MairusuPawa** [comment]
Yes indeed for keyboards

No for a ten-foot UI driven by more simplistic and compact human-friendly device :p

**Comment by basisbit** [comment]
as of 97c3fac you can now jump to the next / previous song where the artist has a different first letter. please check if that fulfills your feature request.
