### ISSUE TITLE
started over Steam i have no special characteres, just "?"

### ISSUE THREAD

**Issue by silelmot** [UltraStar-Deluxe/USDX#424]
Hello there,
i tried to run ultrastardx from steam directly for my little couch-gaming-solution.
unfortunately when started from steam there are no special characteres like è or Ö or even /
instead i have just question marks.
but started in linux directly it works flawlessly.
i tried in arch linux, ubuntu 16.04 and ubuntu 18.04
any idea what could create this conflict with steam?

i believe i did'nt had these problems a year ago when i tried to run ultrastardx over steamos the last time.

**Comment by s09bQ5** [comment]
What are your LANG, LC_CTYPE, and LC_ALL environment variables set to?

**Comment by s09bQ5** [comment]
@Ruedii Feel free to make a pull request that fixes the code.

**Comment by silelmot** [comment]
i just tried ultrastardx world party , which is a fork of 1.1 and this runs flawlessly regarding the utf8-issue (not in other terms). since it is a fork of version 1.1 i believe that  i don't remember it wrong, that i had ultrastardx running a year or more ago under steamos in an older version without errors.

**Comment by s09bQ5** [comment]
I wonder if something breaks on Windows if we do SetMultiByteConversionCodePage(CP_UTF8) at the start of the program.

**Comment by silelmot** [comment]
i have absolute no idea how this program works. where shall i put it to compile and test it?

**Comment by silelmot** [comment]
Great works now. Just cannot register some bands with "umlaut".

**Comment by basisbit** [comment]
regarding "Just cannot register some bands with "umlaut".", please open a new issue. The initial issue seems to be fixed and the issue creator confirmed that.
