### ISSUE TITLE
Problems with Unicode characters in song search

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#437]
### Actual behaviour
I finished converting my entire song collection from CP1252 to UTF8 encoding. One aesthetic benefit is that I can use a correct typographic apostrophe (’ – Mac: Alt+Shift+#, not to be confused with Alt+#) instead of the less correct typewriter apostrophe (' – Shift+#) – see [Wikipedia](https://en.wikipedia.org/wiki/Apostrophe) for details (in particular: »Both simplifications carried over to computer keyboards and the ASCII character set. However, although these are widely used due to their ubiquity and convenience, they are deprecated in contexts where proper typography is important.«). So on the one hand, I used [NameChanger](https://mrrsoftware.com/namechanger/) to change all filenames and [Sublime](https://www.sublimetext.com/) to replace all occurrences of the typewriter apostrophe in all text files of my song collection.

Now I am facing the problem that I can't type the typographic apostrophe in the song search popup (while I am able to produce other special characters):
<img width="1680" alt="bildschirmfoto 2019-01-07 um 21 19 25" src="https://user-images.githubusercontent.com/1497707/50792317-c89af800-12c4-11e9-8ee7-cce9da8dc9cc.png">
<img width="1680" alt="bildschirmfoto 2019-01-07 um 21 20 45" src="https://user-images.githubusercontent.com/1497707/50792331-dbadc800-12c4-11e9-9e83-60d1d49053c0.png">
<img width="632" alt="bildschirmfoto 2019-01-07 um 21 18 56" src="https://user-images.githubusercontent.com/1497707/50792375-03049500-12c5-11e9-9237-f4ad64f60ca7.png">

### Expected behaviour
Song search should support all characters producible by the keyboard.

### Details
- USDX version: latest master
- Operating System + version: macOS Mojave 10.14.1

**Comment by bohning** [comment]
Possibly somewhat related to #334.

**Comment by barbeque-squared** [comment]
This was probably fixed by #795
