### ISSUE TITLE
ASIO Support?

### ISSUE THREAD

**Issue by a3nima** [UltraStar-Deluxe/USDX#439]
I wonder if Ultrastar could have ASIO support for low-latency microphone playback. For me with the current latency the ingame microphone playback is unusable. I use the direct (hardware) monitoring feature of my external sound card (emu tracker pre) to have zero latency real time voice sound. 
but I would have compressor and reverb added to the voice of my singers, so I found some hardware units with that function, but that would require to use the ingame microphone playback function which I could not get to have low-latency so far, then I wondered if the program could probably use the ASIO support function within those external audio-cards drivers for low latency?

**Comment by basisbit** [comment]
the ingame audio playback is not really supported any more. Most audio device drivers support configuring direct microphone to speaker playback in hardware with low latency - please use that instead.

If any developer wants to spend time on this topic, fork the usdx project, change the code and if you are successful, please feel free to create a pull request (the usual github workflow). 😃
