### ISSUE TITLE
cant open the software

### ISSUE THREAD

**Issue by nil18e** [UltraStar-Deluxe/USDX#455]
**Please, do not create duplicate issues**

### Actual behaviour

Tell us what happens
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/2955399/Error.log)

### Expected behaviour

Tell us what should actually happen

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Open the ultrastardx.exe
2. Click on button X, then on the menu that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Details

Provide some additional information:

- USDX version:
- Operating System + version:

**Comment by basisbit** [comment]
I'd guess you are missing OpenGL support in your video card drivers. You could rename the opengl32_[something].dll to opengl32.dll for software video rendering or install the proper video card driver for your hardware. Anyways, don't expect any help when you create issues like this, not even taking the time to write any description / filling out the template.
