### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by J0R0W** [UltraStar-Deluxe/USDX#457]
### Actual behaviour
I downloaded USDX-Master and installed Lazarus und FPC in 32-Bit for Windows.

### Expected behaviour

If I want to compile the Game in Lazarus I get these Error in a Messagebox: "Programfile \USDX-master\game\ultrastardx.exe not found"

The lazarus Console writes: "Project: execute successfully"

### Details
FPS and Lazarus are not installed on default path.  I've installed them on "H:\FPS\", "H:\Lazarus\"

- USDX version: Downloaded version from 18.03.2019
- Operating System: Windows 10 64-Bit

**Comment by basisbit** [comment]
Closed this issue because it is not a bug in USDX, but rather a question of how to configure your IDE. Feel free to continue using this to discuss how to configure your lazarus install

**Comment by basisbit** [comment]
In Lazarus there is some place in the settings to configure the project settings. There you can also adjust the path for your build target and where to find the ultrastardx.exe to be able to use the "compile&run" button.
