### ISSUE TITLE
Configure fails

### ISSUE THREAD

**Issue by deuteragenie** [UltraStar-Deluxe/USDX#463]
Trying to build from master on Lubuntu.

Configure fails at line 3660. Syntax error near expected token 'sdl2,'

**Comment by s09bQ5** [comment]
Please upload your configure file. The configure file generated on my system has sdl2 for the first time on line 4654.
Also please paste the output of your `./autogen.sh` run.

**Comment by deuteragenie** [comment]
Will do.  This is a standard built from current master with no modifications to any configuration or other source files.

**Comment by deuteragenie** [comment]
Update.

After running autgen, configure and make worked OK.

Note that make install fails on live USB system owing to missing permissions on the target directory.  A clean .deb package would be really appreciated and good to raise the profile of this project.  Keep up the good work,

**Comment by s09bQ5** [comment]
The configure script is not part of the git repository. We removed it in 2017.
