### ISSUE TITLE
Error: Identifier not found "PReSampleContext"

### ISSUE THREAD

**Issue by batrique** [UltraStar-Deluxe/USDX#468]
When compiling USDX on Linux (I tried on Lubuntu 19 and Debian buster) I get the following error:  /USDX-master/SRC/media//UAudioConverter.pas(86,24) Error: Identifier not found "PReSampleContext".

**Comment by basisbit** [comment]
Please add more details and the full compile log. What version of ffmpeg,...

**Comment by basisbit** [comment]
@batrique by the way, your line numbers seem off. Please make sure you are using the current code from the master branch of this repository.

**Comment by batrique** [comment]
Yes you are right! My version was not updated! Everything works now! Thank you!
