### ISSUE TITLE
Misaligned/big song layout in widescreen

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#47]
The new cover roulette layout seems to be misaligned and too big compared to the original or how it would look better.

Original (v1.1.0):
<img src="https://cloud.githubusercontent.com/assets/6833006/16768136/489cd72a-4843-11e6-83e2-0ff488749278.png" height="180px"> <img src="https://cloud.githubusercontent.com/assets/6833006/16768138/4b8ac104-4843-11e6-9ff5-bbde3674a133.png" height="180px">

Dev/current (v1.3.0, 2aeda381ceba52560cd9d6b4879ebb34a71c6026):
<img src="https://cloud.githubusercontent.com/assets/6833006/16768007/85f7d36e-4842-11e6-9f05-a34ab8508b7d.jpg" height="180px"> <img src="https://cloud.githubusercontent.com/assets/6833006/16768011/88497370-4842-11e6-848b-7e5d065cbd35.jpg" height="180px">

**Comment by basisbit** [comment]
this is not a bug but instead an improvement I did some months ago to compensate for different screen resolution formats. On a 16:9 screen the stretching of the 800x600p theme doesn't doesn't look good any more. As cover images are always hight=width, the code was adjusted to only take the width value from the theme and to also use that for hight calculation. For the not-roulette views we might need some other solutions.

**Comment by RattleSN4K3** [comment]
The height adaption can break themes like the Temptation.
<img src="https://cloud.githubusercontent.com/assets/6833006/17463171/d16e9dea-5cc0-11e6-943f-bc82025a65cc.jpg" alt"" height="200px"> <img src="https://cloud.githubusercontent.com/assets/6833006/17463172/d4013e28-5cc0-11e6-8706-9fa063ece6c5.jpg" alt"" height="200px">

**Comment by basisbit** [comment]
In this case the themes should be adapted. Correctly resized covers look much better and smoother then the (on some screens) horribly stretched ones. Any suggestion for a better solution, which would also be easily usable for these other themes?

**Comment by RattleSN4K3** [comment]
The theme itself (and also based on the slot menu) should/could control how the resizing/aligning works. Instead of using the fixed width, the displayed themes above could be using a fixed height and the width, position and spacing changes accordingly.

That said, the amount of songs displayed at once could be adjusted dynamically based on the actual available size (width or height depending on the resizing method),

Also what I just noticed, aren't the previous songs (left to the selected) drawn with the original color and not with a grey tone?
