### ISSUE TITLE
Increase performance on network shares

### ISSUE THREAD

**Issue by Mitmischer** [UltraStar-Deluxe/USDX#470]
### Actual behaviour / expected behavior

If the music library is located on a network drive, starting UltraStar takes quite a bit of time with a moderately sized library (~ a minute on a library with a 2000 songs). I'm fine with that. However, songs cannot be sung without extreme stuttering which sadly makes the game unplayable.

### Steps to reproduce

The issue occurs for me on a ~2000 song library on a ssh share, mounted by Swish (a sshfs dropin for Windows).

### Details

Maybe the fix is as simple as loading the music file into memory completely? The throughput of my NAS is good enough, but latency is obviously an issue.
For the long time it takes for startup, maybe we could create an index on the first start to speed up subsequent starts? Both measures shouldn't impact performance for libraries on hard drives.

Provide some additional information:

- USDX version: 1.3.5
- Operating System + version: Windows 10 on USDX, ubuntu 18.04 on the server providing the ssh share.

**Comment by Mitmischer** [comment]
I should add that USDX running on Linux has no such problems (although startup time is still huge) :)

**Comment by basisbit** [comment]
sorry, but that is not a bug in USDX, but rather that is missing cachng in your filesystem driver (that sshfs dropin)

**Comment by basisbit** [comment]
caching all of the file at start is not desirable because that would cause problems for big files and it would also increase memory usage.

**Comment by chrisheib** [comment]
But caching a single song on start of song should be doable, should'nt it? Would solve @Mitmischer s problem at least. I guess I could take a look at it tomorrow, but I guess it should be configurable, because it would slightly slow USDX down in environments where the stream from fs works as expected.

**Comment by s09bQ5** [comment]
I was about to say that you should try to increase `MAX_AUDIOQ_SIZE` in src/media/UAudioDecoder_FFmpeg.pas, but then I realized that this is a Windows problem where FFmpeg isn't used for audio decoding. What was the reason, again, for using BASS on Windows?

**Comment by basisbit** [comment]
I don't know. Feel free to create a pull request to switch to portaudio. Definitely want such a change to be tested for a few weeks first.
