### ISSUE TITLE
Not possible to disable music select beep sound

### ISSUE THREAD

**Issue by suiluj** [UltraStar-Deluxe/USDX#471]
**Please, do not create duplicate issues**

### Actual behaviour

Every time you move to the next song at the song selection menu you here a beep sound.
It is the following sound file:
```
game/sounds/select music change music 50.mp3
```

### Expected behaviour

I would like to disable this sound because it is to loud and when i am scrolling fast through my song collection it is played everytime which is annoying.  

A disable option would be the best.

### Steps to reproduce

This is the normal behaviour.

### Details

Provide some additional information:

- USDX version: compiled from source
- Operating System + version: macOS Sierra

I compiled the app from source for mac and already tried lowering the volume of the sound file to complete silence in audacity before compiling. For some reason it is playing at the same volume nevertheless.

**Comment by dgruss** [comment]
Quickfix: You can remove/rename sound files you don't want to play.

**Comment by suiluj** [comment]
@dgruss do you mean before compiling?

i tried it but it did not work for some reason. (it tried both: deleting the audio file in the compiled app package and before compiling.)

now i cannot compile anymore because i updated my notebook to macOS Catalina and i cannot install all needed libraries for compiling because of compatibility issues with the new operating system.

**Comment by dgruss** [comment]
No, in installed version, in the sounds folder.

**Comment by suiluj** [comment]
well as i said i tried that (i am on a mac so i right clicked the app and choose "show package contents")

then i deleted the file:

```
select music change music 50.mp3
```

But when i start UltraStar Deluxe i still here the beep when scrolling through the song list.

Did you try this on a Mac yourself?

**Comment by dgruss** [comment]
Works on Linux and Windows.

**Comment by suiluj** [comment]
okay strange.

**Comment by suiluj** [comment]
ah i found the correct location for renaming/deleting the beep sound file on a mac:

```
<userhomefolder>/Library/Application Support/UltraStarDeluxe1.3/sounds
```

now the annoying beep is gone :)
