### ISSUE TITLE
[Question] All Songs listed in the DB, like Vocaluxe.

### ISSUE THREAD

**Issue by ZePhyr1987** [UltraStar-Deluxe/USDX#472]
Is it possible to get a full Song list entry in the DB, like in Vocaluxe?
I  would need it for my Online Song list.

With Ultrastar DB:
http://www.karma-biss.de/USDBLK2015_2_us/
With Vocaluxe DB:
http://www.karma-biss.de/USDBLK2015_1/

Feel free to use, modify or even upgrade it to a higher PHP version. ;)
http://www.karma-biss.de/usdblk.rar

**Comment by basisbit** [comment]
You might want to take a look at the sqlite database which UltraStar Deluxe creates while loading. Afaik it should have a table of all the songs that were scanned. I do not know what you mean by "like in Vocaluxe". Please feel free to add screenshots or descriptions to this thread here.

**Comment by ZePhyr1987** [comment]
i see. my php script for UltraStar only lists songs with highscores. Sorry didn't say anything. ;)
