### ISSUE TITLE
ffmpeg-4.2 support

### ISSUE THREAD

**Issue by SoundHunter** [UltraStar-Deluxe/USDX#474]
### Actual behaviour

Building USDX against ffmpeg-4.2 on Archlinux with the AUR package (https://aur.archlinux.org/packages/ultrastardx-git) fails:

USDX/src/lib/ffmpeg-4.0/avutil.pas(81,4) Error: User defined: Linked version of libavutil is not yet supported!

### Expected behaviour

Successful build

### Steps to reproduce

Build USDX against the latest version of ffmpeg (currently ffmpeg-4.2 on Archlinux).

### Details

Provide some additional information:

- USDX version: git master branch, commit: 8d9b3e3
- Operating System + version: Arch Linux x86_64 Kernel 5.2.9-arch1-1-ARCH

**Comment by luto** [comment]
@SoundHunter please check if [#477](https://github.com/UltraStar-Deluxe/USDX/pull/477/files) works for you and let us know! thanks.

**Comment by SoundHunter** [comment]
Hey @luto , #477 compiles without errors and the game works as expected. Thank you so much!
