### ISSUE TITLE
Webcam not working in linux 

### ISSUE THREAD

**Issue by batrique** [UltraStar-Deluxe/USDX#476]
The webcam feature does not seem to work in Linux. When I try to use the build-in webcam on my laptop the game says "No Webcam Found!". I also tried with a USB webcam and got the same result. The usb webcam is detected by the game and can be used as a microphone. The two webcams that I tried work in other programs without issue. Maybe it is a problem with OpenCV?

- USDX version: Latest
- Pop-Os 19.4

![Capture d’écran de 2019-08-26 23-56-06](https://user-images.githubusercontent.com/48631074/63740262-49136680-c85e-11e9-94c0-af7522e98c2c.png)

[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/3544221/Error.log)

**Comment by s09bQ5** [comment]
Please try again with current master.
The symbols for accessing cameras have been moved to a different OpenCV module.

In my Pop!_OS VM USDX can now capture frames, but fails to create an OpenGL texture (SIGSEGV in swrast_dri that is gracefully caught and hidden by Free Pascal). I hope it works on real hardware.

**Comment by s09bQ5** [comment]
No need to try again. It won't work. The crash in swrast_dri happens because the IplImage structure is no longer packed and needs 4 bytes padding between imageSize and imageData on 64 bit architectures. I need to work out how to detect this. Maybe we should switch to cvGetRawData.

**Comment by s09bQ5** [comment]
@basisbit, camera support is something inherited from World Party, isn't it? So we don't know who wrote those OpenCV units and we don't know why that person chose to mark the IplImage record as packed?

Am I right that nobody has ever built USDX for 64 bit Windows and reported that cameras work?
In that case I would simply remove the `packed` word from that record.

**Comment by basisbit** [comment]
afaik, camera support initially started as a patch file submitted but not merged to usdx on sourceforge, then was integrated an further implemented by the usdx world party fork. When these forkes were merged, I only fixed the most basic bugs and did some refactoring.
Builds targeting Winndows so far are always 32bit/x86 builds for compatiblity reasons.

**Comment by s09bQ5** [comment]
Don't be so impatient. I was at work earning money for 10 hours and will now continue fixing your problem. You could have saved yourself all that work taking pictures by comparing the time of the head commit on the master branch with my messages in this discussion.

**Comment by s09bQ5** [comment]
Should be fixed now

**Comment by s09bQ5** [comment]
@batrique, did you already have time to test it? Can we close this issue?

**Comment by luto** [comment]
@s09bQ5 the current master lets me choose between webcam 1 and 0, both of which yield "No webcam found!" when I click "Enable Preview". There is no crash, system message, freeze or console output in that case.

Sorry that I cannot be of more help. I'm not a USDX user and just came across this issue randomly, while looking at another one ;)

**Comment by batrique** [comment]
@s09bQ5 Working! Sorry if I looked impatient. It was not my intention. I wanted to provide as much information as possible to help you. Thank you for your awesome work!

**Comment by s09bQ5** [comment]
@luto, there is only one error message for all problems that could prevent us from accessing the camera. Do you have the OpenCV development package installed? Is your user allowed to open the /dev/video* devices? USDX will always let you to select between webcam 0 and 1, even if there are no or more cameras connected.

**Comment by s09bQ5** [comment]
Since batrique's problem is resolved, I have created a new issue for OpenCV 4. But if luto is having problems with OpenCV 3 we can of course continue to discuss it here.

**Comment by luto** [comment]
If batrique's setup works fine now, we can close this.
