### ISSUE TITLE
Game crashes 10 seconds into any song

### ISSUE THREAD

**Issue by Teafox56a** [UltraStar-Deluxe/USDX#480]
Actual behaviour

After launching Ultrastar and playing any song for about 10 seconds the app closes without any notifications or error reports.

### Details

[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/3563997/Error.log)

- USDX version: 2017.8.0 Stable
- Operating System + version: Windows 10 Home version 1903

**Comment by s09bQ5** [comment]
You have to help us a little. We can't diagnose a problem with that little amount of information.
 - Does it really always crash at exactly 10 seconds?
 - Is there any song where it crashes after you have sung a few notes?
 - Does it crash in songs without video?
 - Does it crash in the song selection while the preview is running?
 - Does it crash in the jukebox?
 - Does it crash in the options screen where you assign microphones to players?
 - Did you try different screen resolutions?
 - Did it work in the past on this computer?

**Comment by basisbit** [comment]
I guess that either your microphones are set to some measureing-rate above 48000Hz (you can change that in the windows audio recording devices settings -> Advanced) or you are using some bluetooth speaker which has a microphone integrated that turns off while the bluetooth speakers are being used

**Comment by basisbit** [comment]
closing this because of no response from issue author and we can't reproduce the problem.
