### ISSUE TITLE
Make looping videos.

### ISSUE THREAD

**Issue by vigliensoni** [UltraStar-Deluxe/USDX#486]
Hi Nice People,

I use USDX with very short video loops instead of the original videos. Long-time ago, the videos looped automatically but now they aren't looped when they reach the end. As a result, I end up with a still image for the rest of the song as soon as I get to the end of the loop.

I am new to the USDX codebase and so could you please point me to the controller or pieces of code that I need to take a look so that I can fix this and make a pull request?

Thank you.

**Comment by s09bQ5** [comment]
It does not look like looping the video during a song was intended behavior.
Try fCurrentVideo.Loop := true in TScreenSingController.LoadNextSong.

If your video is *very* short, you might be interested in porting patch 2 from https://sourceforge.net/p/ultrastardx/patches/53/ .

**Comment by basisbit** [comment]
please use some video editing software to cut some video files as desired and save them in the songs folder. We'd like to mitigate feature creep and thus do not include every feature request into the game. Sorry.
