### ISSUE TITLE
LLVM / LTO

### ISSUE THREAD

**Issue by deuteragenie** [UltraStar-Deluxe/USDX#487]
Looks like FPC supports LLVM as a backend and LTO.

See here: https://wiki.freepascal.org/LLVM#Build_FPC_with_LLVM_support

Potential 15%-20% speed gain maybe ?

**Comment by s09bQ5** [comment]
So... what exactly would you like us to do?

**Comment by basisbit** [comment]
what advantage would LLVM bring? I doubt there would be measurable speed changes for running the game at all. The game needs very little CPU cycles. Most of the time is just used for reading files from slow disks, waiting for library calls to finish, ffmpeg to calculate data or OpenGL doing stuff. There would be no change for these by adding LLVM, besides adding a huge dependency and breaking support for older systems.
Please convince us by explaining what improvements using FPC with LLVM would bring this project.

**Comment by s09bQ5** [comment]
Just profiled USDX while I was playing a song with background video in single player mode. The computer is an Atom 330 (1.6GHz dual core, released 2008) with NVIDIA ION chipset/GPU. The microphone was a wired SingStar USB microphone. USDX ran in 1920x1080 and libavcodec was decoding the video in software. Only about 10% of the instructions executed were generated by the Pascal compiler.

[oprofile.log](https://github.com/UltraStar-Deluxe/USDX/files/3692563/oprofile.log)
.

**Comment by deuteragenie** [comment]
Oh, thanks for the profiling results.

I mistakenly thought that the app would be CPU bound by the Pascal compiler generated instructions, but based on your results, it appears not to be the case.  So probably, the potential gain is more like 10-20% of 10%, ie 1% or 2%  less CPU consumption, which is probably not worth the accrued complexities.
