### ISSUE TITLE
[BUG] Display problems with macOS Catalina 10.15

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#492]
Just compiled USDX on macOS Catalina 10.15 after updating yesterday (side note: Xcode command line tools need to be reinstalled via `xcode-select --install` after the OS update) without problems. However, when starting UltraStar, it only occupies a quarter of the window (lower left corner) if in windowed mode and (the lower) two thirds of the screen when in fullscreen mode. I played around with different resolutions, but no significant improvement and like this unplayable, unfortunately.

![Bildschirmfoto 2019-10-21 um 22 59 10](https://user-images.githubusercontent.com/1497707/67243085-1bf6c500-f457-11e9-89e5-775f4cd2a3dc.png)
<img width="1792" alt="Bildschirmfoto 2019-10-21 um 23 05 39" src="https://user-images.githubusercontent.com/1497707/67243210-5a8c7f80-f457-11e9-80f4-3c05c950ae98.png">

And, I also noticed that it is not possible anymore to change the desktop when UltraStar is running (swipe left/right with three fingers in standard configuration), but this has been the case even before updated to Catalina.

Provide some additional information:

- USDX version: latest master
- Operating System + version: macOS Catalina 10.15

**Comment by basisbit** [comment]
Could you try if performous or some other application using SDL2 works?

**Comment by bohning** [comment]
Sure. Googling »osx catalina "sdl2" problem« I found [this](https://github.com/redeclipse/base/issues/920), which seems to be exactly the same problem.

**Comment by bohning** [comment]
I tried Performous, fullscreen mode does not seem to work, but at least the game part is centered ;-)

<img width="1680" alt="Bildschirmfoto 2019-10-30 um 10 23 16" src="https://user-images.githubusercontent.com/1497707/67845365-aa2a1580-faff-11e9-9669-00924fb9de35.png">

**Comment by s09bQ5** [comment]
@bohning, are you using brew? Have you tried installing the head version of sdl2?

**Comment by bohning** [comment]
> @bohning, are you using brew? Have you tried installing the head version of sdl2?

Yes, I am using brew. TBH, I don’t know how to install the head version (or do you mean brew upgrade?). Any suggestions on how to proceed are welcome.

**Comment by s09bQ5** [comment]
@bohning, try `brew reinstall --HEAD sdl2`

**Comment by bohning** [comment]
> @bohning, try `brew reinstall --HEAD sdl2`

Unfortunately I get: Error: invalid option: --HEAD

**Comment by s09bQ5** [comment]
That option was supported some time ago and the man page on the brew website still lists it for the install command. Maybe someone in #machomebrew on freenode can help.

**Comment by jbretsch** [comment]
Does `brew upgrade --fetch-HEAD sdl2` do what you want?

**Comment by bohning** [comment]
> Does `brew upgrade --fetch-HEAD sdl2` do what you want?

Thanks for the help! Seems like I already have the latest version installed (I get "Warning: sdl2 2.0.10 already installed). I guess I need to recompile and test if the issue still occurs...

**Comment by bohning** [comment]
Unfortunately, the problem still persists:

<img width="1680" alt="Bildschirmfoto 2019-12-19 um 22 33 50" src="https://user-images.githubusercontent.com/1497707/71211607-c94b5500-22af-11ea-84be-fb41e3e372e6.png">

In additional, I now get many many "config-darwin.inc(98,2) Warning: Illegal compiler switch "$"" when compiling. Does not seem to be a problem, but they definitely weren’t there before. ;-)

**Comment by s09bQ5** [comment]
2.0.10 is too old. With `--HEAD` brew is supposed to install the development version that does not yet have a version number.

**Comment by s09bQ5** [comment]
> In additional, I now get many many "config-darwin.inc(98,2) Warning: Illegal compiler switch "$"" when compiling.

Did you run autogen.sh before running configure? A recent merge added a few autoconf substitutions.

**Comment by bohning** [comment]
> > In additional, I now get many many "config-darwin.inc(98,2) Warning: Illegal compiler switch "$"" when compiling.
> 
> Did you run autogen.sh before running configure? A recent merge added a few autoconf substitutions.
> 
> And this issue is not a bug inside USDX. You don't need to recompile.

Ah, no I did not run autogen.sh. Again, thanks for the hints and help!

**Comment by bohning** [comment]
Okay, finally found a solution/workaround:

`brew unlink sdl2
brew install mercurial
brew install --HEAD sdl2`

This will unlink the 2.0.10 sdl2, install mercurial (to be able to fetch latest sdl2 HEAD) and then installs the latest HEAD of sdl2. This resolves the original issue =)

Thanks again, @s09bQ5 and @jbretsch!
