### ISSUE TITLE
Core dump while in "Record" panel

### ISSUE THREAD

**Issue by deuteragenie** [UltraStar-Deluxe/USDX#493]
Core dump while in "Record panel".
Running on latest git/master, Ubuntu.

Trace:

ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( hostApi, parameters, streamDir, &pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1768
ultrastardx: src/hostapi/alsa/pa_linux_alsa.c:3641: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed.
Aborted (core dumped)

**Comment by deuteragenie** [comment]
Seem to be related to this issue in portaudio:
https://app.assembla.com/spaces/portaudio/tickets/268/details

Unfortunately, no fix where committed to portaudio since that time.

**Comment by basisbit** [comment]
Sorry, but there is not much we as UltraStar Deluxe developers can do to fix this problem. Please try to find a workaround yourself and then report this here, so other users with the same problem might see what they could try. Thank you! The issue will be closed (as there is nothing to be done in USDX), but you can still write comments, keep us up to date and discuss this problem.

**Comment by s09bQ5** [comment]
Patches can be found on the Portaudio mailing list:
https://lists.columbia.edu/pipermail/portaudio/2019-January/001734.html
https://lists.columbia.edu/pipermail/portaudio/2019-July/001888.html
The discussion on the mailing list has died off months ago.

The problem is caused by audio data being consumed or produced by USDX slower than necessary to keep up with the sampling rate.

**Comment by basisbit** [comment]
in that case it might be a sampling rate mismatch.
