### ISSUE TITLE
Please add a volume control for background music

### ISSUE THREAD

**Issue by hackerb9** [UltraStar-Deluxe/USDX#497]
The background music sounds like it is being played at full volume. I'd like it to be much quieter. (Maybe 30% volume). There does not appear to be any setting to change the bg music volume, only a toggle to turn it off completely.

- USDX version: Compiled from current GIT source today. 
- Operating System + version: Debian GNU/Linux 10 (Buster)

**Comment by barbeque-squared** [comment]
Is this about the menu background music, or the preview music that plays when selecting a song?

If the former, would setting it to the preview volume (if it's not completely disabled) be an adequate solution? Basically:
* if background music enabled -> play at Preview Volume
* if background music disabled -> don't play any background music

**Comment by hackerb9** [comment]
Yes, that sounds good to me.

**Comment by barbeque-squared** [comment]
@hackerb9 I've created a PR that links this to the preview volume. If you're able to, can you test it?
