### ISSUE TITLE
[Jukebox] inconsitent behaviour when entering Sing for 1st time

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#5]
Preconditions:
Options --> Game --> Tabs=Off
Only 1 song

Steps to reproduce:
1. Start USDX
2. Click Jukebox
3. Press Enter
(Jukebox Just starts playing in Background without Full screen Video etc., intended?)
4. Enjoy the song for a moment (Optional)
5. Click Sing
6. Press Enter
7. Press Enter
8. Notice the Song selection preview is exactly in sync with the song playing

Expected:
Song preview restarts song
(This happens if you have entered Sing before)

General Observations:
If you enter Sing for the 1st time the song usually does not start to preview
If you enter Sing for the 2nd time the song immediately starts the preview

**Comment by basisbit** [comment]
Can not reproduce the issue step number 3.
The sing -> song preview not playing at first time is a feature, not a bug in my opinion. If you still want preview for that song, just press right arror key and then left arrow key.

**Comment by tobijdc** [comment]
I have to check again, what i remember, if you do step 3 with "multiple songs" it shows you the playlist (or does not start playing immediately?).
So (as far as i remember) the issue with step 3 is inconsistency in behavior between having only 1 song or multiple songs in the library. .

I think i will have time on the weekend to check again and improve explanation of this bug report.

**Comment by basisbit** [comment]
I tried with only one song loaded in usdx and behaviour seems the same as for loading many songs. Maybe I fixed by already within the last months^^

**Comment by RattleSN4K3** [comment]
> General Observations:
If you enter Sing for the 1st time the song usually does not start to preview
If you enter Sing for the 2nd time the song immediately starts the preview

Yep. I immediately thought the song was damaged and only had silence + the video got removed.

About the oher stuff, I can also not confirm a problem (following the steps you mentioned).

**Comment by basisbit** [comment]
see #250
