### ISSUE TITLE
Wiki: Explain Options -> Game -> Delay

### ISSUE THREAD

**Issue by speich** [UltraStar-Deluxe/USDX#515]
Could you document/explain (in the wiki) what the settings Option -> Game -> Audio/Video Delay and Microphone Delay do?

**Comment by basisbit** [comment]
Hi, Audio/Video delay controls how much offset between audio and video delay is to be factored in (the game accordingly plays the video frame with the required offset to compensate for these. It helps for example when you use a bluetooth speaker with high delay or a TV which does "video enhancing".
The Microphone Delay option allows you to specify roughly how much latency of the microphone is to be expected. (this is the offset which will be factored in for grading the right syllables)

**Comment by speich** [comment]
Ok, thanks for the quick reply.
And thank you very much for usdx, I just enjoyed singing last night on valentines day with my wife!
