### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by thomasdiesenreiter** [UltraStar-Deluxe/USDX#522]
**Please, do not create duplicate issues**

### Actual behaviour

Framerate of about 3-4 fps already in the menu

### Expected behaviour

Normal framerate

### Steps to reproduce

1. git pull from latest 2020.4.1-dev build
2. compiled, some warnings, no errors
3. game starts as it should, but framerate is really low

### Details

Provide some additional information:
- USDX version: 2020.4.1-dev 
- Operating System + version: Linux 4.19.66-v7+ armv7l GNU/Linux
- tried both opengl drivers available for the raspberry, no use. Glxgears is working and shows 47 fps (full kms driver) and 40 (fake kms driver).

**Comment by s09bQ5** [comment]
Please `grep OpenGL Error.log`

**Comment by thomasdiesenreiter** [comment]
```
INFO:   OpenGL vendor VMware, Inc. [UGraphic.InitializeScreen]
INFO:   OpenGL renderer Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits) [UGraphic.InitializeScreen]
INFO:   OpenGL version 3.0 Mesa 13.0.6 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor VMware, Inc. [TTextureUnit.Create]
INFO:   OpenGL renderer Gallium 0.4 on llvmpipe (LLVM 3.9, 128 bits) [TTextureUnit.Create]
INFO:   OpenGL version 3.0 Mesa 13.0.6 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]
```
Thats all

**Comment by s09bQ5** [comment]
llvmpipe is a software renderer. There is not much we can do in USDX. We are just using the OpenGL that SDL wants us to use.

**Comment by thomasdiesenreiter** [comment]
You were right! There seems to be a bug in the current raspbian configuration which prevents loading of the correct driver. Should anyone stumble upon this post, see https://bugs.launchpad.net/raspbian/+bug/1713746
Solution:
1. Activate fkms driver in raspi-config
2. Disabling /usr/share/X11/xorg.conf.d/99-fbturbo.conf by renaming it
3. Restart
