### ISSUE TITLE
Display Mode Not Switched at Launch on Windows

### ISSUE THREAD

**Issue by Ionwerks** [UltraStar-Deluxe/USDX#528]
I believe this parallels a similar report on MacOS; https://github.com/UltraStar-Deluxe/USDX/issues/500

I run Windows at my TV's native resolution (a paltry 1024x768) for maximum text legibility but games look better (and are less confused by the TV's weird pixel aspect ratio - it's actually a 16:9 display) when configured to run in FHD - yielding a form of super-sampling (downscaled by the TV hardware).

However when USDX launches (configured with Fullscreen=On@1920x1080) the display mode isn't properly set and it shows at a reduced size with black borders until I go into the graphics options and exit via _Back_ whereupon the display mode switches and shows edge to edge.

I strongly suspect the fix arrived at for MacOS (calling UpdateVideoMode within Initialize3D) would work equally well for this issue on Windows.

Steps to Reproduce
1. Configure USDx to run Fullscreen:On (not Borderless) at a resolution other than the desktop resolution (in my case a higher resolution).
2. Exit USDx.
3. Launch USDx. On my system the game window does not display edge-to-edge but rather (in my case) is sized down within black borders (presume wrong video mode).
4. Enter Tools > Options > Graphics then exit (without making changes) via the Back button. The display mode should then reset to the desired mode and the USDx window will show edge to edge.

Version
2020.4.0 Stable (Last Reset at 05.04.2020)

**Comment by Ionwerks** [comment]
While this remains something that I think might be looked at, in the end I just settled on non-native resolution that works well enough on the desktop and for games. For my purposes this is now a non-issue.

**Comment by basisbit** [comment]
I can't reproduce this problem here on various WIndows systems...
