### ISSUE TITLE
Linux tarballs & DEB Downloads missing on USDX/releases & SourceFourge

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [UltraStar-Deluxe/USDX#529]
### Missing builds for Linux
The following builds could neither be found on USDX/releases nor GitHub
- Linux Tarball x86
- Linux Tarball amd64
- DEB packages x86
- DEB packages amd64

### Expected behaviour
- The Travis CI already includes creating a Linux tarball-release. This should be provided as a Download option.
- On amd64 and x86 building a DEB package works with the existing debian config. We should integrate this into Travis CI as well.

**Comment by cRaZy-bisCuiT** [comment]
> DEB for Debian or Ubuntu? And which release should we target?
I would target the latest debian relase. In most cases they will run on current Ubuntu versions as well.
> x86-32 would be slightly more difficult because of #325. We would have to make a custom build of Free Pascal to have a compiler that generates correct code.
amd64 might be enough.
> I don't see the benefit of plain tarballs. 
I just meant if we could buid them anyway, why not providing them? But yes,snap or flatpack might be a better option.

**Comment by s09bQ5** [comment]
Close?

**Comment by barbeque-squared** [comment]
Yeah I don't see the point of keeping this open. Github provides source archives anyway, and if a distro wants to provide a binary -- well they can just build and distribute it themselves.
