### ISSUE TITLE
Wrong version (showing MyLittleKaraoke build)

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#53]
With commit 61d879ef06722832e63936b01cc8ab23f09d62ca, UConfig.pas has been falsely changed.

> ```  
USDX_VERSION_MAJOR   = 2016;
USDX_VERSION_MINOR   = 1;
USDX_VERSION_RELEASE = 1;
USDX_VERSION_STATE   = '';
USDX_STRING = 'MyLittleKaraoke - Singing is Magic';
```

**Comment by basisbit** [comment]
oops.. thanks for the note
