### ISSUE TITLE
videos not playing in newer version of USDX that worked in 1.1 version

### ISSUE THREAD

**Issue by Nopertud** [UltraStar-Deluxe/USDX#531]
The bigger video files are not playing neither when going through the list nor when actually selecting the song
They all used to play with the older version of USDX 1.1.
I have tried all newer versions but no luck. I have tried changing the res and play about settings under Graphic but no luck yet.
I must be missing something simple.
can someone direct me to it.
Ta

- USDX version: 2020 
- Operating System + version: win 10

**Comment by s09bQ5** [comment]
Well, yeah, Intel Core 2 is pretty old. Several generations older than what Intel supports in Windows 10.

But back to the original problem:
According to https://opengl.gpuinfo.org/displayreport.php?id=238 Microsoft's software rendering driver has a GL_MAX_TEXTURE_SIZE of 1024. I can imagine that they enforce this limit.

I have a patch that gradually reduces the output size of swscale until glTexImage2D succeeds, but I feel that I should review the changes after I've had some sleep.

**Comment by basisbit** [comment]
The fallback opengl.dll from MS Windows is a OpenGL 1.1 only and super slow software renderer which is unusable. Please do not try to make usdx usable with it - the user experience will not be good.

**Comment by cRaZy-bisCuiT** [comment]
This is actually a pretty smart way of $$MS and hardware vendors to push planned obsolescence. >.<

@Nopertud : Linux would run pretty nice on such a mashine. ;)

**Comment by s09bQ5** [comment]
But USDX _is_ OpenGL 1.1 + GL_EXT_texture_edge_clamp and I have a Riva TNT2 somewhere in my closet that is also limited to 1024x1024 textures. VIA Unichrome and some SiS chips supported until MESA 7.x also couldn't do bigger textures.

And I just found [a MESA driver](https://gitlab.freedesktop.org/nchery/mesa/commit/485438e2be08c6d57110101f76dd41a5f484a4ee) (also removed in 8.0) that can use DX7-DX9 for rendering. Same limitation: GL_MAX_TEXTURE_SIZE = 1024.

I'll put a commit into the pull request that displays a popup window with a warning on startup when one of the known software renderers is used. Deal?
