### ISSUE TITLE
Enhanced Game Controller Support

### ISSUE THREAD

**Issue by Ionwerks** [UltraStar-Deluxe/USDX#533]
I prefer to run my living room PC's UI with a game controller and there are a couple of enhancements to the support for this I'd ask you to consider;

1. Key-Repeat: With my X360 controller I can navigate the music selection one song at a time but I can't hold down either the DPad or RStick to get continuous navigation. I have to press and release to move one song - quite slow, especially with a device that can't jump-to-letter. Ideally one of these (probably the stick) would allow continuous scrolling.

2. Webcam-Toggle: I'd love a bind to toggle the webcam feature (or cycle through background options).

I expect I might be able to work around these using an external utility but it's kind of wasteful to have two pieces of software polling the controllers and likely a lot less reliable than just having support in the foreground app.

Version
2020.4.0 Stable (Last Reset at 05.04.2020)

Great work by the way, my family are making the most of lockdown not least because of UltraStar Deluxe. Your work is much appreciated.

**Comment by Ionwerks** [comment]
Tried a work-around based on SendInput (WinAPI) but it didn't work, presume USDX may be polling the hardware state.

**Comment by Ionwerks** [comment]
Okay, so SendInput will work with SDL if I submit scan codes rather than virtual key codes.

At this point I have work-arounds for the requested enhancements. While I still think these would be useful improvements to USDX, for my own purposes they're now not required (though I'd still welcome an implementation within USDX).

**Comment by brianch** [comment]
About the 1st point (Button-Repeat) do you know if it would be easy to do, @RattleSN4K3 ? I think it would be a great improvement.

I took a look but was a bit confused, if you have any tips I could try to do it.
