### ISSUE TITLE
ALSA error: Access violoation when trying to start the game

### ISSUE THREAD

**Issue by speich** [UltraStar-Deluxe/USDX#537]
After compiling when I try to start the game, I get the following error:
/usr/local/bin/ultrastardx
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
An unhandled exception occurred at $00007F6BB2969623:
EAccessViolation: Access violation
  $00007F6BB2969623

USDX version v2020.4.0
Linux Mint 20

**Comment by basisbit** [comment]
sorry, but this does not look like a problem regarding USDX, but instead is most likely a problem with your audio setup / audio sink configuration. You might be able to get support from some Linux Mint users forum for this.

**Comment by s09bQ5** [comment]
We've had crashes like this before in #473, #496  and #396. 
Note that $00007F6BB2969623 is inside a library, not inside USDX. My guess is that it's PortAudio that crashes.
Try building --without-portaudio.

**Comment by speich** [comment]
Thanks for the tip. When building with ./configure --without-portaudio the error goes away :-)

**Comment by s09bQ5** [comment]
alsa-project/alsa-plugins#13 crashes at offset 0x623 within a page on current Ubuntu x86-64.
