### ISSUE TITLE
Development guide wrt. plugins

### ISSUE THREAD

**Issue by simlei** [UltraStar-Deluxe/USDX#539]
I have been looking for a way to control USDX from an external program.
On my way I discovered that there are plugins.

However, there seems to be not a trace of information available about the plugin API other than https://github.com/UltraStar-Deluxe/USDX/blob/master/game/plugins/PluginDescription.odt.
If there is anything on the spanish boards I have missed it.

Can anyone point me to where all the current devs organize information about API for other aspiring devs? I would me most grateful.

Also, since a one-off attempt at compiling USDX for linux failed me, I would be glad for an address like a gitter channel or dev bulletin board.

Thanks :)

**Comment by basisbit** [comment]
I think that the best and sadly the only usable documentation currently is the code itself. Within the last couple of years, this part of USDX was kind of a `do not touch` section.
There exists a gitter chat at https://gitter.im/UltraStar-Deluxe/USDX .
If you post your exceptions or error messages, we might even be able to help you get USDX to compile on your linux setup - the most common problem is having a too new ffmpeg version which is not yet made compatible with usdx.

**Comment by simlei** [comment]
Okay, I'll head over there. Can be closed.
