### ISSUE TITLE
 EAccessViolation: Access violation

### ISSUE THREAD

**Issue by mchoccac** [UltraStar-Deluxe/USDX#544]
[hola2.txt](https://github.com/UltraStar-Deluxe/USDX/files/5131181/hola2.txt)
Hi 
when compiling the version
and I try to run it, it tells me this error
run ultrastardx 

ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
An unhandled exception occurred at $00007FB698001623:
EAccessViolation: Access violation
  $00007FB698001623

I am using ubuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

verbose make

**Comment by mchoccac** [comment]
to fix it use this but I'm not sure if it's the best way ./configure --without-portaudio

**Comment by s09bQ5** [comment]
alsa-project/alsa-plugins#13 crashes at offset 0x623 within a page on current Ubuntu x86-64.
