### ISSUE TITLE
Lua 5.4 not yet supported

### ISSUE THREAD

**Issue by ezeklusman** [UltraStar-Deluxe/USDX#557]
Trying to compile last version on macOS Big Sur, I get following errors:
ULua.pas(1360,3) Error: Identifier not found "lua_callk"
ULua.pas(1365,16) Error: Identifier not found "lua_pcallk"

Before, while executing ./configure I got this:
checking for lua5.3... no
checking for lua5.2... no
checking for lua5.1... no
checking for lua >= 5.1... yes (-L/usr/local/lib)
checking version of lua... [5.4.2]
checking size of lua_Integer... 64 bits

Any help? Thanks

**Comment by ezeklusman** [comment]
Removed Lua 5.4 and installed 5.3, got this issue fixed but now this error appears:

Linking ../game/ultrastardx
ld: warning: directory not found for option '-L/usr/X11/lib'
ld: warning: building for macOS 10.4 is deprecated
ld: warning: passed two min versions (10.4, 10.8) for platform macOS. Using 10.8.
ld: library not found for -llua
An error occurred while linking 
Error: Error while linking
Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/local/bin/ppcx64 returned an error exitcode
make[1]: *** [../game/ultrastardx] Error 1
make: *** [all] Error 2

**Comment by buges** [comment]
Hi

This reply might be to late, but try this


brew install lua@5.3
brew link --force lua@5.3

And don't forget about the old version of ffmpeg

brew install ffmpeg@2.8
brew link --force ffmpeg@2.8

Hopefully this helps.

**Comment by ezeklusman** [comment]
Thank you so much!!

I was able to compile the app but unfortunately when trying to execute it I just see the icon for a few seconds and then it disappears.

Is there a way to view a log of what's happening?

**Comment by buges** [comment]
Hi

If your trying to run it from ie "USDX-master/game" you cant.
Try running this make command.

make macosx-standalone-app

It should make you the UltraStarDeluxe.app file in your USDX-master folder.

**Comment by buges** [comment]
BTW I forgot

If the log exists it will be in the console (in utilities) on the left hand side under ~/Library/Logs

**Comment by ezeklusman** [comment]
I run the correct make command and executed the .app file but it just shows the icon a couple of seconds and terminates.

I did find an error (fault) on the Console log:
"This application, or a library it uses, is using the deprecated Component Manager for hosting Audio Components. This is not supported when rebuilding against the 10.16 or later SDK. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h."

That's what appears before it starts shutting it down.

Thanks again for all the help!

**Comment by buges** [comment]
Im running Mojave, but I'll load load BS on to a VM and see if I get the same errors when i get after xmas in a couple of days.

**Comment by ezeklusman** [comment]
Thanks and merry xmas!

**Comment by buges** [comment]
Hi

I've just compiled USDX on Big Sur and had no problems at all.

The only thing i can now think of is if you've got some sort of antivirus software doing something weird or malware which makes the UltraStarDeluxe.app disappear.

where is your source code located? i've got mine in "myhomedir/sourcecode/USDX-master" It really shouldn't make any difference as you know, but i'm just out of ideas now.

As a very last attempt try it from scratch with.

make clean
./autogen.sh
./configure
make macosx-standalone-app

when everything is finished do you get the  message "Standalone Mac OS X application created." in the terminal?

if nothing else works, can you do a make clean, then post the output of the terminal when you run ./configure and then the terminal output of make macosx-standalone-app and upload them to somewhere like pastebin.

**Comment by ezeklusman** [comment]
Tried everything with no success. I do have a specific software that manages audio on this mac so that may be the incompatibility problem.
I've just tested it out on another laptop with Big Sur and it worked fine, so I'll just use that one for the moment!

Thanks again for the help!

**Comment by norwegianblue-nz** [comment]
LUA 5.4 also a problem on Fedora 33. 
+1 for LUA5.4 support please
