### ISSUE TITLE
Game doesn't run well because of Boom 2 equalizer

### ISSUE THREAD

**Issue by kslstn** [UltraStar-Deluxe/USDX#560]
Edit: turns out it was the equalizer application I use, Boom 2, that was not playing nice with USDX. Sorry!

~tl;dr: game was useless on Big Sur until I installed the development dependencies.~

~USDX 2020.4.0, as downloaded from usdx.eu runs with really low performance on iMac (5k, 2017, Big Sur): sound stutters consistently in short bursts every second, very low frame rate visuals (\~5fps). Choosing lower graphics settings improves things, but not to the point where songs are played smoothly and the game can be played.~

~I cloned the repo and followed the [build instructions](https://github.com/UltraStar-Deluxe/USDX#compiling-on-macos-high-sierra-and-above). The result was make: No rule to make target configure', needed by config.status'. Stop.. I followed the build steps again, twice, to no avail. Then I found [this tip](https://github.com/UltraStar-Deluxe/USDX/issues/505#issuecomment-570650548): execute ./autogen.sh && ./configure && make macosx-standalone-app (all in one command line). This time I got a different error (something about ffmpeg). I tried upgrading dependencies, but got stuck on that error. Ready to give up, I removed the project and tried the build that I downloaded again. Now all of a sudden things run smoothly and stable on 5k!~

~I don't need support and I don't have the skills to contribute any code. But I wanted to report this as I think it's unlikely that I'd be the only one for whom the game is useless upon initial download. If I can help debugging by providing more info about my system, please let me know.~

**Comment by s09bQ5** [comment]
> I don't need support and I don't have the skills to contribute any code. But I wanted to report this as I think it's unlikely that I'd be the only one for whom the game is useless upon initial download.

@kslstn, improvements to the documentation are welcome. Even if you don't know how to use git, you can provide sentences and tell us where to paste them.

But knowing that a freshly built USDX runs on Big Sur is valuable as well.

**Comment by kslstn** [comment]
> @kslstn, improvements to the documentation are welcome. Even if you don't know how to use git, you can provide sentences and tell us where to paste them.

Sorry if I was unclear: I couldn't build USDX myself, but after my attempts to do that, the standard build from the website worked all of a sudden. It's like the installation of dependencies made it work. Otherwise I can't explain it. I know how to use git, but as I don't fully understand why the original build didn't work, I don't know what to add. 

I mainly added this issue for two reasons: so the team knows about the issue (although it's vague) and so others experiencing the same can find it and try to follow the steps I took.
