### ISSUE TITLE
Support ffmpeg 4.3

### ISSUE THREAD

**Issue by der-martin85** [UltraStar-Deluxe/USDX#561]
### Actual behaviour

I can't build under Ubuntu 20.10 with ffmpeg 4.3.1. After removing the check for highest Version Number I still the following error:

> USDX-master/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(119,44) Note: Values in enumeration types have to be ascending
> USDX-master/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(504,48) Note: Values in enumeration types have to be ascending
> USDX-master/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(533,49) Note: Values in enumeration types have to be ascending
> USDX-master/src/lib/ffmpeg-4.0/libavutil/pixfmt.pas(554,44) Note: Values in enumeration types have to be ascending
> USDX-master/src/lib/ffmpeg-4.0/avcodec.pas(108,4) Error: User defined: Linked version of libavcodec is not yet supported!
> USDX-master/src/lib/ffmpeg-4.0/avcodec.pas(403,52) Note: Values in enumeration types have to be ascending
> USDX-master/src/lib/ffmpeg-4.0/avcodec.pas(6803,1) Fatal: There were 1 errors compiling module, 

### Expected behaviour

I would like to be able to build the game.

### Steps to reproduce

1. try to build with ffmpeg 4.3.1 (Ubuntu 20.10)

### Details

- USDX version: master (2021-01-06)
- Operating System + version: Ubuntu 20.10

**Comment by basisbit** [comment]
closed as duplicate.
