### ISSUE TITLE
Support AV01 encoded videos

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#564]
### Actual behaviour
USDX currently cannot handle AV01 encoded video files. The video preview in song selection simply shows the cover, the sing screen shows a white background (tested on Mac).

### Expected behaviour
As @basisbit put it in #495: in general, USDX should support whatever formats the ffmpeg version can handle.

**Comment by bohning** [comment]
Just tested with the latest FFmpeg 4.4 build of USDX and I believe this issue can be closed.

I tested the following video qualitites:

- 1080p h264
- 1080 AV01
- 2K AV01
- 4K AV01

All except the 4K AV01 version run smoothly now. The 4K version plays in principle, but lags quite a bit (frame drops).

**Comment by s09bQ5** [comment]
> Just tested with the latest FFmpeg 4.4 build of USDX and I believe this issue can be closed.

Then let's close it.
