### ISSUE TITLE
’R’ restarts the currently playing song, but does not reset lyrics

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#567]
### Actual behaviour
Pressing ’R’ in the sing screen restarts the song from the beginning, but the lyrics do not get reset to the start of the song.

Screenshot taken right after pressing ’R’, song starts playing from the beginning, lyrics remain in the middle of the song:
![image](https://user-images.githubusercontent.com/1497707/110919184-42ebba80-831c-11eb-90e9-b88666fdb7af.png)

### Expected behaviour
’R’ should completely and correctly restart the current song.

### Steps to reproduce
Obvious.

UltraStar Deluxe v2020.4.0-stable
macOS 11.2.2

**Comment by basisbit** [comment]
This is intentional / as designed.
If you want a full restart, press esc and then manually restart the song.

**Comment by bohning** [comment]
Ah okay, didn’t know that. What’s the use case for restarting the song without resetting the lyrics?

**Comment by basisbit** [comment]
You are singing the song and had a sudden interruption and want to get some extra time to get into the lyrics again. Especially during karaike competitions, you'll want to keep the already sung process so it is fair for everyone and the player can't just restart until they have the best amounts of points.

**Comment by bohning** [comment]
So when you hit R, the points are kept and the already sung part is ignored (singing this already sung part doesn’t add any points), until you hit the point in time where R was pressed, so singing can be resumed?

**Comment by basisbit** [comment]
Yes 👍

**Comment by bohning** [comment]
Ah, good to know =)
