### ISSUE TITLE
UltraStar-Deluxe Docker Image

### ISSUE THREAD

**Issue by sw-tracker** [UltraStar-Deluxe/USDX#572]
This is a request and not a bug report. I checked to see if there were other tickets regarding this topic but was not able to find one. Apologies if I missed something.

### Actual behaviour

Currently we have to install UltraStar Deluxe. I checked to see if there was a docker image I could just download, but was not able to find one.

### Expected behaviour

Docker image available.

### Details

The goal would be to have UltraStar running on docker, then it will not matter anymore what OS users "install" UltraStar on. It would be great to have it in docker-hub with proper version tagging + latest.

**Comment by s09bQ5** [comment]
No. Docker is not the the right tool for that.

There is a pull request that adds AppImage and Flatpak builds.

**Comment by sw-tracker** [comment]
Ah thanks for the info!
