### ISSUE TITLE
UltraStar Deluxe is not opening

### ISSUE THREAD

**Issue by kxtlu** [UltraStar-Deluxe/USDX#587]
**Please, do not create duplicate issues**

### Actual behaviour

Yesterday I downloaded UltraStar Deluxe. I'm starting the app by clicking on ultrastardx and I get this text:

''Sorry, an error occurred! Please report this error to the game-developers. Also check the Error.log file in the game folder.
Stacktrace:
Exception class: EAccessViolation
Message: AccessViolation
$00000000
$127123BB
$12709392
$12705D5C
$12708854
$6578E794
$6578E97E
$6576A6DA2
$657A7BAE
$657A70E5
$757B781E
$6675DF7E
$0044A4A7 INITIALIZESCREEN, line 653 of base/UGraphic.pas
$00449C70 INITIALIZE3D, line 480 of base/UGraphic.pas
$0044E334 MAIN, line 202 of base/UMain.pas
$00402B72 main, line 411 of ultrastardx.dpr

### Expected behaviour

The game should be working.

### Details

Provide some additional information:

- USDX version: New version 2020.4.0
- Operating System + version: Windows 10 Pro, 64 bit

This is how it looks like:
![image](https://user-images.githubusercontent.com/87833890/126712815-2e764aaa-5a98-4fc0-9ff7-3b3a96cefa8f.png)

**Comment by basisbit** [comment]
did you possibly add a custom theme, which is not compatible with that UltraStar Deluxe version?
Also, please attach the whole log file as file attachment, thanks!

**Comment by s09bQ5** [comment]
@basisbit, line 653 in UGraphic.pas calls SDL_CreateWindow.

**Comment by basisbit** [comment]
then the log file would probably show that no OpenGL hardware acceleration is available. You might have to either download and install current graphics card drivers from the support website of your hardware vendor, or rename the `opengl32_.dll` file to `opengl32.dll` in the UltraStar Deluxe install folder, then restart the game.

**Comment by kxtlu** [comment]
> then the log file would probably show that no OpenGL hardware acceleration is available. You might have to either download and install current graphics card drivers from the support website of your hardware vendor, or rename the `opengl32_.dll` file to `opengl32.dll` in the UltraStar Deluxe install folder, then restart the game.

Yes renaming worked, thank you so much!

**Comment by s09bQ5** [comment]
This is not a fix. This is a workaround with performance impact.
What GPU do you have?

**Comment by basisbit** [comment]
Could you try installing an older version of the official gpu drivers? (preferably from the nvidia website, not from lenovo)
