### ISSUE TITLE
ffmpeg 5 support

### ISSUE THREAD

**Issue by mweinelt** [UltraStar-Deluxe/USDX#599]
### Actual behaviour

NixOS upgraded ffmpeg to 5.0 and the USDX configure script errored out.

```
checking for libavformat... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libavformat... [59.16.100]
checking for libavutil... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libavutil... [57.17.100]
checking for libswscale... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libswscale... [6.4.100]
checking for libswresample... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libswresample... [4.3.100]
checking version of ffmpeg... configure: error:

Unsupported ffmpeg version, most recent version supported is 3.3.
```

It is interesting to note, that we previously used ffmpeg 4, so that error messages seems somewhat out of date.

### Expected behaviour

USDX should be updated to work with ffmpeg 5.0

### Steps to reproduce

Trivial.

### Details

Provide some additional information:

- USDX version: ade03ddd6d995a78c11de0ed3a1f052adc43ff12
- Operating System + version: NixOS 22.05 (unstable)

**Comment by s09bQ5** [comment]
Supporting FFmpeg 5.0 is not as simple as it was to extend the support from 3.x to 4.x. Functions used by USDX that had been deprecated for a long time have now been removed.
