### ISSUE TITLE
Crash/Regression: Range check error (ERangeError) 

### ISSUE THREAD

**Issue by Avispa** [UltraStar-Deluxe/USDX#602]
### Actual behaviour
Crash

### Expected behaviour
Well..

### Steps to reproduce
Don't know, can only say what I did:
First start of the program and going 1-by-1 through the submenues of the options menu. (Changed theme to winter, in case it's relevant.)
Crashed when trying to enter `Record` option.

### Details
```
Stacktrace:
Exception class: ERangeError
Message: Range check error
  $00512CDA  TSCREEENOPTIONSRECORD__DRAW, line 813 of screens/UScreenOptionsRecord.pas
  $00435D52  TDISPLAY__DRAW, line 379 of base/UMain.pas
  $0044E59C  MAIN, line 266 of base/UMain.pas
  $00402B72  main, line 411 of ultrastardx.dpr
```

### System
- USDX version: **2020.4.0 stable**
- Operating System: **Windows 10**

### Side note/critic
Why do I have to re-type the error message? I guess this will (A) deter a lot of people commiting (usefull) bug reports, (B) even if they do makes it hard to find them because you cannot text-search an uploaded image/screenshot and (C) is very error proun due to typos.
... and no, it is not found in the `Error.log`. There I only have a lot of:
```
...
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
...
ERROR:  Could not load texture: "" with type "Transparent" [TTextureUnit.LoadTexture]
ERROR:  Image-File does not exist "" [LoadImage]
....
```

**Comment by HermannDppes** [comment]
Just a passerby so I'll refrain from commenting on any of your other points, but

> Changed theme to winter

is indeed relevant. The default-selected skin does not exhibit this behaviour. All other default-available skins probably do, though. If you (or anyone else finding this issue) want to fix this yourself, either reset to theme Modern and skin Blue or add the line `PopUpFG     = [menu]popUpFG.png` to the file `Modern/Winter.ini` (or other appropriate theme files) to prevent the crash.
