### ISSUE TITLE
adapt installer for "Giddy-Up" release

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/USDX#61]
- [ ] add all required DLLs to the installer
- [ ] make installer set folder permission for the USDX programs folder to read-write allowed for all authenticated users
- [ ] test if update procedure from USDX 1.1 install works
- [ ] update procedure should be to uninstall old USDX 1.1 but keep anything in subfolders playlists, screenshots, songs and webs

**Comment by basisbit** [comment]
#102 is part of this

**Comment by RattleSN4K3** [comment]
As of ccff9b0, I do think all of the points in this issue are solved. Except the following one which I haven't tested. I also don't know what you intend to set. Home editions don't have that much power to set "read-write" for a specific user. Nowadays UAC is handling most of these things.

> make installer set folder permission for the USDX programs folder to read-write allowed for all authenticated users
