### ISSUE TITLE
Songs not showing up correctly

### ISSUE THREAD

**Issue by Ogutk** [UltraStar-Deluxe/USDX#614]
While testing out different songs I encountered 3 different results when trying to launch them in USDX.

### Actual behaviour

First possibility: The song works just fine
Second: The song loads in fine but the lyrics are messed up (only in game not in the txt)
Third: The song does not show up at all

### Steps to reproduce

To reproduce the second option try downloading the song "Kenan Dogulu - Bas Harfi Ben" from the "ultrastar espana" website
To reproduce the third option try downloading the song "Mustafa Sandal - Indir" from the "ultrastar espana" website

### Details

Provide some additional information:

- USDX version: 0.6.0
- Operating System: Windows 10

**Comment by s09bQ5** [comment]
Can you show one line from the txt file that is messed up and the surrounding lines? A screenshot showing what it looks like would be good as well.

If USDX fails to load a song, the reason is logged in Error.log.

**Comment by Ogutk** [comment]
Oh I solved the messed up one by changing the txt coding from ANSI to UTF-8. 
Thanks angain for leading me towards the Error.log

**Comment by basisbit** [comment]
Closing this as duplicate. There already exist plenty of other issues regarding file encoding.
