### ISSUE TITLE
ffmpeg 5.1 support (linked version of libavutil is not yet supported)

### ISSUE THREAD

**Issue by diogotcorreia** [UltraStar-Deluxe/USDX#615]
### Actual behaviour

When building from source (i.e. using AUR package `ultrastardx-git`):

```
Compiling base/UGraphic.pas
Compiling screens/UScreenName.pas
Compiling base/UNote.pas
Compiling screens/UScreenJukebox.pas
Compiling media/UVideo.pas
Compiling lib/ffmpeg-5.0/avcodec.pas
Compiling lib/ffmpeg-5.0/avutil.pas
Compiling lib/ffmpeg-5.0/rational.pas
/home/dtc/.cache/paru/clone/ultrastardx-git/src/USDX/src/lib/ffmpeg-5.0/avutil.pas(51,4) Error: User defined: Linked version of libavutil is not yet supported!
/home/dtc/.cache/paru/clone/ultrastardx-git/src/USDX/src/lib/ffmpeg-5.0/avutil.pas(172,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
make[1]: *** [Makefile:245: ../game/ultrastardx] Error 1
make[1]: Leaving directory '/home/dtc/.cache/paru/clone/ultrastardx-git/src/USDX/src'
make: *** [Makefile:126: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

### Expected behaviour

It should compile without errors

### Steps to reproduce

1. Install `ffmpeg` 5.1.
2. Compile manually or try to install from the AUR

### Details

Provide some additional information:

- USDX version: 6bb2a06e
- Operating System + version: Arch Linux (Linux 5.19.3-arch1-1)

This only happens during compile time. Compiling with ffmpeg 5.0 and running with ffmpeg 5.1 works correctly.

**Comment by brianch** [comment]
Hello,

Try it now, it seems that indeed nothing was changed in the api from 5.0 to 5.1, so just bumping the maximum compatible versions should work.

**Comment by bohning** [comment]
Works like a charm on my Mac. Thanks a lot, @brianch!

**Comment by diogotcorreia** [comment]
I confirm it works after commit 43484b0a10ce6aae339e19d81ae2f7b37caf6baa
