### ISSUE TITLE
Change menu font?

### ISSUE THREAD

**Issue by amenoko** [UltraStar-Deluxe/USDX#624]
Sorry if this is a dumb question but is there a simple way to change the font? I can't find any info on it.

**Comment by barbeque-squared** [comment]
There is no way to change the menu font through any kind of in-game option.

But it's possible (and still fairly easy) to do this by modifying some .ini file:
1. Go to the game directory (on Windows, this is where the .exe is)
2. Go to the `fonts` subfolder
3. Backup the `fonts.ini` file somewhere
4. Open and modify the `fonts.ini` file.

It has some comments in it (it picks the first font for the entire GUI), but basically if you just want the menu font to be DejaVu Sans, cut the entire `[Font_DejaVuSans]` section from the bottom and paste it back at the very top. Save and the next time you start the game, it should use the new font for basically everything _except_ the lyrics.

You should also be able to add entirely new fonts this way, but I haven't tested that.

NB: I tested it on Linux, it _should_ work the same for Windows though.
NB2: this is assuming you use the default theme (Deluxe).

**Comment by amenoko** [comment]
I see! Thanks.
