### ISSUE TITLE
[Video] Check if refresh rate is required for real fullscreen on older displays

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#63]
If a computer is connected with a secondary monitor/TV and attempts to run USDX on that display with the config option to run in fullscreen (`Fullscreen=On`; not borderless), the display might stay black.

Check if refresh rate has to be configured to support that secondary display.

Also evaluate if borderless mode is sufficient in all such cases/setups.

**Comment by basisbit** [comment]
full screen mode will be abandoned. Only windowed full screen will be used in the future. There was a huge discussion about this in #stepmania and then in the #sdl channel about this and we all ended up agreeing that nowadays, there is no valid reason to have old fullscreen mode with custom refresh frequency and custom resolution any more. The user experience of this mode is way too bad.
