### ISSUE TITLE
Flatpak installation error

### ISSUE THREAD

**Issue by Atari2601** [UltraStar-Deluxe/USDX#631]
Attempting to install UltraStar in Batocera using Flatpak

In terminal window using the following prompt:
flatpak run org.flatpak.Builder --user --install-deps-from=flathub --install build $USDX_SOURCE_TREE/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml 

I receive the error:

Can't load '/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml': Failed to open file “/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml”: No such file or directory

Has anyone successfully installed on Batocera? Perhaps a pre-compiled version would work? Just not sure where to go from here

Thank you

**Comment by s09bQ5** [comment]
Uhm, I think the error message is pretty obvious. You passed `$USDX_SOURCE_TREE/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml` to the command and it complained about `/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml` not being found. So `$USDX_SOURCE_TREE` is empty and probably shouldn't be.

**Comment by s09bQ5** [comment]
Ok, I'll not assume that you already cloned the git repository then.

Try
```
flatpak run org.flatpak.Builder --user --install-deps-from=flathub --install build --from-git=https://github.com/UltraStar-Deluxe/USDX dists/flatpak/eu.usdx.UltraStarDeluxe.yaml
```
instead.

**Comment by Atari2601** [comment]
> Ok, I'll not assume that you already cloned the git repository then.
> 
> Try
> 
> ```
> flatpak run org.flatpak.Builder --user --install-deps-from=flathub --install build --from-git=https://github.com/UltraStar-Deluxe/USDX dists/flatpak/eu.usdx.UltraStarDeluxe.yaml
> ```
> 
> instead.

Thank you so much, it installed without any issues. Now I'll just need to work through the process to bring the app into the Batocera front end.

**Comment by s09bQ5** [comment]
After running that command `flatpak list` lists eu.usdx.UltraStarDeluxe as installed application on my computer.

Does `flatpak run eu.usdx.UltraStarDeluxe` work? Then it is installed an merely needs to be added to the menu.

**Comment by Atari2601** [comment]
> flatpak run eu.usdx.UltraStarDeluxe

No, I'm having an issue that flatpak is not showing USD under the apps list - trying to explore what is going on here.. 

one of the commands: batocera-flatpak-update is not working, it should update the flatpak app list and update all permissions on the files but it is not executing.. so somewhere along the line I have an issue with permissions to run this simple command.

I'm still working away at it..

**Comment by Atari2601** [comment]
There may be a fix for this issue in the current beta build, so I'm installing it to see now

**Comment by Atari2601** [comment]
*update* the beta download is painfully slow. I'll let it run and come back tomorrow (late here in Australia) and let you know how things are going or if I have any other questions. I've appreciated your time today, so thanks again.

**Comment by Atari2601** [comment]
Still had no luck today, I've reached out to the Batocera support guys to see if there's anything that I can do as I believe it's a Batocera issue

**Comment by jochenkluger** [comment]
Hi, 
any news on this topic?
I am just trying the same and I am not succeeding in building USDX as flatpak.

I followed the described compiling steps and everything looks fine until module opencv exits with a code 1. It does not matter if I use runtime version 20.08 or 21.08.

...
-- Installing: /app/share/opencv4/lbpcascades/lbpcascade_profileface.xml
-- Installing: /app/share/opencv4/lbpcascades/lbpcascade_silverware.xml

(flatpak-builder:13253): flatpak-builder-WARNING **: 12:58:19.403: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4: Unknown debugging section .debug_line_str

(flatpak-builder:13253): flatpak-builder-WARNING **: 12:58:19.403: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4: Unknown debugging section .debug_loclists

(flatpak-builder:13253): flatpak-builder-WARNING **: 12:58:19.403: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4: Unknown debugging section .debug_rnglists

(flatpak-builder:13253): flatpak-builder-WARNING **: 12:58:19.403: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4: DWARF version 5 unhandled
compressing debuginfo in: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4
processing: /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4
[29] .debug_aranges compressed -> .zdebug_aranges (101920 => 27636 27.12%)
[30] .debug_info compressed -> .zdebug_info (23987795 => 10301436 42.94%)
[31] .debug_abbrev compressed -> .zdebug_abbrev (457696 => 102594 22.42%)
[32] .debug_line compressed -> .zdebug_line (4221172 => 1121637 26.57%)
[33] .debug_str compressed -> .zdebug_str (3114462 => 395660 12.70%)
[34] .debug_line_str compressed -> .zdebug_line_str (10493 => 2359 22.48%)
[35] .debug_loclists compressed -> .zdebug_loclists (8649154 => 2610594 30.18%)
[36] .debug_rnglists compressed -> .zdebug_rnglists (1723476 => 603717 35.03%)
[39] Updating section string table
stripping /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/libopencv_core.so.4.5.4 to /mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/debug/lib/libopencv_core.so.4.5.4.debug
eu-strip: while creating '/mnt/d/Ultrastar/.flatpak-builder/rofiles/rofiles-3sUayD/files/lib/debug/lib/libopencv_core.so.4.5.4.debug': No such file or directory
Error: module opencv: Child process exited with code 1

**Comment by s09bQ5** [comment]
@jochenkluger, your problem is completely different from Atari2601's. It looks like your elfutils package is too old. Does it work if you install the org.flatpak.Builder flatpak and use `flatpak run org.flatpak.Builder` instead of `flatpak-builder` to perform the build?

**Comment by jochenkluger** [comment]
I managed to get it working.
I installed a new ubuntu desktop and did the following (the first steps are from point 5. Build and Run from the github page):

Compiling on Linux/BSD using make
	1. make sure all required libraries are installed
          - sudo apt-get update && sudo apt-get install git automake make gcc fpc libsdl2-image-dev libavformat-dev libswscale-dev libsqlite3-dev libfreetype6-dev portaudio19-dev libportmidi-dev liblua5.3-dev libopencv-videoio-dev
          - sudo apt-get install g++ libprojectm-dev
          - sudo apt-get install g++ libopencv-dev
	2. git clone https://github.com/UltraStar-Deluxe/USDX
	3. cd USDX
	4. ./autogen.sh
	5. ./configure (or use autoconf)
	6. make
--> yes it builds

Building flatpak
1. sudo apt-get install flatpak flatpak-builder
2. sudo flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
3. cd ..
4. sudo flatpak-builder --user --install-deps-from=flathub build/ USDX_SOURCE_TREE/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml --force-clean
5. sudo flatpak build-export export build
6. sudo flatpak build-bundle export eu.usdx.UltraStarDeluxe.flatpak eu.usdx.UltraStarDeluxe

Installation on different machine:
1. copied the file eu.usdx.UltraStarDeluxe.flatpak to the target machine
2. sudo flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
3. sudo flatpak install eu.usdx.UltraStarDeluxe.flatpak

@Atari2601 if you need the flatpak bundle file, I can provide it.
@s09bQ5 would it be possible to provide the flatpak via flathub?

**Comment by s09bQ5** [comment]
Flathub only hosts stable releases, not development snapshots.

**Comment by barbeque-squared** [comment]
I do appreciate all the detailed build stuff in https://github.com/UltraStar-Deluxe/USDX/issues/631#issuecomment-1396702453, and looking at the original issue, isn't really the crux of this whole issue:
> would it be possible to provide the flatpak via flathub?

Because looking at what Batocera is, I think that was the expectation here, not having to compile it for themselves etc.

I'm not against flathub as a (Linux) release distribution channel, but I have no idea how that works nor any intention of figuring it out (or maintaining it). But if someone else wants to do that (@s09bQ5 ?) it's probably not a bad suggestion.
(offtopic: I use Arch so I just build a normally-installable package on one computer and then install that on my other Arch boxes)

**Comment by s09bQ5** [comment]
We've been releasing to Flathub for the past 8 months. I think this issue can be closed and I am tempted to remove the dists/flatpak directory from the USDX repository. The builds for the Flathub releases use the manifest from this repository: https://github.com/flathub/eu.usdx.UltraStarDeluxe/

**Comment by s09bQ5** [comment]
The manifest has been removed from this repository. Please open an issue in the flathub repository if you are still having problems to build the flatpak yourself.
