### ISSUE TITLE
Installer error, probably UAC-related

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#647]
When trying to run a self-compiled installer, I get an error after the UAC prompt.

### Actual behaviour
An error dialog pops up.
Window title = `UltraStar Deluxe 2020.4.0 Dev Setup`
Error message = `Unable to elevate, error 0:\Users\[REDACTED]\AppData\Local\Temp\ns[a-z][4-numbers].tmp`

When opening the directory it contains just a single file: `UAC.dll`

After closing the first popup, it actually opens a second identical one, except the path it reports is slightly different. The directory it reports again contains just a single `UAC.dll`.

After closing the second, the installer process goes away entirely.

### Expected behaviour
???

### Steps to reproduce

1. Make the installer (`makensis "installer/UltraStar Deluxe.nsi"`)
2. Run the generated installer
3. Get the UAC prompt
4. Click Yes

### Details

Trying to run the updater causes the same issue.

I did change line 13 in the UltraStar Deluxe.nsi to read `!makensis Update.nsi` instead of what it was before (but I doubt this has any relation with UAC).

- USDX version: master (actually the deduplicate-versions branch, but I doubt this matters)
- Operating System + version: Windows 10

This blocks #644 (and thus also actually doing a release).

**Comment by basisbit** [comment]
Can not reproduce. Building the nsis installer on Windows with Nsis 3.0.8 works fine here and the result has all the DLLs, exe and so on.
Please extend the issue description by what you expect to happen and what you did do before.

**Comment by barbeque-squared** [comment]
Alright, I've compared a [working 2020.4.0 installer](https://github.com/UltraStar-Deluxe/USDX/releases/download/v2020.4.0/UltraStar.Deluxe_v2020.4.0.stable_installer.exe) with my self-compiled installer:
![2023-02-07-192304_1036x957_scrot](https://user-images.githubusercontent.com/5775429/217332548-12327c1e-e2dd-45c9-a9b0-911e411f4af0.png)
Left side = working, right side = broken
I've filtered it to only show differences and collapsed the languages/resources/themes directories, as I suspect these aren't relevant.

`$PLUGINSDIR` also contains the `UAC.dll` in both versions (not shown in picture because they're identical)

But what immediately jumps out to me is three things:
- dev has no `Uninstall.exe`
- dev has no `pcre3.dll`
- dev has a _significantly_ smaller `ultrastardx.exe`

Is this normal? Especially the lack of an Uninstall.exe? Also: `/installer/settings/files_main_uninstall.nsh:66` references pcre3.dll, but I couldn't find a file like that in git.

**Comment by barbeque-squared** [comment]
I spent some time yesterday, also tried a newer version of https://nsis.sourceforge.io/UAC_plug-in but I keep getting the same error. It's probably something on my PC, but I have no idea what.

I can build the installer just fine, it's just impossible for me to test if it actually works. Do I need to supply the installer when doing a release? If yes, can someone test it if I attach mine here? Alternatively it needs to be built automatically, because I do not want to be dependent on too many people for releases (Mac is currently the exception as I just don't have the hardware).

**Comment by s09bQ5** [comment]
Can't we use Travis or AppVeyor to build the release installer?

**Comment by barbeque-squared** [comment]
@s09bQ5 I created #652 to maybe hopefully fix this. beware that it'll create bigger .exe's than it did in the past (I disabled compression for devbuilds, it makes the .exe generation about 100 times faster -- release builds will still use proper compression) but assuming the jobs actually pass, it'll be a win anyway:
- if the CI-generated exe works, good, because that finally removes the release blocker
- if the CI-generated exe doesn't work either, at least there's now a single reference

**Comment by barbeque-squared** [comment]
I merged #652, for the jobs work and the installer it generates also actually works. Obviously something _must_ be different somewhere, but I can't be bothered to figure it out because as long as there's a working Windows installer somewhere, awesome.
