### ISSUE TITLE
UScreenScore shows wrong texts and avatar screens when screens=2

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/USDX#65]

**Comment by basisbit** [comment]
this is now fixed in a very hacky way. After 1.3 release, UScreenScore should get a full rewrite.

**Comment by RattleSN4K3** [comment]
Some related changes
b647c0549bc1d0d8ff399999fc24275213561bf9
44c2c84a8890c628a380dce453e1859c2e8204c0
a2d8579187362aae0c32efdbdc045f62db48fb38

**Comment by RattleSN4K3** [comment]
PS: @basisbit Can you add another label to specify issues to look after in the future. Something like "backlog" or any other reasonable name.

**Comment by basisbit** [comment]
backlog label was just added.

**Comment by RattleSN4K3** [comment]
Added this one. In case you don't want to be assigned. Assigne me.
