### ISSUE TITLE
Songs with ä ö ü  are missing in the 2023 version 

### ISSUE THREAD

**Issue by LoZe** [UltraStar-Deluxe/USDX#669]
Songs with German umlauts (ä,ü,ö) are no longer displayed in the 2023 version.
it was shown to me in the 2020 version.

Raspberry Pi OS with desktop
    System: 64-bit
    Kernel version: 5.15

**Comment by LoZe** [comment]
I had thought that the problem was due to my error port compiling, but I also have it with the Windows.exe in the 2024.10 Version.
What I have discovered so far, that the letters are converted incorrectly in the error log "Can't find audio file in song: ...".

it is
ä = "61 CC 88"
instead of 
ä = "C3 A4"

**Comment by bohning** [comment]
Seems to be a Unicode normalization issue, see e.g. https://minaret.info/test/normalize.msp

**Comment by s09bQ5** [comment]
@LoZe, can you check with a hex editor which bytes are used in the .txt file of that song to represent the ä?

**Comment by barbeque-squared** [comment]
It's probably something similar to #904, although that did fix special characters in at least the _txt_ filename for me.

Just to make sure: this is with a special character in the `#MP3` tag inside the txt? We can probably use the weird `Č` again because if this has the same cause as the other issue, that one appears to trigger it on most locales.

**Comment by s09bQ5** [comment]
As far as I understood @LoZe has this problem both on Linux and on Windows. So it is unlikely that it is an issue with the locale.

**Comment by LoZe** [comment]
I think the problem occurred while moving the folders.
I have now found out that the wrong character was contained in the file name and folder, the contents of the text file were correct.
I wrote a small program that renames all files with these chars to normal chars.
I can't test it at the moment but I'll let you know as soon as I can start Ultrastar.

**Comment by bohning** [comment]
> I wrote a small program that renames all files with these chars to normal chars.

But why would you want to do that?

**Comment by LoZe** [comment]
because when I look for a band like "Die Ärzte", The Ä key on the keyboard should be the Ä in the name.
