### ISSUE TITLE
Editor - Current note not highlighted

### ISSUE THREAD

**Issue by DoubleDee73** [UltraStar-Deluxe/USDX#674]
**Please, do not create duplicate issues**

### Actual behaviour

While the text of the current note is highlighted in the editor, the actual note is not highlighted in red (anymore)

### Expected behaviour

Currently selected note should be highlighted in text AND in the bar for the note

### Steps to reproduce

1. Open any song in the editor
2. First note should be highlighted

### Details

- USDX version: 2023.4
- Operating System + version: Windows 10 (21H2)

### Example
![screenshot0005](https://user-images.githubusercontent.com/26616916/232291241-a2b2e3a8-da00-4c06-ac12-a36d52ceafa3.jpg)
the corresponding bar for "you" should be highlighted

This used to work. I deinstalled USDX 2023.4 and reinstalled 2023.3, and then I had this issue. I then deinstalled 2023.3 and installed 2020.4 and had this issue. Re-installing 2023.4 did not help either, and then I installed USDX on 2 other Windows computers where it is not highlighted either.

**Comment by DoubleDee73** [comment]
@barbeque-squared 
Ahh. This clears things up.

My P1 is blue, and my P2 is red (probably as per default)
When I select one player, which I had in this particular example, the active note is blue, while the other notes are also blue.
If I change it to green, the active note remains blue, and the rest will turn green.

When I select two players (p1 = blue, p2 = red), the active note becomes red, and the remaining notes are blue.
When I select two players (p1 = blue, p2 = green), the active note becomes green, the remaining notes are blue.

While I can live with that, I think, it'd be better, if at one point the active note became independent from the current color scheme of the configured players, or maybe use a totally different color. Or have a border around the active note...

**Comment by barbeque-squared** [comment]
Okay I retract that statement. I (still) have no idea where exactly it's getting the note colors from, but it's fairly irrelevant now that I discovered that the colors I was going to use (the in the default theme red+orange from the bar with the box thingies -- between the note grid and the lyrics) are actually hardcoded colors.
I'd always assumed that the orange a mix between the highlight color for the lyrics and something else from the theme, but it's actually hardcoded.

As a workaround, I suggest to have at least 2 players active, or just set P1 to some different color.

**Comment by barbeque-squared** [comment]
Closing this as it's been fixed by #870 .

(in the future I might tinker around with 0 players -- to replace most of the jukebox functionality -- but in that case the editor should still be using P1 anyway, or else some hardcoded fallback color)
