### ISSUE TITLE
Uninstaller remove folder when updating that result in a crash under certain circumstances

### ISSUE THREAD

**Issue by LittleTale** [UltraStar-Deluxe/USDX#693]
### Actual behaviour

force close when trying to go to the sing section. screenshot of the error is added in the post.
Thanks a lot in advance.

### Expected behaviour

see the artists songs.

### Details

Provide some additional information:

- USDX version: Latest Version
- Operating System + version: Windows 10 22H2

![Screenshot (83)](https://github.com/UltraStar-Deluxe/USDX/assets/52611040/de87242c-2dcc-4be2-902f-b5eefc6db3bd)

**Comment by LittleTale** [comment]
[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/11525647/Error.log)

**Comment by barbeque-squared** [comment]
Just to check, which of these 2 is happening?
1. it errors when you click "Sing" in the main menu
2. it errors after you've setup players and want to go to the song selection screen

Additionally, can you attach your `config.ini`? You can replace real names with fake names, just leave everything else alone. This sounds similar to #630 but the error is different and it crashes earlier.

Assuming I can reproduce the error, expect a fix within a day or so after you've posted your config.

**Comment by s09bQ5** [comment]
An exception at $004CC2CD means `PlayerAvatars[Player]` is negative.

**Comment by LittleTale** [comment]
Fixed the issue. actually it's because when you update Ultrastar and it ask you to first uninstall the old version it delete the AVATAR folder, and apparently if you have custom avatar pictures, the game crash when launching the sing menu if you had a player with a custom avatar image on your last session before the update.

Maybe you could add a option in the Uninstaller to keep avatar images so it doesn't delete the folder when updating.

**Comment by LittleTale** [comment]
changed the title of the issue to reflect behavor from the problem

**Comment by barbeque-squared** [comment]
Yeah, this is definitely some behaviour extremely related to #630 then. Could be a Windows vs Linux difference (Linux appears to just select the last avatar, apparently Windows crashes earlier). I'll have a go at fixing that one before the next release.

(unless someone is faster than me) I'll also have a look whether there's an easy fix to keep the avatar folder when updating -- you might still have to delete the default avatars from it after every upgrade, but I'm pretty sure it already has options to keep songs etc, so this shouldn't be that difficult.
(this is also an issue under Linux)

**Comment by barbeque-squared** [comment]
I've created #702 as a separate ticket for handling updates/uninstalls better. The original error from the current ticket should be solved by the merging of #698.

Reopen this issue if this error still exists once 2023.6.0 is released.
