### ISSUE TITLE
V:2023.5.0 Doesn't recognize new songs added to folder

### ISSUE THREAD

**Issue by LittleTale** [UltraStar-Deluxe/USDX#696]
### Actual behaviour

After I installed the latest version, every new songs I add to the "songs" folder is not recognize by ultrastar.
It can still access the folder, I changed a song cover image and the change is reflected in-game, but it will not add any new song to the database.

### Expected behaviour

See the newly added songs in the "Sing" and "Jukebox" sections.

### Steps to reproduce

1.Add new song to folder 
(Folder is in Drive D: and the config.ini is set up correctly)
{[Directories]
SongDir1=D:\Program Files\UltraStar\songs
WebScoresDir=}
2.Launch Ultrastar
3.go to Sing
4.New added songs are missing

### Details

- USDX version: 2023.5.0
- Operating System + version: Windows 10 22h2

I will attach the error log, config.ini and example of a song that will not be added.

[Error.log](https://github.com/UltraStar-Deluxe/USDX/files/11538576/Error.log)
[config.txt](https://github.com/UltraStar-Deluxe/USDX/files/11538617/config.txt)
[AURORA - A Dangerous Thing.txt](https://github.com/UltraStar-Deluxe/USDX/files/11538630/AURORA.-.A.Dangerous.Thing.txt)

**Comment by barbeque-squared** [comment]
Since this has already been marked as closed, to others reading this issue: it's most likely because of these lines in Error.log
```
ERROR:  Can't find audio file in song: D:\Program Files\UltraStar\songs\AURORA - A Dangerous Thing\AURORA - A Dangerous Thing.txt
ERROR:  MP3 tag/file missing: D:\Program Files\UltraStar\songs\AURORA - A Dangerous Thing\AURORA - A Dangerous Thing.txt
ERROR:  AnalyseFile failed for "D:\Program Files\UltraStar\songs\AURORA - A Dangerous Thing\AURORA - A Dangerous Thing.txt".
```
which usually mean that `#MP3:` in the txt is pointing to a non-existent file.
