### ISSUE TITLE
[Jukebox] Starting without correct Playlist/Folder leads to crash

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#7]
Precondition:
No Playlist defined

Steps to reproduce:
1. Start USDX
2. Click on Jukebox
3. Select Playlist (No Playlists found)
4. Press Enter
5. Crash

For the Folder Crash substitute Step 3 with "Select Folder (No Categories found)"

Not tested with correct Playlist/Folder (Sorry).

Playlist crash:
![No Playlist Crash](https://i.imgur.com/r8X7gK3.png)

Folder Crash:
![No Folder Crash](https://i.imgur.com/KwqQnyg.png)

**Comment by basisbit** [comment]
fixed.
