### ISSUE TITLE
Windows cannot handle certain flac files since #688

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#700]
I happened to run a very recent CI windows portable and got an error on my main test song. I've pinpointed it to be introduced with the merging of #688, as in:
- d20b1ac9372fbcfb436abc537a1dcc1226e64755 works
- 68515f2307fffc1a1edd88e05052a5ae22543d0e crashes

The error popup:
![2023-05-23-usdx-devbuild](https://github.com/UltraStar-Deluxe/USDX/assets/5775429/2e6ba9ca-365f-44c1-a27d-f48b59fa5339)
(Error.log contains no useful information; that it's opening the file is the last line before the lines you get when USDX closes)

### Steps
1. I've minimized the problem to a txt+flac combination*
2. Start USDX
3. Go to the song
4. It will either crash immediately (or if you wait a few seconds) but no audio will start playing. if it doesn't trigger it just navigate _away_ from it by either going to another song or just starting it. The error picture is from when navigating away from it by starting the song.

mp3's and even _other_ flacs work absolutely fine, and this is Windows so I have _no_ idea what I'm looking at. hell, even a different flac that I know consistently crashed on 2017.x work fine on _both_ commits referenced above.

\* = I can't share this particular flac here for legal reasons, and as soon as I try to make a small excerpt or create a dummy file, _that_ suddenly works just fine. If someone needs my actual file to debug this (people that have previously contributed only please) put it here in a comment and I'll email you a link.

**Comment by s09bQ5** [comment]
Can you add some log lines to TFFmpegDecodeStream.Close to see how far it gets?
Or can you bisect it even more? My guess is that 2303ea537afa71a96d7aa3ce88e4cb372c20618d still works and 1481c309dd47c464809259d4979f4ac611dcfbb4 crashes.

Does this flac play any audio or was decoding for this file broken even before the changes?

**Comment by barbeque-squared** [comment]
If I build it locally, it always fails (also on d20b1ac), so unless there's CI zips for both of these somewhere. The good news is that it is at least consistently crashing.

Beware:
- the way in which it crashes varies, sometimes it segfaults and the log never gets completed (the `Closing DB file` line isn't there), other times there's one error box, other times two (you close the first one and then the second one immediately pops up)
- I noticed that the menu background etc were opened by the `BASS_Decoder` but the flac that crashes gets opened by the `FFmpeg_Decoder`

I added a bunch of log statements and was able to produce this screenshot:
![2023-05-26-usdx-status-packet](https://github.com/UltraStar-Deluxe/USDX/assets/5775429/ce5a068e-e1d8-42cd-a1e4-6f571cf420a9)
_if_ it crashes with a proper error popup (whether one or two), notice how it doesn't log the second `avcodec_send_packet was succesful` line. It does that consistently. Sometimes it's near-instant, other times it can take up to a second or so, but the end of the log will always look like that (I don't know how threaded this runs).

This is all in `TFFmpegDecodeStream.DecodeFrame`. There's only 1 occurence of `avcodec_send_packet` in that file, the two loglines are around that.

**Comment by s09bQ5** [comment]
So the crash is inside avcodec_send_packet. Did you have any logging inside TFFmpegDecodeStream.Close? Are we maybe closing the stream while it is still decoding?

**Comment by barbeque-squared** [comment]
I did have some logging in Close. Look at the `1` to `6` at the bottom of the log. It's not visible in the picture (screen wasn't big enough), but what it's logging is this:
- Bass decoder opens the background music (for the main menu)
- When I go to the Song selection screen, I guess it stops the background music (there's no Bass logging for that). The song it initially selects will not get played, probably a bug somewhere (there's no log that opens any media file when I go there)
- When I press Enter (I only have 1 song -- it's the one that crashes) to sing it, it first logs a bunch of Close lines for FFmpegDecodeStream. They're just not in the screenshot because it didn't fit. It then logs what you see in the screenshot (it opens the file with FFmpegDecodeStream, does some stuff, then crashes).

I'm not even sure if this is the same error as in the first post -- it's really unhelpful that there's no function names being printed -- but it's the error it's currently stuck on.

If you want me to log certain things, could you make a patch/diff? That way you'd know for sure where lines are coming from etc.

**Comment by barbeque-squared** [comment]
In a first quick test, this appears to be fixed by the artifact linked in https://github.com/UltraStar-Deluxe/USDX/issues/701#issuecomment-1566744446

**Comment by s09bQ5** [comment]
> In a first quick test, this appears to be fixed by the artifact linked in [#701 (comment)](https://github.com/UltraStar-Deluxe/USDX/issues/701#issuecomment-1566744446)

Probably because of the `$IF LIBAVFORMAT_VERSION < 59000000` in UAudioDecoder_FFmpeg.pas. It would still be broken for someone using an old FFmpeg version.

**Comment by s09bQ5** [comment]
@barbeque-squared, please test https://ci.appveyor.com/project/s09bQ5/usdx/builds/47170889/job/wgn6sw3ab7dqmyi0/artifacts

**Comment by barbeque-squared** [comment]
@s09bQ5 works (the file for which I originally opened this ticket, and I also tested a bunch of others and didn't notice any issues with them)
