### ISSUE TITLE
USDX crashes when opening "AV1 Video" encoded files

### ISSUE THREAD

**Issue by GrueneNeun** [UltraStar-Deluxe/USDX#701]
**Please, do not create duplicate issues**

### Actual behaviour

Game crashes when it tries to open a file encoded with what VLC identifies as "AOMedia's AV1 Video (av01)" Codec
This happens in 2023.4 and 2023.5. In 2020.04 it does not crash, but the whole game gets really unresponsive.
I have found 3 different files so far which i can upload if necessary (not public of course). Those files all are rather big with resolutions of around 4K. There is no crash report or an error window and in error.log the last entry is that USDX opened the file.

### Expected behaviour

Game should not crash.

### Steps to reproduce

Open USDX
Go to Song Selection
Select a Song with the mentioned Codec
Game crashes

### Details

Provide some additional information:

- USDX version: 2023.4 / 2023.5
- Operating System + version: Windows 10

**Comment by s09bQ5** [comment]
In other words: We should try to ship a newer version of FFmpeg with the Windows build.

**Comment by s09bQ5** [comment]
Difficult... The place where we took our FFmpeg DLLs from (Zeranoe) closed in September 2020. Reino Wijnsma still [provides 32 bit DLLs](http://forum.doom9.net/showthread.php?t=181802), but he builds them without libdav1d. We could try to use [his build scripts and patches](https://github.com/Reino17/ffmpeg-windows-build-helpers) to make our own builds.

**Comment by s09bQ5** [comment]
Can you confirm that it does not crash when you remove the `#VIDEO:` line at the top of the txt file?

**Comment by GrueneNeun** [comment]
Yes, just tested with 2023.4 and 2023.5 both are fine without the #VIDEO: line and instantly crash when it is there.

**Comment by s09bQ5** [comment]
@GrueneNeun, please try https://ci.appveyor.com/project/s09bQ5/usdx/builds/47161286/job/0u9dp95a9846lbeg/artifacts

**Comment by GrueneNeun** [comment]
Seems to work, Videos are a bit laggy, but this could very well be the machine i'm testing on - in any case, the game does not crash which is most important imho.
