### ISSUE TITLE
Jukebox graphics not displaying correctly

### ISSUE THREAD

**Issue by jmfergeau** [UltraStar-Deluxe/USDX#717]
### Actual behaviour
The jukebox interface doesn't display correctly, elements being invisible, hoverable elements appearing only when hovered. (screenshot below)
![v2023.5.0](https://github.com/UltraStar-Deluxe/USDX/assets/6705075/1a4f8548-87f5-419d-b40c-69a4cca3b84e)

### Expected behaviour
The jukebox interface should display correctly, like in screenshot below.
![v2023.4.0](https://github.com/UltraStar-Deluxe/USDX/assets/6705075/85de3efe-2e9c-4dc1-a53a-253e488d0de0)

### Steps to reproduce
1. Open ultrastardx (ensure you have at least one song in the songs folder)
2. Click on jukebox and choose all songs

### Details
- USDX version: v2023.5.0
- Operating System + version: Arch Linux with kernel 6.1.33
- Only happens in 2023.5.0. Previous versions are fine. Does it with both Deluxe and Modern themes, no matter the languages.

**Comment by jmfergeau** [comment]
I made a comparison between the Modern theme of v2023.5.0 and the one from v2023.4.0.

For the inis, I only found a difference with `[SingBackground]`. Nothing relevant to the jukebox. And reverting these values didn't change anything.

For the graphics, I found out that some graphics related to the jukebox are bigger in the v2023.5 than in the v2023.4 and are indeed different. But putting these old files in the new version didn't change anything. I haven't spotted files removed, either.

I have no idea of what's going on.

**Comment by barbeque-squared** [comment]
@jmfergeau is this actually 2023.5.0 or secretly 2023.5.0+dev? Can you check in Tools -> Statistics, or at the top of the Error.log file?

On _my_ system, it appears to be caused by f38a3e8f9636999b2f35ce7ce5b155f23effffac that introduced this. If I go to the parent commit (72b8caa99474b2935856cdbb918a9e6e160e964c) it still looks good. But there's nothing texture-related in the logs.

I also have absolutely no idea why that commit would even cause that behaviour.

**Comment by jmfergeau** [comment]
`UltraStar Deluxe - www.usdx.eu - v2023.5.0+dev Error Log`

...oh.

Indeed, i tried with the appimage of v2023.5 and it doesn't occur there...

~~Can we eventually have an AUR package for a stable version of usdx someday btw??~~

**Comment by s09bQ5** [comment]
f38a3e8f9636999b2f35ce7ce5b155f23effffac lacks a `SDL_UnlockSurface(ImgSurface);` before https://github.com/UltraStar-Deluxe/USDX/blob/c56afde2d317feb9bee3196296e4d84234f4287b/src/base/UImage.pas#L737

**Comment by jmfergeau** [comment]
> [f38a3e8](https://github.com/UltraStar-Deluxe/USDX/commit/f38a3e8f9636999b2f35ce7ce5b155f23effffac) lacks a `SDL_UnlockSurface(ImgSurface);` before
> 
> https://github.com/UltraStar-Deluxe/USDX/blob/c56afde2d317feb9bee3196296e4d84234f4287b/src/base/UImage.pas#L737

Just tried in my own dev version, it works like a charm!
Time to make a pull request! (if no one else did before?)

**Comment by s09bQ5** [comment]
@barbeque-squared, I don't mind someone else making the PR.

**Comment by jmfergeau** [comment]
i did the PR already and credited @s09bQ5 in it ^^ (i have another PR waiting anyway so i don't mind :p )
