### ISSUE TITLE
Editor: Setting Preview and Medley Start does not work anymore

### ISSUE THREAD

**Issue by DoubleDee73** [UltraStar-Deluxe/USDX#721]
### Actual behaviour

- When typing A in the editor, the message "Medley start cleared" is shown
- When typing Shift-I in the editor, the message "Preview start cleared" is shown

### Expected behaviour

- Typing A in the editor, should set the medley start
- Typing Shift-I in the editor should set the preview start

### Steps to reproduce

See behaviour, pretty self explaining....

### Details

Provide some additional information:

- USDX version: 2023.6.0
- Operating System + version: Windows 11

**Comment by bohning** [comment]
Just tested - does work as expected on Mac, so it seems to be a Windows only issue. But along the way, I identified a minor bug: it is not possible to set medley tags to the beginning (first note) and end (last note) of the same line. When the medley start is set to the first note, USDX complains "Medley end not set (must be after medley start)", which it technically is. I guess it has no real life relevance as a medley section should probably always be longer than one line (except maybe "Tequila" by The Champs).

**Comment by barbeque-squared** [comment]
@DoubleDee73 can you try this build please? https://ci.appveyor.com/project/basisbit/usdx/builds/47849412/job/8enooytqfwppm5mx/artifacts
Or if you build them yourself, it's this branch: https://github.com/UltraStar-Deluxe/USDX/tree/debug-721

It adds a few extra log lines (to `Error.log`) when you press A or Shift+I, I need all the lines that have `UScreenEditSub` somewhere in them.

Example output for Shift+I (PreviewStart):
```
INFO:   CurrentSong.HasPreview=0 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentTrack=0 MedleyNotes.Preview.track=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].CurrentLine=4 MedleyNotes.Preview.line=10 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.Preview.note=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].Lines[Tracks[CurrentTrack].CurrentLine].Notes[CurrentNote[CurrentTrack]].IsStartPreview=0 [UScreenEditSub.SetPreviewStart]
INFO:   The Second CurrentSong.PreviewStart=15.61 [UScreenEditSub.SetPreviewStart]
INFO:   The Second CurrentSong.HasPreview=-1 [UScreenEditSub.SetPreviewStart]
```

Example output for A (MedleyStart):
```
INFO:   MedleyNotes.isStart=0 [UScreenEditSub.SetMedleyStart]
```

There might be more or less lines depending on what it's doing.

**Comment by DoubleDee73** [comment]
INFO:   MedleyNotes.isStart=0 [UScreenEditSub.SetMedleyStart]
INFO:   MedleyNotes.isStart=-1 [UScreenEditSub.SetMedleyStart]
INFO:   Tracks[CurrentTrack].CurrentLine=4 MedleyNotes.start.line=4 [UScreenEditSub.SetMedleyStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.start.note=0 [UScreenEditSub.SetMedleyStart]
INFO:   MedleyNotes.isStart=0 [UScreenEditSub.SetMedleyStart]
INFO:   MedleyNotes.isStart=-1 [UScreenEditSub.SetMedleyStart]
INFO:   Tracks[CurrentTrack].CurrentLine=4 MedleyNotes.start.line=4 [UScreenEditSub.SetMedleyStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.start.note=0 [UScreenEditSub.SetMedleyStart]

**Comment by barbeque-squared** [comment]
The first output line tells me that it's correctly knowing that this song doesn't have anything set yet at the very beginning.

Was that log output generated by pressing `A` **once** ? Because if yes: it's (somehow) getting triggered 4 times by a single keypress.

I do notice that most of the other screens (Jukebox being a notable exception, because _of course it is_) use this form to check for "letter" key presses:
```
case UCS4UpperCase(CharCode) of
      Ord('S'): begin
```
whereas the editor uses `case PressedKey of SDLK_S`. Not sure why this would make a difference, but I'll get a build out later where it uses the `Ord` one for the `A` key but not for `I` and see if that fixes anything.

**Comment by DoubleDee73** [comment]
I did this again, and after I pressed SHIFT+I, these loglines were added:
`INFO:   CurrentSong.HasPreview=0 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentTrack=0 MedleyNotes.Preview.track=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].CurrentLine=10 MedleyNotes.Preview.line=18 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.Preview.note=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].Lines[Tracks[CurrentTrack].CurrentLine].Notes[CurrentNote[CurrentTrack]].IsStartPreview=0 [UScreenEditSub.SetPreviewStart]
INFO:   The Second CurrentSong.PreviewStart=49.23 [UScreenEditSub.SetPreviewStart]
INFO:   The Second CurrentSong.HasPreview=-1 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentSong.HasPreview=-1 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentTrack=0 MedleyNotes.Preview.track=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].CurrentLine=10 MedleyNotes.Preview.line=10 [UScreenEditSub.SetPreviewStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.Preview.note=0 [UScreenEditSub.SetPreviewStart]
INFO:   Tracks[CurrentTrack].Lines[Tracks[CurrentTrack].CurrentLine].Notes[CurrentNote[CurrentTrack]].IsStartPreview=-1 [UScreenEditSub.SetPreviewStart]`

then I pressed A, which resulted in:
`INFO:   MedleyNotes.isStart=0 [UScreenEditSub.SetMedleyStart]
INFO:   MedleyNotes.isStart=-1 [UScreenEditSub.SetMedleyStart]
INFO:   Tracks[CurrentTrack].CurrentLine=10 MedleyNotes.start.line=10 [UScreenEditSub.SetMedleyStart]
INFO:   CurrentNote[CurrentTrack]=0 MedleyNotes.start.note=0 [UScreenEditSub.SetMedleyStart]
`

**Comment by barbeque-squared** [comment]
Yeah it's absolutely being triggered multiple times. Can you try this build: [TODO LINK](https://ci.appveyor.com/project/basisbit/usdx/builds/47864612/job/iui99umjhveoi940/artifacts) ?

Unlike my previous comment it was easier to just use the `Ord` method for all letter keys in the editor, so either everything suddenly works, or everything is still as broken as before. But in the latter case we can at least start ruling things out.

**Comment by DoubleDee73** [comment]
Thanks. This is working again now! We can close the issue, once this has been released, right?

**Comment by barbeque-squared** [comment]
Well I'd rather not merge the debug lines, and now that we know this is an issue, I'd like to have a quick look through the code to see if there's any other places that also use the non-`Ord` form. Ideally I could write a shitty test that just greps for `SDLK_` and then specifically exclude all the non-letter stuff, but I don't know how to do that in AppVeyor :( That would make sure this doesn't accidentally happen in the future.

I'll make a proper PR for the fix, once that's merged this can be closed. Keeping tickets open until _release_ will just clutter things. I was going to go for a September release anyway.

Thanks for testing! No idea _why_ this fixes the problem, but hey, as long as it works...
