### ISSUE TITLE
Windows Defender detects malware 

### ISSUE THREAD

**Issue by knabbels** [UltraStar-Deluxe/USDX#722]
USDX Release (v2023.6.0)

File: libdav1d.dll
Malware: Trojan:Win32/Wacatac.B!ml

Operating System: Windows 10

**Comment by s09bQ5** [comment]
Did you compare the file on your computer to the one in our git repository?
1300499 bytes and sha256 hash 3bbe5c2867b693ef8f9a9a05c0bef2696e5e937f06e4aa92d46263d4fac86793.

I have cross compiled this DLL from source code on a Linux machine. The built process didn't even involve Wine. So I highly doubt there is a Windows trojan in that DLL.

**Comment by basisbit** [comment]
Of course there is no malware in the file. Windows Defender if just notoriously annoying with false positives when you compile and share your own DLLs of installers or encoders/decoders. I suggest checking all files on virustotal.com and slightly adjust the compiler flags and recompile until none of them "detects" anything and then publish this.

**Comment by basisbit** [comment]
(see also #368 - same issue a few years ago, but Microsoft Defender considers the installer to be "suspicious"... I wish this snakeoil software would use better pattern-checks)

**Comment by s09bQ5** [comment]
I have submitted the file to Microsoft as a false positive (Had to create a Microsoft account to do this 🤮). The case is still open, so I guess a human will look into this.

I don't think there is any value in someone else doing this again for the same file, but for future reference here is the link I used: https://www.microsoft.com/wdsi/filesubmission

**Comment by s09bQ5** [comment]
I also submitted it to Avast. Both Microsoft and Avast have confirmed that it is not malware. VirusTotal no longer detects anything with Microsoft's, Avast's, and AVG's checker.

The comment from Microsoft is

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

There are still 37 other services that detect something, though.
