### ISSUE TITLE
Ubuntu2004 CI job consistently fails

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#726]
Example job: https://ci.appveyor.com/project/basisbit/usdx/builds/47670013/job/945wxc8lwsrt5u9f

Job output:
```
Build started
git clone -q https://github.com/UltraStar-Deluxe/USDX.git /home/appveyor/projects/usdx
git fetch -q origin +refs/pull/724/merge:
git checkout -qf FETCH_HEAD
Running "install" scripts
$env:package_version = ("$(git describe --tags --always --long)").trim()
Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
sudo apt update -qq
E: Repository 'http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal InRelease' changed its 'Label' value from 'Modern Erlang packages for Ubuntu and Debian' to 'Latest (26.x) Erlang packages for Ubuntu and Debian'
Command exited with code 100
Build failed
```

This causes all pipelines to fail (which is slightly annoying on PR's) and also causes this artifact to not be built anymore.

**Comment by s09bQ5** [comment]
Isn't this something AppVeyor should fix in their image?

**Comment by barbeque-squared** [comment]
I don't know (enough about) how AppVeyor works to answer that. Let alone if yes, how to get it fixed.

**Comment by s09bQ5** [comment]
I just sent a mail to their support address.

**Comment by barbeque-squared** [comment]
Didn't get around to look at this until now, but merged the PR because that option is probably fine to keep going forward anyway. Thanks for doing the email on this one, no idea how I missed that page...
