### ISSUE TITLE
The "releases" branch also needs to be updated when doing a release

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#735]
Apparently the self-updater (Windows only) relies on the https://github.com/UltraStar-Deluxe/USDX/tree/release branch.

I don't exactly know how this works, but I _think_ RELEASING.md needs to have a seventh step where you merge _something_ into it?

Something like:
- go to the branch
- `git merge --ff-only v<the-new-version>`
- `git push origin release`

?

I don't know who did this for the recent release(s) (and thank you for doing it!) and while I certainly don't want to do everything myself, I think it should at least be documented. But I don't know if the above is correct.

**Comment by s09bQ5** [comment]
I just forwarded the release branch to v2023.9.0.

The second command in Step 3 in RELEASING.md can be changed to `git push origin master v<the-new-version> master:release` since at that point master is pointing to the same commit as the tag. But I don't understand the comment in the following line. Where does "Flatpak" get confused if tag and branch are pushed separately?

I also don't understand why adding a semicolon to the installer script is mentioned as a cure for a broken CI build.

**Comment by barbeque-squared** [comment]
> I just forwarded the release branch to v2023.9.0.

Thanks!

> The second command in Step 3 in RELEASING.md can be changed to `git push origin master v<the-new-version> master:release` since at that point master is pointing to the same commit as the tag.

But at that point the github release page isn't out yet (because the artifacts aren't built yet). Shouldn't that be live first? Note: if you say it can all be done in one go I'll take your word for it.

> But I don't understand the comment in the following line. Where does "Flatpak" get confused if tag and branch are pushed separately?

I think I'm referring to our own CI job there. See #662. If you push master first (without the tag) it builds an artifact that has the correct version _ingame_ but in the generated filename it would still be using the _previous_ name, which makes things really confusing (or it was the other way around, I forgot).

> I also don't understand why adding a semicolon to the installer script is mentioned as a cure for a broken CI build.

Yeah that's one ugly hack. It currently builds it twice anyway: once for the branch, once for the tag, so the chances are low of it ever being needed.

It's also not meant to fix a consistently failing build. It's more that that is the only way for me to retry jobs. Take for example https://ci.appveyor.com/project/basisbit/usdx/builds/47885836. It's perfectly valid but one of the jobs decided not to download something, but in surrounding builds it was totally fine.

The reason for extra semicolon is that those lines are going to get edited anyway when setting things back to dev version, so the retrigger doesn't pollute the git too much.
