### ISSUE TITLE
UltraStar Deluxe stopped working, including the latest release

### ISSUE THREAD

**Issue by wipe2000** [UltraStar-Deluxe/USDX#736]
Hi,

'UltraStar Deluxe 2020.4.0 stable' I had on my Win11 laptop stopped working.
Everything worked fine a few weeks ago but today when I started the laptop, and after Windows installed some updates, the program won't start but interrupts to a error message.
I installed the latest releas UltraStar Deluxe v2023.6.0 but it gives the same error (screen cap attached).
![USDX_error](https://github.com/UltraStar-Deluxe/USDX/assets/143400822/ce5481e9-464f-457e-bef5-8dbe17714c6c)

I tried to remove all the songs from the library, no change. I tried to change access rights of the program files and run it admin , no change. I also tried the latest US Worldparty, same issue again.

UltraStar Deluxe - www.usdx.eu - v2023.6.0 Error Log
Date: 28.8.2023 Time: 13.13.10
-------------------
STATUS: Load Language [Initialization]
STATUS: Load Default Language English [Initialization]
STATUS: Loading Skin List [Initialization]
STATUS: Loading Theme List [Initialization]
STATUS: Searching for Theme : C:\Program Files (x86)\UltraStar Deluxe\themes\*.ini [Theme.LoadList]
STATUS: Found Theme: Deluxe.ini [Theme.LoadList]
STATUS: Found Theme: Modern.ini [Theme.LoadList]
STATUS: Website-Manager [Initialization]
STATUS: DataBase System [Initialization]
STATUS: Initializing database: "C:\Program Files (x86)\UltraStar Deluxe\Ultrastar.db" [TDataBaseSystem.Init]
STATUS: Load Ini [Initialization]
STATUS: GamePath : C:\Program Files (x86)\UltraStar Deluxe\ []
STATUS: Using config : C:\Program Files (x86)\UltraStar Deluxe\config.ini [Ini]
STATUS: Found Video Mode: 2560x1440 [Video]
STATUS: Found Video Mode: 1920x1080 [Video]
STATUS: Found Video Mode: 1760x990 [Video]
STATUS: Found Video Mode: 1680x1050 [Video]
STATUS: Found Video Mode: 1600x900 [Video]
STATUS: Found Video Mode: 1440x900 [Video]
STATUS: Found Video Mode: 1366x768 [Video]
STATUS: Found Video Mode: 1360x768 [Video]
STATUS: Found Video Mode: 1280x1024 [Video]
STATUS: Found Video Mode: 1280x800 [Video]
STATUS: Found Video Mode: 1280x768 [Video]
STATUS: Found Video Mode: 1280x720 [Video]
STATUS: Found Video Mode: 1176x664 [Video]
STATUS: Found Video Mode: 1152x864 [Video]
STATUS: Found Video Mode: 1128x634 [Video]
STATUS: Found Video Mode: 1024x768 [Video]
STATUS: Found Video Mode: 800x600 [Video]
STATUS: Found Video Mode: 720x576 [Video]
STATUS: Found Video Mode: 720x480 [Video]
STATUS: Found Video Mode: 640x480 [Video]
STATUS: Found resolutions: 20 [Video]
STATUS: Load Help [Initialization]
STATUS: Write Ini [Initialization]
STATUS: Loading: C:\Program Files (x86)\UltraStar Deluxe\themes\Modern.ini [TTheme.LoadTheme]
ERROR:  no texture type for LoadingStaticAnimation found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic2Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic3Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic4Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic5Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic6Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic7Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic8Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic9Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic10Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic11Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for NamePlayerSelectStatic12Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SongRouletteStaticCat found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxStaticActualSongCover found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for JukeboxSongMenuTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingTimeProgress found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1Avatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1TwoPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP1ThreePSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP2MSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingDuetP3RSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4FourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6SixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPStatic2 found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetFourPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP1DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP2DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP3DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP4DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP5DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPSingBar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for SingP6DuetSixPAvatar found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubHeaderBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubCurrentNoteInfoBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubVolumeSliderBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubNotesBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubP1InfoBarBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubP2InfoBarBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for EditSubSentenceBackground found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressSong found. [TTheme.ThemeLoadStatic]
ERROR:  no texture type for ScoreDownloadPopupProgressWeb found. [TTheme.ThemeLoadStatic]
STATUS: Attempting to configure InputDevice "Mikrofoni (Logitech USB Microphone)" [Bass.EnumDevices]
STATUS: InputDevice "Mikrofoni (Logitech USB Microphone)"@1x48000Hz [Bass.EnumDevices]
STATUS: Attempting to configure InputDevice "Microphone (Realtek(R) Audio)" [Bass.EnumDevices]
STATUS: InputDevice "Microphone (Realtek(R) Audio)"@2x48000Hz [Bass.EnumDevices]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common start.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Common back.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\menu swoosh.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\select music change music 50.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\option change col.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\rimshot022b.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\Applause.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder BASS_Decoder for "C:\Program Files (x86)\UltraStar Deluxe\sounds\background track.mp3" [TAudioPlaybackBase.OpenDecodeStream]
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Borderless fullscreen [SDL_SetVideoMode]
STATUS: Closing DB file [Finalization]
INFO:   TDataBaseSystem.Free [TDataBaseSystem.Destroy]
STATUS: Finalize Media [Finalization]
STATUS: Uninitialize 3D [Finalization]
STATUS: Kill Fonts [UnloadFontTextures]
STATUS: Finalize SDL [Finalization]
STATUS: Finalize Log [Finalization]

**Comment by basisbit** [comment]
This is caused by some issue with your graphics card drivers. Try reinstalling / updating them. If that also doesn't help, go into the UltraStar Play folder were the game has its files, and rename the file `[opengl32_.dll](https://github.com/UltraStar-Deluxe/USDX/blob/master/game/opengl32_.dll)` to `opengl32.dll` and then try starting the game - though this is only a workaround and will use CPU based rendering instead of using your GPU / hardware acceleration.

**Comment by barbeque-squared** [comment]
Can we keep this open until it has at least been verified that this was the issue by the OP? I also suspect it's a driver issue since it also affects other programs, and maybe there's not much we can do about giving a better error in this case, but closing it immediately also isn't really conducive to wanting to _improve_ this scenario in the future.

It's fine to close it after a while of inactivity if OP never comes back.

**Comment by basisbit** [comment]
Closing this as duplicate of #587 .

**Comment by dgruss** [comment]
the other has been closed for >2 years
