### ISSUE TITLE
[FEATURE] Make the Song Path configurable

### ISSUE THREAD

**Issue by nevyen** [UltraStar-Deluxe/USDX#76]
Hey it would be nice if it were possible to configure the song path in an ini-file. 

I had about 45 Gb of song content and they are on an external storage. So I use different operation systems and I won't store the same content 3 times. 

Thanks 
Dominic

**Comment by basisbit** [comment]
You can already do that in tge config.ini. Plesse take a look at the second point of chapter two of https://github.com/UltraStar-Deluxe/USDX/blob/master/README.md

**Comment by RattleSN4K3** [comment]
Relative paths are also possible.
`SongDir2=..\ExternalSongs`
