### ISSUE TITLE
Crash when opening songs with MPG/FLV videos

### ISSUE THREAD

**Issue by DerGitRob** [UltraStar-Deluxe/USDX#764]
### Actual behaviour

Ultrastar Deluxe crashes when opening songs that contain a video with MPG or FLV ending

### Expected behaviour

Song should be played with the video

### Details

**terminal output**
$ flatpak run --branch=stable --arch=x86_64 --command=ultrastardx eu.usdx.UltraStarDeluxe
Sorry, an error ocurred! Please report this error to the game-developers. Also check the Error.log file in the game folder.
Stacktrace:
Exception class: EAccessViolation
Message: Access violation
  $000000000050B3AB

**USDX error.log (last entries)**
INFO:   VideoStreamIndex : 0 [TVideoPlayback_ffmpeg.Open]
INFO:   Using h264 codec [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 30fps [TVideoPlayback_ffmpeg.Open]
INFO:   Using decoder FFmpeg_Decoder for "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear.mp3" [TAudioPlaybackBase.OpenDecodeStream]
ERROR:  Failed to open file "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear [VD#0].mpg" (::-1094995529)
STATUS: Begin [OnShow]
ERROR:  Failed to open file "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear [VD#0].mpg" (::-1094995529)
STATUS: Closing DB file [Finalization]
INFO:   TDataBaseSystem.Free [TDataBaseSystem.Destroy]
STATUS: Finalize Media [Finalization]
STATUS: Uninitialize 3D [Finalization]
STATUS: Kill Fonts [UnloadFontTextures]
STATUS: Finalize SDL [Finalization]
STATUS: Finalize Log [Finalization]

**The video is being played outside USDX with no problems.**

- USDX version: 2023-09 as flatpak
- Operating System + version: Linux (siduction/Debian unstable)

**Comment by barbeque-squared** [comment]
do you have a native (non-flatpak) USDX somewhere and do they work there? It's fine if you just use a Windows portable for this. if they work there, it has to be something specifc to the flatpak (which I know nothing about).

if they also don't work there, I'll need the actual video files. If you can't link them here, either PM or link them on Discord, or send me an email to my github commit email.

**Comment by s09bQ5** [comment]
This issue consists of two parts. We have FFmpeg inside the Flatpak environment rejecting the video and we have USDX crashing when FFmpeg rejects a video.

$000000000050B3AB is [here](https://github.com/UltraStar-Deluxe/USDX/blob/master/src/screens/controllers/UScreenSingController.pas#L1091). I guess fCurrentVideo is nil.

The -1094995529 error code is AVERROR_INVALIDDATA.

What does ffprobe say about All 4 One - I Swear [VD#0].mpg?

**Comment by DerGitRob** [comment]
Duration: 00:04:19.86, start: 0.188411, bitrate: 1262 kb/s
  Stream #0:0[0x1c0]: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
  Stream #0:1[0x1e0]: Video: mpeg1video, yuv420p(tv), 352x240 [SAR 200:219 DAR 880:657], 1120 kb/s, 29.97 fps, 29.97 tbr, 90k tbn

**Comment by s09bQ5** [comment]
ffmpeg-full in runtime version 22.08 does not contain the mpegps demuxer and the mpeg1video decoder. The one in 23.08 [does](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commits/release/23.08/elements/extensions/ffmpeg-full/ffmpeg.bst). I'll switch to the newer runtime with the 2023.11.0 release.

**Comment by DerGitRob** [comment]
I installed that version separately, but i guessed already that this cannot be used by USDX flatpak in that way. So it's really great that you will switch to the newer runtime in the upcoming release :)
