### ISSUE TITLE
Recommendation for check and fixing songs?

### ISSUE THREAD

**Issue by DerGitRob** [UltraStar-Deluxe/USDX#765]
What tools(s) are recommended to check and fix problems with songs?

- check for duplicate songs
- check for missing MP3/VIDEO/... tags
- check for referenced but not existing mp3/video/... files
- check for and fixing of common txt errors

**Comment by bohning** [comment]
I’d recommend the UltraStar Manager for all of those tasks.

**Comment by DerGitRob** [comment]
Great, but unfortunately that seems not to be maintained any more. The most recent version I found at https://sourceforge.net/projects/uman/files/uman/1.8.x/

Extracting uman-1.8.2-unix32.tar.gz and launching at Linux (debian unstable) gives me this error:
./uman: error while loading shared libraries: libtag.so.1: cannot open shared object file: No such file or directory

Maybe someone can help?

**Comment by basisbit** [comment]
please blame the (recently extra bad) Google algorithm for placing the link to the current repository of UltraStar Manager just below the link to the old SourceForge repository from 2017.
![image](https://github.com/UltraStar-Deluxe/USDX/assets/10870269/2523e645-fd06-4b56-a3db-b7825f0cca12)

**Comment by DerGitRob** [comment]
Thanks, I'm trying to compile.

At first, I got "Project ERROR: Unknown module(s) in QT: multimedia" which I could resolve by
apt-get install qtmultimedia5-dev

But now I have another error that I couldn't resolve
https://github.com/UltraStar-Deluxe/UltraStar-Manager/issues/21

**Comment by OverzetKaraoke** [comment]
I have been using 1.8.3 on a Windows 10/11 device for a long time now without any issues.
Can highly recommend
