### ISSUE TITLE
Game Crash by song start

### ISSUE THREAD

**Issue by plexa16** [UltraStar-Deluxe/USDX#774]
**Please, do not create duplicate issues**

### Actual behaviour

Hello i have been downloaded two new songs from https://usdb.eu. This two songs are bringing my game to crash with an Error.
The other old songs are working very fine.

### Steps to reproduce

start the game
go to sing menu
choose the song DanceMonkey-773 from tones and i
game crashed

### Details

Provide some additional information:

Error.log:
ROR:  Failed to open file "C:\Ultrastar\Tones And I\DanceMonkey-773.mp3" () [UAudio_FFmpeg]
STATUS: Could not open "C:\Ultrastar\Tones And I\DanceMonkey-773.mp3" [TAudioPlayback_Bass.OpenStream]
ERROR:  Failed to open file "C:\Ultrastar\The Greatest Showman\AMillionDreams-73.mp3" () [UAudio_FFmpeg]
STATUS: Could not open "C:\Ultrastar\The Greatest Showman\AMillionDreams-73.mp3" [TAudioPlayback_Bass.OpenStream]

Error by Starting Game
![image](https://github.com/UltraStar-Deluxe/USDX/assets/15812391/dc51fc3e-3aa2-425f-ab19-a2b96ed1d628)

OS Windows 10
Version Ultrastar 2023 v9.0

**Comment by s09bQ5** [comment]
The crash is the same as #764. It has already been fixed and the fix will be in the next release.

But these two songs appear to have problems finding the audio and video files. Please compare the file names with the ones mentioned at the top of the .txt files.

**Comment by plexa16** [comment]
thanks for your help, i have been an writing error in the txt file. Thanks for your help
