### ISSUE TITLE
Version in codebase (with a file)

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#79]
It could be helpful to have a "VERSION" file in the root of this repo. This would state the version every contribution will go into, from that specific update of that version (similar to updating tags, but stored in a text file along other source files, otherwise a code dump would not state what kind of major+minor[+patch] version the source files are from). At the time a version is released, the VERSION file updates (incrementally or with a appendix).

Current a file could look like this:

> 1.3.1+

Once the code reaches a stable condition and is ready to be packaged/distributed, it first changes and commits the version file update like

> 1.3.2

After the release, it will be updated to

> 1.3.2+

**Alternative**
The current repo will have a VERSION file with:

> 1.3.2

And with an release it directly increments the major/minor/patch number (via a commit)

> 1.3.3

**Comment by basisbit** [comment]
how about using the keywords for that?
for example "1.3.1_trunk"?

**Comment by RattleSN4K3** [comment]
Trunk is a SVN expression. Isn't that easy to understand witout a SVN background. "+" is consistently used in Unix packages.

Instead of "trunk", I'd use "dev" if not "+".
"1.3.1_dev" or "1.3.1dev"

**Comment by RattleSN4K3** [comment]
I've talked with @basisbit in the gitter room. He said, I should gibt it a try (or something like that :wink: ).

f1533178835cef9ffb07b52e346e24c7c2ffce4d
>
This version will define what kind of version the code belongs to - when dumped. This version is for development not for release. This version string is compatible to the semantic versioning 2.0. The appendix ("+") can be seen as meta data.

>This specific appendix ("+") is used to differentiate the working files from the release (and its source code). Once a build will be released, the VERSION file will be updated to the precedence of the release name, and committed. Right after that point, it will be changed to that new VERSION string with the appendix. This will result that there's only 1 specific code dump with the matching version string of the release (its precedence). This commit is generally tagged as release, it can have other release related files committed.
>
If a release does have extra tags, such as alpha, beta and all that, it can be included in the release version file (check semver.org). An additional plain text name should be entered into a new line.
>
That said, if a new release is called "2.4.5-beta", this will be the committed content of the VERSION file, the master branch will get a new VERSION commit with the string "2.4.5+". This will state an ongoing development from the version 2.4.5. It doesn't matter if it's the same as a possible alpha release of that version. The code changes went in to the main branch (master). Branching the tagged release, that branch should update its version file matching the same string (including the pre-release identifier). This should be used if fixes to a specific release are created.
>
If an internal/public dev pre-release is published, it should have that VERSION file string from that codebase including in the name, additionally it can have a readable name right after "+". Other meta data should be added according the recommendation on semver.org. All these builds (but not the release) should have a readable metadata suffix in order to differentiate test builds build from each other (preferably a date is understandable across all user bases).
>
All in all, this should help providing pre-releases, test builds, fork builds and not mix it with the release cycle, and its versioning.

Keeping this issue opened for the next release.

**Comment by basisbit** [comment]
The version number is being used afaik. Thus, the issue can be closed.
