### ISSUE TITLE
Appimage on Ubuntu and config.ini

### ISSUE THREAD

**Issue by maggiv8** [UltraStar-Deluxe/USDX#793]
### Actual behaviour

Tell us what happens
When opening the application via Appimage, no songs are being loaded. Where do I define my config.ini file for song file directory settings and definition? I added a config.ini file in the same directory as the app image and also tried ~/.config/ultrastardx/, but it doesn't seem to be considered. 

### Expected behaviour
config.ini configuration should be considered, but it is currently unclear where to place the config.ini file.

### Steps to reproduce

1. Open Ultrastar Appimage on Ubuntu 22.04 with command './UltraStarDeluxe-v2023.12.0-0-x86_64.AppImage'. config.ini located in the same directory as the app image and also ~/.config/ultrastardx/.
2. Click on 'Sing'.
3. Message 'No songs are being loaded'.

### Details

Provide some additional information:

- USDX version: v2023.12.0.0
- Operating System + version: Ubuntu 22.04

**Comment by basisbit** [comment]
Where did you get this appImage file from?

**Comment by s09bQ5** [comment]
The AppImage uses ~/.ultrastardx/config.ini

**Comment by maggiv8** [comment]
Awesome, thank you.  That worked.
