### ISSUE TITLE
Selection of 5 Players not possible

### ISSUE THREAD

**Issue by tobijdc** [UltraStar-Deluxe/USDX#8]
Steps to reproduce:
1. Start USDX
2. Click on Sing
3. Select Players (5)
This is not possible.

Everything between 1-6 is possible except for 5.
Is there a particular reason for that?

**Comment by basisbit** [comment]
5 players would not fit on the screen nicely/evenly. I don't see any usecase where 5 player selection would ne necessary. just choose 6 :)
