### ISSUE TITLE
OpenGL rendering

### ISSUE THREAD

**Issue by vrs99-hub** [UltraStar-Deluxe/USDX#806]
When I open the program I get the message 'You appear to be using software rendering OpenGL. Expect bad performance'. And after that I do get some really bad performance.

Unfortunately, there is no setting to change the renderer. I've not experienced this behavior with other programs, games, or emulators. The one peculiar thing in my setup that is suspect might be an issue is that I have a gaming laptop with an Nvidia graphics card but also integrated AMD graphics. 

This is a problem with the 2024.1.0 portable version. I also tested the 2020.4.0 portable version which has the same issue except it doesn't show the OpenGL message.

I'm on Windows 11 with all updates installed and I have up to date graphic drivers as well.

**Comment by basisbit** [comment]
Try installing the graphics card drivers from your computer's manufacturer's support website. The drivers which come with Windows automatically tend to not have OpenGL acceleration for older integrated Intel GPUs any more.

As a workaround, you can also try renaming the `opengl32_.dll` file in the installation folder of UltraStar Deluxe to `opengl32.dll` (without the underscore) and then restart the game. Then it will still use software-rendering, but it should at least have better performance than before.

**Comment by vrs99-hub** [comment]
I am already using the manufacture's drivers so that didn't change anything. However, you suggestion regarding the dll file fixed it! Very much appreciated!

**Comment by barbeque-squared** [comment]
Closing this because I don't think there's much we can do to make this nicer.

**Comment by s09bQ5** [comment]
We are currently telling users to use a build of [LLVMpipe](https://docs.mesa3d.org/drivers/llvmpipe.html) from Mesa 11.0.5, released in November 2015. How about making 32 bit builds of the current Mesa code with its [OpenGL on Vulkan](https://docs.mesa3d.org/drivers/zink.html) and [OpenGL on Direct3D 12](https://docs.mesa3d.org/drivers/d3d12.html) drivers? I found a [build script on Github](https://github.com/mmozeiko/build-mesa), but it still needs to be modified for 32 bit DLLs and it would be nicer to use a MinGW toolchain.

**Comment by basisbit** [comment]
@s09bQ5 You are very welcome to create a pull request for that. The OpenGL version from back then was one which I tested on various systems and it always worked reliably as a workaround when proper GPU drivers aren't yet installed. Imho we should not spend any time because of vendors dropping their support for older hardware.

**Comment by s09bQ5** [comment]
> Imho we should not spend any time because of vendors dropping their support for older hardware.

But it's new hardware that doesn't support the old OpenGL 2 API.

**Comment by basisbit** [comment]
@s09bQ5 USDX uses OpenGL 1.4+ API, not the "new" OpenGL 2 API which recently some vendors stopped supporting. What you are referring to has nothing to do with this issue here.

**Comment by s09bQ5** [comment]
OpenGL 2.x is still the old fixed pipeline API and fully compatible to OpenGL 1.4. The new OpenGL API is 3.x/4.x and compatibility to the old API has been made optional there.
