### ISSUE TITLE
Where to add songs in Linux Mint ?

### ISSUE THREAD

**Issue by tynpawel** [UltraStar-Deluxe/USDX#808]
Sorry for that but I have to raise this question here as I do not know other channels to ask

### Details

Provide some additional information: 
I just installed 2023.12.0 and have not song loaded. Can you please tell me where to put the songs folder so that USDX can find my songs? 

- USDX version: 2023.12.0
- Operating System + version: Linux Mint 21.2

**Comment by barbeque-squared** [comment]
If this is a native installed version (not flatpak or appimage) the directory USDX looks in for songs is `~/.ultrastardx/songs`

If your songs are located elsewhere, add them to the config.ini as described in https://github.com/UltraStar-Deluxe/USDX/#3-configuration NOTE: you'll have to use absolute paths (for now...)

**Comment by tynpawel** [comment]
I have installed it via the built in Software Manager. Added my songs in `~/.ultrastardx/songs` . But still it shows the error massage `No songs loaded`
Where can i find the config.ini ?

**Comment by s09bQ5** [comment]
I doubt any distribution ships their own build of USDX. So you are most likely using the flatpak that we published on flathub. Try ~/.var/app/eu.usdx.UltraStarDeluxe/.ultrastardx/songs/.

**Comment by tynpawel** [comment]
@s09bQ5 Thx this was working! Great :+1:
