### ISSUE TITLE
USDX 2024.1.0 does not care about SongDir1 entry in config.ini

### ISSUE THREAD

**Issue by jazz-messenger** [UltraStar-Deluxe/USDX#809]
### Actual behaviour
After the initial call of USDX a folder was created in ~/Music/UltraStar Deluxe/.
config.ini is in ~/Library/Application Support/UltraStarDeluxe1.3/ which has been created by USDX, too.
I changed the Directories section where SongDir1 was initially empty to

[Directories]
SongDir1=~/Music/UltraStar Deluxe
WebScoresDir=

I created song subfolders inside the folder ~/Music/UltraStar Deluxe containing a txt file plus jpg mp4 and mp3, but USDX tells me that it did not find any song.

### Expected behaviour
USDX shows me the song I created the sub folder before.

### Steps to reproduce
see above

### Details
Provide some additional information:

- USDX version: 2024.1.0
- Operating System + version: macOS Sonoma 14.3

**Comment by jazz-messenger** [comment]
I added another SongDir entry. And guess what... now it worked.

**Comment by barbeque-squared** [comment]
Did you add the other entry as an absolute path by any chance? I remember also trying to use `~` at first but at least on Linux that doesn't appear to get expanded.

It's probably not too difficult to replace a leading `~` with the actual home directory internally, for it appears to be a common enough source of issues/confusion? I doubt it would break anyone's existing config, and would also make things more portable for Linux/Mac users.
(just don't expect USDX to start supporting generic environment variables in the config)
