### ISSUE TITLE
Song screen shows "PONY" instead of "Time"

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#81]
Song screen shows wrong builds image/text. Instead of "Time", "PONY" is displayed.
![usdx1 3 2_songoline2_l1](https://cloud.githubusercontent.com/assets/6833006/16997848/760b9c94-4eb7-11e6-95f4-6a5cf053ab31.jpg)

**Comment by basisbit** [comment]
that is just a pun in the english translation file. no need for an issue here.
Pony sounds similar to some other karaoke creator company ;-)

**Comment by RattleSN4K3** [comment]
oO. It's still an issue. PONY is nothing anyone could related to seein this near the time line.

This is still Ultrastar Deluxe, right.

**Comment by basisbit** [comment]
actually that is a pun which most people will understand and just laugh about. This game is very similar to singstar, but having the original company name there would be a copyright violation. this will not be in the release, but rather is fun for development versions. sort of like an easte egg.

**Comment by RattleSN4K3** [comment]
... playing the legislation card
It could be a "copyright violation" with the original name, but with this "pun"-intended alternative, you could get into other trouble. After all this should be avoided.

If this isn't just because of that "fun". Why closing this issue. It should be "time" anyway.

**Comment by basisbit** [comment]
agree. it still was funny and no one complained for almost half a year^^
I closed the issue because having an issue regarding this is just plainly wasting time. It is not correct, so simply just fix it right away. No need for huge discussions.

**Comment by RattleSN4K3** [comment]
Was creating images for #83 and just did the additional issue for that _problem_.

I am working on other stuff, nor I am the original person who did the "PONY" stuff. An explanation/intent to be read somewhere is the go to. Otherwise this project will be full of reverts by each other.

**Comment by basisbit** [comment]
nah, don't worry, that will not happen. We work together after all.
