### ISSUE TITLE
Song screen's lyric-font-"Plain"-styled 2nd line is unreadable

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#82]
The 2nd lyric line is not readable with the "Plain" font selected.
![usdx1 3 2_songplain_l1](https://cloud.githubusercontent.com/assets/6833006/16997917/c2cc70f8-4eb7-11e6-8f6d-ecc9ffc4e04a.jpg)

Judging from some new features, it could be related to the Jukebox coloring.

**Comment by basisbit** [comment]
jukebox and normal singing should have the same coloring. this is work in progress. as quick fix, the default colors for first and second line should be changed to white.

**Comment by RattleSN4K3** [comment]
White has the same problem. Süeaking of "should have the same coloring", that should be an option.

Personally:
I don't like the new coloring / Jukebox override.

**Comment by basisbit** [comment]
jukebox and normal singing should be unified piece by piece. this is just one part of it. Having the possibility to change the color in the game settings definitely is a neat feature we should keep.

**Comment by RattleSN4K3** [comment]
> Having the possibility to change the color in the game settings definitely is a neat feature we should keep.

I don't disagree.

But the jukebox has a different theme and layout. Singing with points does need a good readable text whereas with the Jukebox the side-by-side lyric is a nice-to-have thing. Not even the color could be different, but also the size. So there must be at least some options which are separate for each "singing screen". Coloring is also an important key of duets (or party mode which slightly relates to it in some plugin cases).
