### ISSUE TITLE
Editor lyric line is squashed

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#83]
Compared to previous releases, the editor lyric is squashed.

Judging from a different issue, it could be an roudning error in the drawing code.

# USDX 1.3 (dev)

##Editor
![usdx1 3 2_editor_l1](https://cloud.githubusercontent.com/assets/6833006/16998175/9b15f0c4-4eb8-11e6-93ae-ed0a6ca6a863.jpg)
![usdx1 3 2_editor_l2](https://cloud.githubusercontent.com/assets/6833006/16998178/9cb1686e-4eb8-11e6-8a20-6ce6c89c6925.jpg)
![usdx1 3 2_editor_l3](https://cloud.githubusercontent.com/assets/6833006/16998179/9e09dcc8-4eb8-11e6-81cd-99b6285808b3.jpg)
![usdx1 3 2_editor_l4](https://cloud.githubusercontent.com/assets/6833006/16998182/9f654f1c-4eb8-11e6-840f-95e52505bd41.jpg)

## OLine2
![usdx1 3 2_songoline2_l1](https://cloud.githubusercontent.com/assets/6833006/16998142/77aa2a4c-4eb8-11e6-8d42-35049c087ea1.jpg)
![usdx1 3 2_songoline2_l2](https://cloud.githubusercontent.com/assets/6833006/16998143/7979ecc2-4eb8-11e6-9d32-8475262a3b54.jpg)
![usdx1 3 2_songoline2_l3](https://cloud.githubusercontent.com/assets/6833006/16998145/7c1bb10e-4eb8-11e6-86c3-7d13e3f83255.jpg)
![usdx1 3 2_songoline2_l4](https://cloud.githubusercontent.com/assets/6833006/16998146/7da497f2-4eb8-11e6-9b78-5c2f1006547b.jpg)

## Plain
![usdx1 3 2_songplain_l1](https://cloud.githubusercontent.com/assets/6833006/16998149/85712392-4eb8-11e6-8b5b-411e25aca189.jpg)
![usdx1 3 2_songplain_l2](https://cloud.githubusercontent.com/assets/6833006/16998152/8747c4be-4eb8-11e6-8ee9-78bd80da793d.jpg)
![usdx1 3 2_songplain_l3](https://cloud.githubusercontent.com/assets/6833006/16998155/894cef82-4eb8-11e6-89a2-528f323b4a2c.jpg)
![usdx1 3 2_songplain_l4](https://cloud.githubusercontent.com/assets/6833006/16998162/8b57ebe2-4eb8-11e6-8e49-145b1ed49577.jpg)

# USDX 1.1

## Editor
![usdx1 1 0_editor_l1](https://cloud.githubusercontent.com/assets/6833006/16998196/aa8c1ff6-4eb8-11e6-9a06-f9c3e7f3c6d3.jpg)
![usdx1 1 0_editor_l2](https://cloud.githubusercontent.com/assets/6833006/16998198/ac009830-4eb8-11e6-86a3-b65e906cd367.jpg)
![usdx1 1 0_editor_l3](https://cloud.githubusercontent.com/assets/6833006/16998199/ad81e92a-4eb8-11e6-9241-609d8c3f2d5b.jpg)
![usdx1 1 0_editor_l4](https://cloud.githubusercontent.com/assets/6833006/16998201/af7a55d2-4eb8-11e6-801b-db1b403b3e8a.jpg)

## Oline2
![usdx1 1 0_songoline2_l1](https://cloud.githubusercontent.com/assets/6833006/16998211/b8ec1920-4eb8-11e6-9ea8-04e3c0549d43.jpg)
![usdx1 1 0_songoline2_l2](https://cloud.githubusercontent.com/assets/6833006/16998213/bb47cf84-4eb8-11e6-9514-74088e042e41.jpg)
![usdx1 1 0_songoline2_l3](https://cloud.githubusercontent.com/assets/6833006/16998215/bcad3f3a-4eb8-11e6-984b-c9184051df20.jpg)
![usdx1 1 0_songoline2_l4](https://cloud.githubusercontent.com/assets/6833006/16998216/be42397c-4eb8-11e6-88ce-e3bd2143e608.jpg)

## Plain
![usdx1 1 0_songplain_l1](https://cloud.githubusercontent.com/assets/6833006/16998221/c27b8016-4eb8-11e6-9e34-e2f1e4a046e2.jpg)
![usdx1 1 0_songplain_l2](https://cloud.githubusercontent.com/assets/6833006/16998224/c429a7e4-4eb8-11e6-8562-5d00bd75dd68.jpg)
![usdx1 1 0_songplain_l3](https://cloud.githubusercontent.com/assets/6833006/16998226/c5c3e93e-4eb8-11e6-99b6-3ec71ada5131.jpg)
![usdx1 1 0_songplain_l4](https://cloud.githubusercontent.com/assets/6833006/16998229/c7573206-4eb8-11e6-9050-75a3852578ac.jpg)

**Comment by bohning** [comment]
The OSX version is now compilable and runnable - so thank you very much for your efforts and good work!

Unfortunately, this error still persists:
Editor on first open:
![bildschirmfoto 2016-07-31 um 15 37 40](https://cloud.githubusercontent.com/assets/1497707/17276870/1d39f65c-5735-11e6-9e54-1b73ca62a639.png)

Editor after switching to second line and back to first:
![bildschirmfoto 2016-07-31 um 15 37 45](https://cloud.githubusercontent.com/assets/1497707/17276874/5c34a23a-5735-11e6-99d4-72b4a239bab9.png)

**Comment by RattleSN4K3** [comment]
Nothing has been done regarding that. I can also not reproduce the case where it would be shown properly. However, when I'm going to investigate/fix this issue, it doesn't even matter if switching would correct something.

**Comment by RattleSN4K3** [comment]
Fixed with db6b0ef. @bohning, can you check if it also working on your side (in your case)?

**Comment by RattleSN4K3** [comment]
Confirmed in #33.
