### ISSUE TITLE
CI cannot build ProjectM

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#834]
example: https://ci.appveyor.com/project/basisbit/usdx/builds/49748770

I can't do anything with this error as it's a Windows thing. I like the part where github isn't showing failed pipelines, hence I only noticed it now. It apparently also prevents the _non-Windows_ builds from being built.
I know there's plans to move away from AppVeyor but right now this is blocking making a new release.

For completeness future reference, the entire build output is:
```
Build started
git clone -q --branch=master https://github.com/UltraStar-Deluxe/USDX.git C:\projects\usdx
git checkout -qf 338bf8011539679f8c20c6f7a5d53dd95ad6fe2a
The project file "projectM-cwrapper.vcproj" is in the ".vcproj" file format, which MSBuild no longer supports. Please convert the project by opening it in the Visual Studio IDE or running the conversion tool, or use MSBuild 3.5 or earlier to build it.
```

**Possible solutions**
Well, let's be real, we should probably just fix the CI. The other option would be to just stop using ProjectM, which although I'm personally totally in favour of, this is the wrong reason to drop it.

**Comment by basisbit** [comment]
why do we build projectM for Windows each time anyways? Wouldn't just getting the official dll download be a better fix while also saving buil-pipeline minutes?

**Comment by s09bQ5** [comment]
> why do we build projectM for Windows each time anyways?

We don't. The CI just thinks that it will be asked to build the .vcproj file.
