### ISSUE TITLE
Duet not working as expected

### ISSUE THREAD

**Issue by Pilegrim** [UltraStar-Deluxe/USDX#838]
**We tried downloading duet versions of songs from USDB, but when opening them in Ultrastar Deluxe, they don't seem to work as intended. Can't find anything elsewhere so I'm asking here.**

### Actual behaviour

When the song is played, there are no seperate tracks for both players, although the file kinda seems to be working because sometimes the lyrics progress without the tracks matching up. Also, after a track it says awful everytime, even though most of the notes should have been hit.

### Expected behaviour

Songs should play with seperate tracks for each of the 2 singers.

### Steps to reproduce

1. Download a [DUET] song from usdb by searching duet in the edition tab (example song we tried: https://usdb.animux.de/?link=detail&id=10616)
2. Import the song to Ultrastar as you would with normal songs
3. Open Ultrastar and sing the song

### Details

- USDX version: 2024.5.0
- Operating System + version: Windows 11, 23H2

**Comment by bohning** [comment]
You need to re-insert "P1" and "P2" into the txt file manually, because unfortunately they get deleted when submitted to usdb. P1 goes on a separate line before the first note of singer 1, P2 goes on a separate line before the first note of singer 2.
