### ISSUE TITLE
#RESOLUTION:0 results in crash when opening song in editor

### ISSUE THREAD

**Issue by rosepetaldevourer** [UltraStar-Deluxe/USDX#859]
### Actual behaviour

Game crashes when trying to open a specific song file in editor mode.

### Expected behaviour

No crash but opening in editor mode

### Steps to reproduce

1.    Open the ultrastardx.exe
2.    Select Sing.
3.    Select song Love Hina - Sakura Sakura
4.    Press E to go into editor mode
5.    Crash happens before the editor mode opens.

### Details

Provide some additional information:

Error message:
![image](https://github.com/UltraStar-Deluxe/USDX/assets/91917605/8e48a834-729e-4257-ac4b-a028402e4f1e)

Txt-File of the song:
[Sakura Sakura - Love Hina.txt](https://github.com/user-attachments/files/15857878/Sakura.Sakura.-.Love.Hina.txt)

Error log after first crash:
[Error.log](https://github.com/user-attachments/files/15857881/Error.log)

- USDX version: 2024.5.1
- Operating System + version: Edition Windows 10 Home
Version 22H2
Installed on ‎23/‎02/‎2021
OS build 19045.4529
Experience Windows Feature Experience Pack 1000.19058.1000.0

**Comment by s09bQ5** [comment]
Please delete the line `#RESOLUTION:0` from your .txt file.
Yes, we should ignore invalid resolution values.
