### ISSUE TITLE
Song screen fade out shows image even if video was used

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#86]
Start a song with a video and an image set. Verify options like `VideoEnabled=On`, `Oscilloscope=Off` (or something similar) and `ScreenFade=On`.

Once you press Escape (in order to return to previous screen and abort the singing), the background image is shown during the fade. This can be irritating.

![animation60](https://cloud.githubusercontent.com/assets/6833006/17028158/e89bf2fe-4f66-11e6-8d4a-55700b5688c3.gif)

**Comment by basisbit** [comment]
this was a requested feature and thus was implemented on purpose. Please leave it in there.

**Comment by RattleSN4K3** [comment]
> this was a requested feature and thus was implemented on purpose.

Why? To me, it doesn't make any sense having it only shown for the fading process. It would be better if the video still image is used.

> Please leave it in there.

Not touching anything. But if this inconsistent behavior was requested, why not having it at least as config option (if not advanved).

**Comment by ePirat** [comment]
I agree that this is weird behavior, what is the reasoning behind it?

**Comment by bohning** [comment]
Surprised to learn that this was actually a feature request. I agree with @ePirat, it always irritated me and until just now always thought it was a bug... I'd love to be able to turn that off (and +1 for the reasoning behind the request).

**Comment by barbeque-squared** [comment]
Is this still a thing in the current versions? I've been running with animations disabled since forever, but I have vague recollections of this _exact_ behaviour being one of my main reasons to disable them in the first place.

Considering it's been 7 (!) years and there's been no reason given for _why_ this feature was ever requested/needed, and there's now at least 4 people irritated by it, I'm fine with changing it. The way I see it, worst case the original requester might show up one day. I'd have done this earlier but I don't scroll through all the old issues that often.

I also suspect this isn't the only thing in USDX that is really just someone's personal feature.

**Comment by bohning** [comment]
IIRC, this "feature" resulted from a request from the "My Little Karaoke" (https://www.mylittlekaraoke.com) development fork of USDX, but I might be wrong. It has always irritated me tbh, so I'd welcome a removal.

Maybe @basisbit has more details.

**Comment by basisbit** [comment]
> I also suspect this isn't the only thing in USDX that is really just someone's personal feature.

Can confirm this is a feature for me which I very much like. Please do not remove and please do not make not-standard. Seeing the art for the 2 seconds or so at the end makes me happy, especially during bigger events where I know others also get to smile thanks to it.

**Comment by basisbit** [comment]
(but as usual, please go with what the majority of active developers wants, not with what I want for whatever weird reason that I might mention)

**Comment by MairusuPawa** [comment]
> Yes, still in issue. IIRC, this "feature" resulted from a request from the "My Little Karaoke" (https://www.mylittlekaraoke.com) development fork of USDX, but I might be wrong. It has always irritated me tbh, so I'd welcome a removal.
> 
> Maybe @basisbit has more details.

Hey! I'm not sure I made the request back then, but that's entirely possible. A few things come to mind:

- at the time, video playback was a whole other can of worms in USDX. It's possible that switching back to a static frame helped a lot before running the transition.
- It may also have been much less jarring back then, and gave enough time for players to have the opportunity to have a look at the static background art (there's some neat stuff out there).
- Another reasoning might have been to simply fallback to a static picture at the end of video playback, so the screen isn't just stuck on the last video frame - usually a boring black screen if you're lucky, or a frame full of video artifacting and weird faces if not.

I do agree that this is quite jarring now anyway, and I'd generally vote in favor of a removal too; might want to consider my last point though eg. check for video length and still allow to fallback to an alternative background display (image or visualization) if said video is "significantly" shorter than the song playback time.
