### ISSUE TITLE
Update docker image OS for Linux builds

### ISSUE THREAD

**Issue by DeinAlptraum** [UltraStar-Deluxe/USDX#864]
(Description edited after discussion below)

We've reached EOL for the Centos 7 image (see https://endoflife.date/centos), which is currently used by the docker image for the Linux build. The image needs to be changed to change the Yum mirrors to the archive at `vault.centos.org`

This is also the reason for currently failing CI builds on Linux

**Comment by s09bQ5** [comment]
NACK. For AppImage builds we want the build system to be as old as possible.

**Comment by DeinAlptraum** [comment]
Do you prefer switching to the `vault.centos.org` mirrors?

**Comment by s09bQ5** [comment]
yes, let's do that instead
