### ISSUE TITLE
Mouse button selection (hover) doesn't update description text

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#87]
In some menus, using the Mouse to selection menu items doesn't update the description text. Using keyboard works as intended.

![animation](https://cloud.githubusercontent.com/assets/6833006/17080826/6a4ece6e-513f-11e6-8364-37d3bd4e1484.gif)

_(Note: Issued because of logging)_

**Comment by RattleSN4K3** [comment]
Resolved with 2c2cb21
![animation1](https://cloud.githubusercontent.com/assets/6833006/17080872/f3eee126-5140-11e6-9d64-081c3ac614cf.gif)

**Comment by basisbit** [comment]
Nice! Good work!
