### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [UltraStar-Deluxe/USDX#887]
**Please, do not create duplicate issues**

### Actual behaviour

App is hidden by default on Linux Mint and warnings appear on elementaryOS because the app is unverified

### Expected behaviour

The app should appearance be downloadable as normal

### Steps to reproduce

1. Open the default app store on the latest versions of Linux Mint or elementaryOS
2. Search for ultrastar
3. Note it's absence or a warning on download

### Details

Provide some additional information:

- Here is a link to Flathub's documentation for verification https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by s09bQ5** [comment]
Ok, flathub says
> Create a page at https://usdx.eu/.well-known/org.flathub.VerifiedApps.txt containing the following token:
> 1e80abb6-1364-46fa-bd91-f0abf47396b9

I'm not familiar with Jekyll. Do we have to create a file `.well-known/org.flathub.VerifiedApps.txt` in https://github.com/UltraStar-Deluxe/ultrastar-deluxe.github.io/ and add a snippet
```
include:
 - .well-known
```
to `_config.yml`?

**Comment by Roman19S** [comment]
I believe you have to add the token to your website

**Comment by basisbit** [comment]
@s09bQ5 is there no option to verify using a well known dns entry?

**Comment by barbeque-squared** [comment]
I think you're on the right track with the ultrastar-deluxe.github.io repository!

I think we have to either
- create a page with [layout: null](https://jekyllrb.com/docs/front-matter/) and figure out how to exclude it from the menu structure, or
- maybe it will get automatically copied? I don't know: https://jekyllrb.com/docs/structure/ at the end of the table "Other Files/Folders"

But what I think would be even more useful is a small Readme in that repository with some basic commands on how to get it compiling/running locally, and then do this one. And maybe also look into not having a six year old Jekyll version...

**Comment by barbeque-squared** [comment]
This seems to work: https://usdx.eu/.well-known/org.flathub.VerifiedApps.txt
I don't know how to get flathub to say it's verified now though

**Comment by Roman19S** [comment]
Sometimes it just takes a bit. It's done now:
![Screenshot_20240908-065808_Firefox_1](https://github.com/user-attachments/assets/460f629e-b28c-44e7-b807-692157af1534)
